//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSAttributedString;

@interface _ASTextNodeCachedMetrics : NSObject
{
    NSAttributedString *_attributedString;
    float _lineHeight;
    float _descender;
}

@property(nonatomic) float descender; // @synthesize descender=_descender;
@property(nonatomic) float lineHeight; // @synthesize lineHeight=_lineHeight;
@property(nonatomic) __weak NSAttributedString *attributedString; // @synthesize attributedString=_attributedString;
- (void).cxx_destruct;

@end

