//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface _FBBadgeImage : NSObject
{
}

+ (id)badgeImageWithSize:(struct CGSize)arg1 cornerRadius:(float)arg2 color:(id)arg3;
+ (id)blueBadgeImage;
+ (id)redBadgeImage;

@end

