//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@protocol ASDisplayNodeAsyncTransactionContainer
@property(readonly, nonatomic) unsigned int asyncdisplaykit_asyncTransactionContainerState;
@property(nonatomic, getter=asyncdisplaykit_isAsyncTransactionContainer, setter=asyncdisplaykit_setAsyncTransactionContainer:) BOOL asyncdisplaykit_asyncTransactionContainer;
- (void)asyncdisplaykit_asyncTransactionContainerStateDidChange;
- (void)asyncdisplaykit_cancelAsyncTransactions;
@end

