//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "ASControlNode.h"

#import "FBRichStoryTextNode-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class ASHighlightOverlayLayer, ASTextNodeRenderer, ASTextNodeShadower, NSArray, NSAttributedString, NSString, UIColor, UILongPressGestureRecognizer;
@protocol ASTextNodeDelegate;

@interface ASTextNode : ASControlNode <FBRichStoryTextNode, UIGestureRecognizerDelegate>
{
    struct CGSize _shadowOffset;
    struct CGColor *_shadowColor;
    float _shadowOpacity;
    float _shadowRadius;
    NSAttributedString *_composedTruncationString;
    NSString *_highlightedLinkAttributeName;
    id _highlightedLinkAttributeValue;
    struct _NSRange _highlightRange;
    ASHighlightOverlayLayer *_activeHighlightLayer;
    struct Mutex _rendererLock;
    struct CGSize _constrainedSize;
    ASTextNodeRenderer *_renderer;
    ASTextNodeShadower *_shadower;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    BOOL _longPressCancelsTouches;
    NSAttributedString *_attributedString;
    NSAttributedString *_truncationAttributedString;
    NSAttributedString *_additionalTruncationMessage;
    int _truncationMode;
    unsigned int _maximumLineCount;
    UIColor *_placeholderColor;
    NSArray *_linkAttributeNames;
    unsigned int _highlightStyle;
    id <ASTextNodeDelegate> _delegate;
    struct UIEdgeInsets _placeholderInsets;
}

+ (struct CGRect)_adjustRendererRect:(struct CGRect)arg1 forShadowPadding:(struct UIEdgeInsets)arg2;
+ (float)_highlightOpacityForStyle:(unsigned int)arg1;
+ (struct CGColor *)_highlightColorForStyle:(unsigned int)arg1;
+ (void)drawRect:(struct CGRect)arg1 withParameters:(id)arg2 isCancelled:(CDUnknownBlockType)arg3 isRasterizing:(BOOL)arg4;
@property(nonatomic) BOOL longPressCancelsTouches; // @synthesize longPressCancelsTouches=_longPressCancelsTouches;
@property(nonatomic) __weak id <ASTextNodeDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned int highlightStyle; // @synthesize highlightStyle=_highlightStyle;
@property(copy, nonatomic) NSArray *linkAttributeNames; // @synthesize linkAttributeNames=_linkAttributeNames;
@property(nonatomic) struct UIEdgeInsets placeholderInsets; // @synthesize placeholderInsets=_placeholderInsets;
@property(retain, nonatomic) UIColor *placeholderColor; // @synthesize placeholderColor=_placeholderColor;
@property(nonatomic) unsigned int maximumLineCount; // @synthesize maximumLineCount=_maximumLineCount;
@property(nonatomic) int truncationMode; // @synthesize truncationMode=_truncationMode;
@property(copy, nonatomic) NSAttributedString *additionalTruncationMessage; // @synthesize additionalTruncationMessage=_additionalTruncationMessage;
@property(copy, nonatomic) NSAttributedString *truncationAttributedString; // @synthesize truncationAttributedString=_truncationAttributedString;
@property(copy, nonatomic) NSAttributedString *attributedString; // @synthesize attributedString=_attributedString;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)_prepareTruncationStringForDrawing:(id)arg1;
- (id)_composedTruncationString;
- (struct _NSRange)_additionalTruncationMessageRangeWithVisibleRange:(struct _NSRange)arg1;
- (void)_invalidateTruncationString;
@property(readonly, nonatomic) unsigned int lineCount;
@property(readonly, nonatomic, getter=isTruncated) BOOL truncated;
@property(readonly, nonatomic) struct UIEdgeInsets shadowPadding;
- (void)setShadowRadius:(float)arg1;
- (float)shadowRadius;
- (void)setShadowOpacity:(float)arg1;
- (float)shadowOpacity;
- (void)setShadowOffset:(struct CGSize)arg1;
- (struct CGSize)shadowOffset;
- (void)setShadowColor:(struct CGColor *)arg1;
- (struct CGColor *)shadowColor;
- (BOOL)_pendingTruncationTap;
- (BOOL)_pendingLinkTap;
- (void)_handleLongPress:(id)arg1;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)placeholderImage;
- (struct CGRect)frameForTextRange:(struct _NSRange)arg1;
- (struct CGRect)trailingRect;
- (id)highlightRectsForTextRange:(struct _NSRange)arg1;
- (id)rectsForTextRange:(struct _NSRange)arg1;
- (id)_rectsForTextRange:(struct _NSRange)arg1 measureOption:(unsigned int)arg2;
- (void)_clearHighlightIfNecessary;
- (void)_setHighlightRange:(struct _NSRange)arg1 forAttributeName:(id)arg2 value:(id)arg3 animated:(BOOL)arg4;
- (void)setHighlightRange:(struct _NSRange)arg1 animated:(BOOL)arg2;
@property(nonatomic) struct _NSRange highlightRange;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (id)_linkAttributeValueAtPoint:(struct CGPoint)arg1 attributeName:(out id *)arg2 range:(out struct _NSRange *)arg3 inAdditionalTruncationMessage:(out char *)arg4;
- (id)linkAttributeValueAtPoint:(struct CGPoint)arg1 attributeName:(out id *)arg2 range:(out struct _NSRange *)arg3;
- (id)drawParametersForAsyncLayer:(id)arg1;
- (void)_invalidateShadower;
- (id)_shadower;
- (void)_invalidateRenderer;
- (id)_renderer;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)didLoad;
- (void)clearRendering;
- (void)displayDidFinish;
- (struct CGSize)calculateSizeThatFits:(struct CGSize)arg1;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)initWithViewBlock:(CDUnknownBlockType)arg1;
- (id)initWithLayerBlock:(CDUnknownBlockType)arg1;
- (id)init;
- (struct CGPoint)minimorphAnchorPoint;
- (id)_computeCachedMetrics;
- (id)_cachedMetrics;
- (void)removeIconAnimations;
- (void)addIconAnimation:(id)arg1;
- (id)textLayer;
@property(nonatomic, getter=isInnerTextNodeLayerBacked) BOOL innerTextNodeLayerBacked;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

