//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class CKComponentScopeFrame, NSHashTable;
@protocol CKComponentStateListener;

@interface CKComponentScopeRoot : NSObject
{
    struct unordered_multimap<CKComponentAnnouncedEvent, CKComponentController *, std::__1::hash<unsigned int>, std::__1::equal_to<unsigned int>, std::__1::allocator<std::__1::pair<const CKComponentAnnouncedEvent, CKComponentController *>>> _eventRegistration;
    NSHashTable *_boundsAnimationComponents;
    id <CKComponentStateListener> _listener;
    int _globalIdentifier;
    CKComponentScopeFrame *_rootFrame;
}

+ (id)rootWithListener:(id)arg1;
@property(readonly, nonatomic) CKComponentScopeFrame *rootFrame; // @synthesize rootFrame=_rootFrame;
@property(readonly, nonatomic) int globalIdentifier; // @synthesize globalIdentifier=_globalIdentifier;
@property(readonly, nonatomic) __weak id <CKComponentStateListener> listener; // @synthesize listener=_listener;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct CKComponentBoundsAnimation)boundsAnimationFromPreviousScopeRoot:(id)arg1;
- (id)boundsAnimationComponents;
- (void)registerBoundsAnimationComponent:(id)arg1;
- (void)announceEventToControllers:(unsigned int)arg1;
- (void)registerAnnounceableEventsForController:(id)arg1;
- (id)initWithListener:(id)arg1 globalIdentifier:(int)arg2;
- (id)newRoot;

@end

