//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBIntentTarget.h"

@class NSArray;

@interface FBActorSequenceIntentTarget : FBIntentTarget
{
    NSArray *_FBIDs;
}

+ (id)actorSequenceTargetWithFBIDs:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *FBIDs; // @synthesize FBIDs=_FBIDs;
- (void).cxx_destruct;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)fallbackURLs;

@end

