//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "CKComponentController.h"

#import "MKMapViewDelegate-Protocol.h"

@class NSString;
@protocol FBServiceTransactionMutating;

@interface FBAdInterfacesMapPickerComponentController : CKComponentController <MKMapViewDelegate>
{
    BOOL _didHandleMapRegionChange;
    id <FBServiceTransactionMutating> _geocodingTransactionHandle;
    id <FBServiceTransactionMutating> _populationEstimationTransactionHandle;
    id <FBServiceTransactionMutating> _radiusRecommendationTransactionHandle;
}

+ (SEL)customAddressCommittedAction;
+ (SEL)locationChangedAction;
- (void).cxx_destruct;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2;
- (void)gaugeCustomAddressCommitted:(id)arg1 address:(id)arg2;
- (void)gaugeLocationChanged:(id)arg1 selectedLocation:(id)arg2;
- (void)simulateMapRegionChangeIfNecessary:(id)arg1;
- (void)estimateAreaPopulation:(id)arg1 account:(id)arg2;
- (void)didReceiveGeoCodingWithResponse:(id)arg1;
- (void)geoCodeAddress:(id)arg1;
- (void)getRecommendedRadius:(id)arg1;
- (void)geoLocationChanged:(id)arg1;
- (void)didUpdateComponent;
- (void)componentDidAcquireView;
- (void)willUnmount;
- (void)didRemount;
- (void)didMount;
- (void)willRemount;
- (id)nextResponder;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

