//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@class FBAdInterfacesTokenFetcher, NSArray, NSError;

@protocol FBAdInterfacesTokenFetcherDelegate
- (void)tokenFetcher:(FBAdInterfacesTokenFetcher *)arg1 didFinishWithError:(NSError *)arg2;
- (void)tokenFetcher:(FBAdInterfacesTokenFetcher *)arg1 didFetchResults:(NSArray *)arg2;
@end

