//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@interface FBAdInterfacesBudgetPickerComponent : CKCompositeComponent
{
    SEL _selectionChangeAction;
}

+ (id)newWithBudgetRecommendations:(id)arg1 customBudget:(id)arg2 minDailyBudget:(id)arg3 minTotalBudget:(id)arg4 maxDailyBudget:(id)arg5 maxTotalBudget:(id)arg6 selectedBudget:(id)arg7 baseBudgetValue:(unsigned long long)arg8 isDaily:(BOOL)arg9 invalidEstimates:(BOOL)arg10 showCustomOptionOnTop:(BOOL)arg11 selectionChangeAction:(SEL)arg12;
- (void)customBudgetChanged:(id)arg1 withBudget:(id)arg2;
- (void)optionSelected:(id)arg1 withBudget:(id)arg2;

@end

