//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView;
@protocol FBAnimatedGIFDownloadIndicatorViewDelegate;

@interface FBAnimatedGIFDownloadIndicatorView : UIView
{
    BOOL _wasRotatingBeforeApplicationBackgrounded;
    BOOL _visible;
    UIImageView *_circleView;
    UIImageView *_dashesView;
    UIImageView *_gifTextView;
    BOOL _disappearAfterAnimation;
    id <FBAnimatedGIFDownloadIndicatorViewDelegate> _delegate;
}

@property(nonatomic) BOOL disappearAfterAnimation; // @synthesize disappearAfterAnimation=_disappearAfterAnimation;
@property(nonatomic) __weak id <FBAnimatedGIFDownloadIndicatorViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_shrinkCircle;
- (void)_shrinkGifText;
- (void)_shrinkDashes;
- (void)_popOut;
- (BOOL)_isRotatingDashes;
- (void)_stopDashes;
- (void)_rotateDashes;
- (void)animationDidStop:(id)arg1 finished:(BOOL)arg2;
- (void)reset;
- (void)stop;
- (void)spin;
- (void)animateDownloadCompletionIfVisible;
- (void)applicationForegroundedWithNotification:(id)arg1;
- (void)applicationBackgroundedWithNotification:(id)arg1;
- (void)dealloc;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

