//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBAppModule-Protocol.h"
#import "FBComposerFlowDelegate-Protocol.h"
#import "FBNuxProvider-Protocol.h"

@class FBExceptionHandler, FBProviderMap, FBUserSession, FBZeroOptinInterstitialPresenter, NSString;

@interface FBApplicationModule : NSObject <FBComposerFlowDelegate, FBAppModule, FBNuxProvider>
{
    FBUserSession *_session;
    FBZeroOptinInterstitialPresenter *_zeroOptinInterstitialPresenter;
    FBProviderMap *_providerMap;
}

+ (id)instanceForSession:(id)arg1 providerMap:(id)arg2;
+ (void)initialize;
- (void).cxx_destruct;
- (void)_navigateBackToAppSectionAfterPosting;
- (void)composerCompletedWithResult:(id)arg1;
- (BOOL)_openAppSection:(id)arg1;
- (id)processViewControllers:(id)arg1 forMenuItem:(id)arg2;
- (id)nuxPresenters;
- (id)staticBookmarks;
- (BOOL)handleOpenURL:(id)arg1 sourceApplication:(id)arg2 annotation:(id)arg3 appLinksInfo:(id)arg4 withNavigationCoordinator:(id)arg5;
- (id)supportedURLSchemes;
- (id)supportedKeys;
- (id)_groupsViewController:(id)arg1;
- (id)notificationViewController:(id)arg1;
- (id)viewControllerForMenuItem:(id)arg1;
- (BOOL)handleMenuItem:(id)arg1 navigationCoordinator:(id)arg2;
- (id)URLSegues;
- (id)defaultMenuItem;
- (id)ID;
- (id)init;
- (id)initWithSession:(id)arg1 providerMap:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) FBExceptionHandler *exceptionHandler;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

