//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCopying-Protocol.h"

@class FBMemPlatformApplication, NSOrderedSet;

@interface FBAppInviteCellModel : FBValueObject <NSCopying>
{
    BOOL _isApplicationInstalled;
    BOOL _showChevronNux;
    NSOrderedSet *_requests;
    unsigned int _visibleIndex;
    FBMemPlatformApplication *_application;
}

@property(readonly, nonatomic) BOOL showChevronNux; // @synthesize showChevronNux=_showChevronNux;
@property(readonly, nonatomic) BOOL isApplicationInstalled; // @synthesize isApplicationInstalled=_isApplicationInstalled;
@property(readonly, copy, nonatomic) FBMemPlatformApplication *application; // @synthesize application=_application;
@property(readonly, nonatomic) unsigned int visibleIndex; // @synthesize visibleIndex=_visibleIndex;
@property(readonly, copy, nonatomic) NSOrderedSet *requests; // @synthesize requests=_requests;
- (void).cxx_destruct;
- (id)initWithRequests:(id)arg1 visibleIndex:(unsigned int)arg2 application:(id)arg3 isApplicationInstalled:(BOOL)arg4 showChevronNux:(BOOL)arg5;

@end

