//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBRichTextView, NSString;
@protocol FBAppDetailTOSViewDelegate;

@interface FBAppDetailTOSView : UIView
{
    struct _NSRange _tosRange;
    struct _NSRange _privacyRange;
    FBRichTextView *_tosAndPrivacyLabel;
    id <FBAppDetailTOSViewDelegate> _delegate;
    NSString *_appName;
    NSString *_tosURL;
    NSString *_privacyPolicyURL;
}

@property(copy, nonatomic) NSString *privacyPolicyURL; // @synthesize privacyPolicyURL=_privacyPolicyURL;
@property(copy, nonatomic) NSString *tosURL; // @synthesize tosURL=_tosURL;
@property(copy, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(nonatomic) __weak id <FBAppDetailTOSViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)_handleLinkTapAtLocation:(struct CGPoint)arg1 inView:(id)arg2;
- (void)_setLabelString;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)tosAttributedLabelAction:(id)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

