//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBFacebookRedirectionViewController.h"

@class FBUserSession, NSDate, NSString, NSURL;

@interface FBAppLinkBackToReferrerTopBarViewController : FBFacebookRedirectionViewController
{
    FBUserSession *_session;
    NSString *_action;
    NSDate *_startTime;
    NSURL *_fromURL;
    NSURL *_applinkReferrerURL;
    NSString *_appName;
    int _topBarPriority;
}

@property(nonatomic) int topBarPriority; // @synthesize topBarPriority=_topBarPriority;
@property(copy, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(copy, nonatomic) NSURL *applinkReferrerURL; // @synthesize applinkReferrerURL=_applinkReferrerURL;
- (void).cxx_destruct;
- (void)_dismissOnEnterBackground;
- (void)_onModuleShown:(id)arg1;
- (void)_stopObservingModuleMenuTabWillChangeEvent;
- (void)_startObservingModuleMenuTabWillChangeEvent;
- (void)_stopObservingAppEnterBackground;
- (void)_startObservingAppEnterBackground;
- (void)_logConversion;
- (void)_dismissTopBar;
- (void)redirectionDismissViewTapped;
- (void)redirectionViewTapped;
- (void)didMoveToParentViewController:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
- (id)initWithSession:(id)arg1 fromURL:(id)arg2;

@end

