//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

#import "FBTextLabeling-Protocol.h"

@class FBAttributedTextReusableView_DEPRECATED, FBRichTextView, NSAttributedString;

@interface FBAttributedTextTableViewCell_DEPRECATED : UITableViewCell <FBTextLabeling>
{
    FBAttributedTextReusableView_DEPRECATED *_reusableView;
    NSAttributedString *_text;
    FBRichTextView *_attributedLabel;
    int _verticalTextAlignment;
    struct CGRect _textLayoutFrame;
}

- (void).cxx_destruct;
- (struct UIEdgeInsets)textPadding;
@property(readonly, nonatomic) FBRichTextView *attributedLabel; // @synthesize attributedLabel=_attributedLabel;
@property(copy, nonatomic) NSAttributedString *text; // @synthesize text=_text;
@property(nonatomic) int verticalTextAlignment; // @synthesize verticalTextAlignment=_verticalTextAlignment;
- (void)prepareForReuse;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
@property(readonly, nonatomic) struct CGRect textLayoutFrame; // @synthesize textLayoutFrame=_textLayoutFrame;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

