//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSArray, NSPredicate, NSString;

@interface FBAvatarPickerConfiguration : FBValueObject <NSCopying, NSCoding>
{
    BOOL _canTagSelf;
    BOOL _shouldShowSearchField;
    int _style;
    NSString *_searchBarPlaceHolder;
    NSArray *_taggableCollections;
    NSArray *_initialSelection;
    NSArray *_forcedSelection;
    NSArray *_disabledAvatars;
    NSArray *_sortDescriptors;
    NSPredicate *_predicate;
    unsigned int _flags;
}

@property(readonly, nonatomic) unsigned int flags; // @synthesize flags=_flags;
@property(readonly, copy, nonatomic) NSPredicate *predicate; // @synthesize predicate=_predicate;
@property(readonly, copy, nonatomic) NSArray *sortDescriptors; // @synthesize sortDescriptors=_sortDescriptors;
@property(readonly, nonatomic) BOOL shouldShowSearchField; // @synthesize shouldShowSearchField=_shouldShowSearchField;
@property(readonly, nonatomic) BOOL canTagSelf; // @synthesize canTagSelf=_canTagSelf;
@property(readonly, copy, nonatomic) NSArray *disabledAvatars; // @synthesize disabledAvatars=_disabledAvatars;
@property(readonly, copy, nonatomic) NSArray *forcedSelection; // @synthesize forcedSelection=_forcedSelection;
@property(readonly, copy, nonatomic) NSArray *initialSelection; // @synthesize initialSelection=_initialSelection;
@property(readonly, copy, nonatomic) NSArray *taggableCollections; // @synthesize taggableCollections=_taggableCollections;
@property(readonly, copy, nonatomic) NSString *searchBarPlaceHolder; // @synthesize searchBarPlaceHolder=_searchBarPlaceHolder;
@property(readonly, nonatomic) int style; // @synthesize style=_style;
- (void).cxx_destruct;
- (id)initWithStyle:(int)arg1 searchBarPlaceHolder:(id)arg2 taggableCollections:(id)arg3 initialSelection:(id)arg4 forcedSelection:(id)arg5 disabledAvatars:(id)arg6 canTagSelf:(BOOL)arg7 shouldShowSearchField:(BOOL)arg8 sortDescriptors:(id)arg9 predicate:(id)arg10 flags:(unsigned int)arg11;

@end

