//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSDate, NSDictionary, NSTimer;
@protocol FBBackgroundFetchRequestDelegate;

@interface FBBackgroundFetchRequest : NSObject
{
    CDUnknownBlockType _completionHandler;
    NSArray *_registeredObservers;
    double _timeout;
    BOOL _finished;
    unsigned int _finalResult;
    unsigned int _numPendingCallbacks;
    NSDate *_startDate;
    NSDate *_endDate;
    NSTimer *_timeoutTimer;
    id <FBBackgroundFetchRequestDelegate> _delegate;
    NSDictionary *_notification;
}

@property(copy, nonatomic) NSDictionary *notification; // @synthesize notification=_notification;
@property __weak id <FBBackgroundFetchRequestDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (unsigned int)result;
- (unsigned int)observerCount;
- (double)duration;
- (void)_finish;
- (void)_timeOut;
- (void)observer:(id)arg1 completedWithResult:(unsigned int)arg2;
- (void)start;
- (id)initWithRegisteredObservers:(id)arg1 notification:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)init;

@end

