//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class POPSpringAnimation;

@interface FBBouncyButton : UIButton
{
    struct CGSize _sizeWhenNotAnimated;
    double _downTime;
    BOOL _selected;
    BOOL _bounces;
    BOOL _bounceOnlyShrinks;
    POPSpringAnimation *_bounceAnimation;
    float _bounciness;
}

@property(readonly, nonatomic) struct CGSize sizeWhenNotAnimated; // @synthesize sizeWhenNotAnimated=_sizeWhenNotAnimated;
@property(nonatomic) float bounciness; // @synthesize bounciness=_bounciness;
@property(nonatomic) BOOL bounceOnlyShrinks; // @synthesize bounceOnlyShrinks=_bounceOnlyShrinks;
- (void).cxx_destruct;
- (void)touchCancelled:(id)arg1;
- (void)touchUp:(id)arg1;
- (void)touchDown:(id)arg1;
- (void)pop_animationDidApply:(id)arg1;
@property(nonatomic, getter=isSelected) BOOL selected;
- (void)setImage:(id)arg1 forState:(unsigned int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

