//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSMutableDictionary, NSString, NSURL;

@interface FBBreakpadCrashReport : NSObject
{
    NSMutableDictionary *_parameters;
    NSURL *_exceptionURL;
    NSString *_minidumpPath;
    NSString *_configPath;
    NSString *_extraPath;
    NSDate *_crashTime;
}

@property(readonly, nonatomic) NSDate *crashTime; // @synthesize crashTime=_crashTime;
@property(readonly, copy, nonatomic) NSString *extraPath; // @synthesize extraPath=_extraPath;
@property(readonly, copy, nonatomic) NSString *configPath; // @synthesize configPath=_configPath;
@property(readonly, copy, nonatomic) NSString *minidumpPath; // @synthesize minidumpPath=_minidumpPath;
@property(readonly, nonatomic) NSURL *exceptionURL; // @synthesize exceptionURL=_exceptionURL;
- (void).cxx_destruct;
- (BOOL)isReactNativeJsCrash;
- (id)readDataFromFile:(int)arg1 withLength:(long)arg2;
- (id)readString:(int)arg1;
- (id)readExtraData:(const char *)arg1;
- (BOOL)loadConfigFile:(id)arg1 errorHandler:(CDUnknownBlockType)arg2;
- (void)cleanupFiles;
- (id)sendCrashReportToURL:(id)arg1 error:(id *)arg2;
- (id)sendCrashReport:(id *)arg1;
- (void)addParameter:(id)arg1 forKey:(id)arg2;
- (id)parameters;
- (id)minidumpData;
- (id)initWithConfigPath:(id)arg1 errorHandler:(CDUnknownBlockType)arg2;

@end

