//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBBubbleController;

@protocol FBBubbleControllerDelegate <NSObject>

@optional
- (void)bubbleDidEndEditing:(FBBubbleController *)arg1;
- (void)bubbleDidBeginEditing:(FBBubbleController *)arg1;
- (void)bubbleSizeChanged:(FBBubbleController *)arg1 byOffset:(float)arg2;
- (void)bubbleKeyboardChanged:(FBBubbleController *)arg1;
- (void)bubbleKeyboardDismissed:(FBBubbleController *)arg1;
- (void)bubbleKeyboardPresented:(FBBubbleController *)arg1;
- (void)bubbleDidDisappear:(FBBubbleController *)arg1;
- (void)bubbleWillDisappear:(FBBubbleController *)arg1;
- (void)bubbleDidAppear:(FBBubbleController *)arg1;
- (void)bubbleWillAppear:(FBBubbleController *)arg1;
@end

