//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSDictionary, NSSet, NSString;

@interface FBBugReportInfo : NSObject <NSCoding>
{
    NSDictionary *_attachments;
    NSSet *_contextsToUploadWithInitialCreationRequest;
    NSString *_creationTime;
    NSString *_descriptionEnteredByPerson;
    unsigned int _initiationSource;
    NSString *_localBugID;
    NSDictionary *_parameters;
    NSString *_selectedCategory;
}

+ (id)loadFirstUnsentBugReport;
+ (id)loadSavedBugReport:(id)arg1;
+ (id)persistedBugReports:(int)arg1;
+ (void)initializeDiskSynchronizationObjectIfNeeded;
+ (id)persistedBugsDirectory:(int)arg1;
@property(readonly, copy, nonatomic) NSString *selectedCategory; // @synthesize selectedCategory=_selectedCategory;
@property(readonly, copy, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(readonly, copy, nonatomic) NSString *localBugID; // @synthesize localBugID=_localBugID;
@property(readonly, nonatomic) unsigned int initiationSource; // @synthesize initiationSource=_initiationSource;
@property(readonly, copy, nonatomic) NSString *descriptionEnteredByPerson; // @synthesize descriptionEnteredByPerson=_descriptionEnteredByPerson;
@property(readonly, copy, nonatomic) NSString *creationTime; // @synthesize creationTime=_creationTime;
@property(readonly, copy, nonatomic) NSSet *contextsToUploadWithInitialCreationRequest; // @synthesize contextsToUploadWithInitialCreationRequest=_contextsToUploadWithInitialCreationRequest;
@property(readonly, copy, nonatomic) NSDictionary *attachments; // @synthesize attachments=_attachments;
- (void).cxx_destruct;
- (void)moveToSentDirectory;
- (void)removeOldBugs;
- (void)saveToDisk;
- (id)fetchDebugLogs;
- (id)generateContextsToUploadWithInitialCreationRequest;
- (void)_appendAutoLayoutTraceForView:(id)arg1 intoBuilder:(id)arg2 currentDepth:(unsigned int)arg3;
- (id)_autoLayoutTrace:(id)arg1;
- (id)getNewsfeedLogs:(id)arg1;
- (id)generateAttachmentsWithDescription:(id)arg1 additionalContexts:(id)arg2;
- (double)elapsedTimeSinceFileLastModified:(id)arg1;
- (id)generateParameters:(id)arg1;
- (id)_logInfo:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithHTTPCookies:(id)arg1 descriptionEnteredByPerson:(id)arg2 initiationSource:(unsigned int)arg3 selectedCategory:(id)arg4 additionalContexts:(id)arg5;

@end

