//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBGraphQLConnectionStoreStateModifying-Protocol.h"

@class NSDictionary, NSString;

@interface FBCKFeedbackConnectionStoreCommentUpdate : NSObject <FBGraphQLConnectionStoreStateModifying>
{
    NSDictionary *_updates;
}

@property(readonly, copy, nonatomic) NSDictionary *updates; // @synthesize updates=_updates;
- (void).cxx_destruct;
- (id)transitionsFromState:(id)arg1;
- (id)initWithUpdatesMap:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

