//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBCommentReplyViewControllerProvider : NSObject
{
}

+ (id)darkCellStyleWithSession:(id)arg1;
+ (id)cellStyleWithSession:(id)arg1;
+ (id)commentReplyManagerConfigurationWithReplyConfiguration:(id)arg1 cellStyle:(id)arg2 darkCellStyle:(id)arg3;
+ (id)commentStreamConfigurationWithReplyConfiguration:(id)arg1 cellStyle:(id)arg2;
+ (id)commentReplyViewControllerWithConfiguration:(id)arg1 userSession:(id)arg2;

@end

