//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBWorkingRangeItemViewState-Protocol.h"

@class NSString;

@interface FBComponentWorkingRangeItemState : NSObject <FBWorkingRangeItemViewState>
{
    struct CKComponentLayout _layout;
    id _item;
    struct CGRect _frame;
}

@property(readonly, nonatomic) struct CGRect frame; // @synthesize frame=_frame;
@property(readonly, nonatomic) id item; // @synthesize item=_item;
- (id).cxx_construct;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (BOOL)isEqual:(id)arg1;
@property(readonly) unsigned int hash;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (const struct CKComponentLayout *)layout;
- (id)initWithItem:(id)arg1 frame:(struct CGRect)arg2 layout:(const struct CKComponentLayout *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

