//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBComposerMediaThumbListController, FBComposerToolTipCoordinator, FBCropLogger, FBMemPhotoTagsEdge, FBStickersInPhotosLogger, FBTextOnPhotosLogger, NSArray, NSString, UIImage, UIScrollView, UIView;
@protocol FBMediaAttachmentProtocol;

@protocol FBComposerMediaListViewDelegate <NSObject>
- (void)didEndShowingInstructionalNuxForComposerMediaThumbListController:(FBComposerMediaThumbListController *)arg1;
- (void)didBeginShowingInstructionalNuxForComposerMediaThumbListController:(FBComposerMediaThumbListController *)arg1;
- (UIScrollView *)scrollViewForComposerStatusCellsForMediaThumbListController:(FBComposerMediaThumbListController *)arg1;
- (void)composerMediaThumbListController:(FBComposerMediaThumbListController *)arg1 updateAssetEditsAndThumbnail:(UIImage *)arg2 forAssetID:(NSString *)arg3;
- (void)composerMediaThumbListControllerDidUpdateAttachments:(FBComposerMediaThumbListController *)arg1;
- (void)composerMediaThumbListControllerDidDismissReorderingView:(FBComposerMediaThumbListController *)arg1;
- (void)composerMediaThumbListControllerWillPresentReorderingView:(FBComposerMediaThumbListController *)arg1;
- (FBComposerToolTipCoordinator *)composerToolTipCoordinatorForMediaThumbListController:(FBComposerMediaThumbListController *)arg1;
- (void)composerMediaThumbListController:(FBComposerMediaThumbListController *)arg1 needsRectVisible:(struct CGRect)arg2 inView:(UIView *)arg3 forceToBottomOfVisibleRegion:(BOOL)arg4 animated:(BOOL)arg5 completion:(void (^)(void))arg6;
- (void)composerMediaThumbListControllerDidMoveAttachmentFromIndex:(unsigned int)arg1 toIndex:(unsigned int)arg2;
- (void)composerMediaThumbListController:(FBComposerMediaThumbListController *)arg1 didTapTextOnPhotosButtonForMediaAttachment:(id <FBMediaAttachmentProtocol>)arg2 logger:(FBTextOnPhotosLogger *)arg3;
- (void)composerMediaThumbListController:(FBComposerMediaThumbListController *)arg1 didTapStickersForMediaAttachment:(id <FBMediaAttachmentProtocol>)arg2 logger:(FBStickersInPhotosLogger *)arg3;
- (void)composerMediaThumbListController:(FBComposerMediaThumbListController *)arg1 didTapCropForMediaAttachment:(id <FBMediaAttachmentProtocol>)arg2 logger:(FBCropLogger *)arg3;
- (void)composerMediaThumbListController:(FBComposerMediaThumbListController *)arg1 didTapRemoveForMediaAttachment:(id <FBMediaAttachmentProtocol>)arg2;
- (void)composerMediaThumbListController:(FBComposerMediaThumbListController *)arg1 didRemoveTagsEdge:(FBMemPhotoTagsEdge *)arg2 forMediaAttachment:(id <FBMediaAttachmentProtocol>)arg3 allTags:(NSArray *)arg4 source:(NSString *)arg5;
- (void)composerMediaThumbListController:(FBComposerMediaThumbListController *)arg1 didTapMediaAttachment:(id <FBMediaAttachmentProtocol>)arg2 tappedButton:(BOOL)arg3 faceBoxID:(NSString *)arg4;
@end

