//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBCompleteProfileMegaphoneConfigurator.h"

@class CAShapeLayer;

@interface FBCompleteProfileMegaphoneTimelineConfigurator : FBCompleteProfileMegaphoneConfigurator
{
    CAShapeLayer *_borderLayer;
}

+ (BOOL)shouldShowTimelinephoneWithSession:(id)arg1;
- (void).cxx_destruct;
- (id)surface;
- (id)newAccessoryQuestionViewWithFrame:(struct CGRect)arg1;
- (id)newBorderLayer;
- (id)newShadowViewWithFrame:(struct CGRect)arg1;
- (id)newFooterWithFrame:(struct CGRect)arg1;
- (id)newTypeaheadCellWithReusedIdentifier:(id)arg1;
- (id)newInferenceCellWithReusedIdentifier:(id)arg1;
- (float)accessoryQuestionViewHeight;
- (struct CGSize)closeButtonInset;
- (float)contentInset;
- (BOOL)showQuestionCell;
- (float)cornerRadius;
- (float)footerHeight;
- (float)confirmationCellHeight;
- (float)inferenceCellExpandedHeight;
- (float)typeaheadCellHeight;
- (int)initialState;

@end

