//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "CKStatefulViewComponentController.h"

#import "FBCommentComposerViewDelegate-Protocol.h"
#import "FBGrowingComposerViewDelegate-Protocol.h"
#import "FBMultiMediaAttachmentsViewDelegate-Protocol.h"

@class FBCommentComposerHashtagController, FBCommentComposerPhotoController, FBCommentComposerStickerController, NSString;

@interface FBCommentComposerViewComponentController : CKStatefulViewComponentController <FBCommentComposerViewDelegate, FBGrowingComposerViewDelegate, FBMultiMediaAttachmentsViewDelegate>
{
    FBCommentComposerHashtagController *_hashtagController;
    FBCommentComposerPhotoController *_photoController;
    FBCommentComposerStickerController *_stickerController;
}

+ (void)configureStatefulView:(id)arg1 forComponent:(id)arg2;
+ (id)contextForNewStatefulView:(id)arg1;
+ (id)newStatefulView:(id)arg1;
- (void).cxx_destruct;
- (id)stickerController;
- (void)multiPhotoAttachment:(id)arg1 removePhotoTapAtIndex:(unsigned int)arg2;
- (void)commentComposerView:(id)arg1 dismissFullScreenStickerTrayWithCompletion:(CDUnknownBlockType)arg2;
- (void)commentComposerView:(id)arg1 presentFullScreenWithStickerTray:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)commentComposerView:(id)arg1 didSelectStickerStoreWithFBID:(unsigned long long)arg2 fromView:(id)arg3;
- (void)commentComposerViewDidTapStickerComposerButton:(id)arg1;
- (void)commentComposerViewDidTapAttachPhotoButton:(id)arg1;
- (void)commentComposerView:(id)arg1 didSelectStickerWithFBID:(id)arg2;
- (void)commentComposerViewDidTapSendButton:(id)arg1;
- (void)commentComposerViewNeedsResize:(id)arg1;
- (void)growingComposerViewDidBeginEditing:(id)arg1;
- (void)_cleanUp;
- (BOOL)canRelinquishStatefulView;
- (void)willRelinquishStatefulView:(id)arg1;
- (void)didAcquireStatefulView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

