//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface FBCodeGeneratorObject : FBValueObject <NSCopying>
{
    NSString *_userFBID;
    NSString *_key;
    double _timeOffset;
}

@property(readonly, nonatomic) double timeOffset; // @synthesize timeOffset=_timeOffset;
@property(readonly, copy, nonatomic) NSString *key; // @synthesize key=_key;
@property(readonly, copy, nonatomic) NSString *userFBID; // @synthesize userFBID=_userFBID;
- (void).cxx_destruct;
- (id)initWithUserFBID:(id)arg1 key:(id)arg2 timeOffset:(double)arg3;
- (double)nowTime;

@end

