//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCopying-Protocol.h"

@class FBMemTextWithEntities, NSArray, NSString;

@interface FBCollectionProfileFieldSection : FBValueObject <NSCopying>
{
    BOOL _hasContent;
    NSString *_editURI;
    NSArray *_styles;
    FBMemTextWithEntities *_textContent;
    FBMemTextWithEntities *_title;
    FBMemTextWithEntities *_upsellText;
    NSArray *_associatedPages;
}

@property(readonly, copy, nonatomic) NSArray *associatedPages; // @synthesize associatedPages=_associatedPages;
@property(readonly, copy, nonatomic) FBMemTextWithEntities *upsellText; // @synthesize upsellText=_upsellText;
@property(readonly, copy, nonatomic) FBMemTextWithEntities *title; // @synthesize title=_title;
@property(readonly, copy, nonatomic) FBMemTextWithEntities *textContent; // @synthesize textContent=_textContent;
@property(readonly, copy, nonatomic) NSArray *styles; // @synthesize styles=_styles;
@property(readonly, nonatomic) BOOL hasContent; // @synthesize hasContent=_hasContent;
@property(readonly, copy, nonatomic) NSString *editURI; // @synthesize editURI=_editURI;
- (void).cxx_destruct;
- (id)initWithEditURI:(id)arg1 hasContent:(BOOL)arg2 styles:(id)arg3 textContent:(id)arg4 title:(id)arg5 upsellText:(id)arg6 associatedPages:(id)arg7;

@end

