//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBComposerPublisherData, NSString;

@protocol FBComposerPublisher <NSObject>
- (void)stoppingPublishingDueToUnexpectedReason;
- (void)retryPublishingPublisherData:(FBComposerPublisherData *)arg1 withSource:(unsigned int)arg2;
- (void)restorePausedPublication:(FBComposerPublisherData *)arg1;
- (void)publish:(FBComposerPublisherData *)arg1;
- (void)pausePublication:(FBComposerPublisherData *)arg1;
- (void)cancelPublishingPublication:(FBComposerPublisherData *)arg1 withReason:(NSString *)arg2;
@end

