//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UIView;

@interface FBCollectionAbstractCell : UITableViewCell
{
    UIImageView *_borderImageView;
    UIView *_borderImageContainerView;
    UIView *_bottomBorderView;
    UIView *_customContentView;
    struct UIEdgeInsets _customContentViewEdgeInsets;
}

@property(nonatomic) struct UIEdgeInsets customContentViewEdgeInsets; // @synthesize customContentViewEdgeInsets=_customContentViewEdgeInsets;
@property(retain, nonatomic) UIView *customContentView; // @synthesize customContentView=_customContentView;
- (void).cxx_destruct;
- (id)backgroundColorWhenHighlighted:(BOOL)arg1;
- (BOOL)renderingInCard;
- (BOOL)hasCustomBorder;
- (void)layoutSubviews;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithReuseIdentifier:(id)arg1;

@end

