//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBComposerSproutsTransitionAnimator-Protocol.h"

@class FBComposerSproutsSheetContainerView, UIView;

@interface FBComposerSproutsTransitionAnimatorForSproutSheet : NSObject <FBComposerSproutsTransitionAnimator>
{
    UIView *_opaqueView;
    FBComposerSproutsSheetContainerView *_sproutSheetView;
}

- (void).cxx_destruct;
- (void)performClosingAnimationFromView:(id)arg1 toView:(id)arg2 animationGroup:(id)arg3;
- (void)performOpeningAnimationFromView:(id)arg1 toView:(id)arg2 animationGroup:(id)arg3;
- (double)openingAnimationDuration;
- (id)initWithSproutSheetView:(id)arg1 opaqueView:(id)arg2;

@end

