//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface FBComposerAudienceEducationDataBuilder : NSObject
{
    NSString *_title;
    NSString *_introductionText;
    NSString *_callToActionText;
    NSString *_primaryActionText;
    NSString *_additionalActionText;
    NSString *_publicTooltip;
    NSString *_friendsTooltip;
    NSString *_onlyMeTooltip;
    NSString *_moreTooltip;
    NSString *_dismissTooltip;
    NSString *_suggestedTooltip;
    NSString *_learnMoreTitle;
    NSArray *_learnMoreParagraphs;
}

+ (id)composerAudienceEducationDataFromExistingComposerAudienceEducationData:(id)arg1;
+ (id)composerAudienceEducationData;
- (void).cxx_destruct;
- (id)withLearnMoreParagraphs:(id)arg1;
- (id)withLearnMoreTitle:(id)arg1;
- (id)withSuggestedTooltip:(id)arg1;
- (id)withDismissTooltip:(id)arg1;
- (id)withMoreTooltip:(id)arg1;
- (id)withOnlyMeTooltip:(id)arg1;
- (id)withFriendsTooltip:(id)arg1;
- (id)withPublicTooltip:(id)arg1;
- (id)withAdditionalActionText:(id)arg1;
- (id)withPrimaryActionText:(id)arg1;
- (id)withCallToActionText:(id)arg1;
- (id)withIntroductionText:(id)arg1;
- (id)withTitle:(id)arg1;
- (id)build;

@end

