//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBCollectionAbstractViewController.h"

@class FBMemTimelineAppCollection, FBMemTimelineAppSection, NSOrderedSet;

@interface FBCollectionPerCollectionViewController : FBCollectionAbstractViewController
{
    FBMemTimelineAppSection *_section;
    FBMemTimelineAppCollection *_collection;
    NSOrderedSet *_items;
}

- (void).cxx_destruct;
- (id)queryForProfileSections;
- (id)collectionItemsForCollection:(id)arg1;
- (void)updateWithConnectionNodes:(id)arg1;
- (void)handleBootstrapResponse:(id)arg1 error:(id)arg2;
- (id)connectionKeypath;
- (id)newQueryWithPageInfo:(id)arg1;
- (id)viewEventLogData;
- (id)analyticsModule;
- (float)scrollBufferFactor;
- (id)collectionSectionForTableSection:(int)arg1;
- (BOOL)canExpandSections;
- (id)headerSection;
- (id)destinationURLForTableSection:(int)arg1;
- (id)logoURLForTableSection:(int)arg1;
- (id)headerSubtitleForTableSection:(int)arg1;
- (id)headerTitleForTableSection:(int)arg1;
- (id)collectionForTableSection:(int)arg1;
- (unsigned int)maxItemsToShowForCollectionStyle:(id)arg1;
- (unsigned int)numberOfTableSections;
- (BOOL)supportsPaging;
- (BOOL)shouldShowEmptyState;
- (void)viewWillAppear:(BOOL)arg1;
- (unsigned int)_numberOfCollectionItemsPerPage;
- (id)initWithSession:(id)arg1 ownerFBID:(id)arg2 collection:(id)arg3 inCollectionSection:(id)arg4;

@end

