//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class FBAudioActivityReloadButton, FBMemSuggestedTaggableActivitiesEdge, FBNetworkImageView, FBUserSession;

@interface FBComposerSuggestedActivityTableViewCell : UITableViewCell
{
    FBNetworkImageView *_profilePictureView;
    FBUserSession *_session;
    BOOL _hasHighlightState;
    FBMemSuggestedTaggableActivitiesEdge *_suggestedActivity;
    float _cellInset;
    FBAudioActivityReloadButton *_reloadButton;
}

@property(retain, nonatomic) FBAudioActivityReloadButton *reloadButton; // @synthesize reloadButton=_reloadButton;
@property(nonatomic) BOOL hasHighlightState; // @synthesize hasHighlightState=_hasHighlightState;
@property(nonatomic) float cellInset; // @synthesize cellInset=_cellInset;
@property(retain, nonatomic) FBMemSuggestedTaggableActivitiesEdge *suggestedActivity; // @synthesize suggestedActivity=_suggestedActivity;
- (void).cxx_destruct;
- (void)updateDisplayForHighlightedAndSelected;
- (void)updateCell;
- (void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
- (id)initWithReuseIdentifier:(id)arg1 session:(id)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

