//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSAttributedString;

@interface FBCommentTranslationComponentState : NSObject
{
    unsigned int _translationLoadingState;
    NSAttributedString *_translatedMessage;
}

@property(readonly, copy, nonatomic) NSAttributedString *translatedMessage; // @synthesize translatedMessage=_translatedMessage;
@property(readonly, nonatomic) unsigned int translationLoadingState; // @synthesize translationLoadingState=_translationLoadingState;
- (void).cxx_destruct;
- (id)initWithTranslationLoadingState:(unsigned int)arg1 translatedMessage:(id)arg2;

@end

