//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBCollectionAbstractCell.h"

@class FBMemInfoRequestField, FBMemTimelineAppCollection, FBUserSession, NSString, UIButton, UILabel;
@protocol FBCollectionInfoRequestCellDelegate;

@interface FBCollectionInfoRequestCell : FBCollectionAbstractCell
{
    UIButton *_askButton;
    UIButton *_cancelButton;
    UILabel *_titleLabel;
    FBUserSession *_session;
    FBMemTimelineAppCollection *_collection;
    id _observation;
    FBMemInfoRequestField *_infoRequestField;
    id <FBCollectionInfoRequestCellDelegate> _infoRequestCellDelegate;
    NSString *_collectionStyle;
}

+ (float)desiredHeight;
@property(copy, nonatomic) NSString *collectionStyle; // @synthesize collectionStyle=_collectionStyle;
@property(nonatomic) __weak id <FBCollectionInfoRequestCellDelegate> infoRequestCellDelegate; // @synthesize infoRequestCellDelegate=_infoRequestCellDelegate;
@property(readonly, nonatomic) FBMemInfoRequestField *infoRequestField; // @synthesize infoRequestField=_infoRequestField;
- (void).cxx_destruct;
- (id)_cancelButtonTextColor;
- (id)_cancelButtonFont;
- (int)_titleLineBreakMode;
- (id)_titleBackgroundColor;
- (id)_titleTextColor;
- (id)_titleFont;
- (id)_titleLabel;
- (id)_cancelButton;
- (id)_askButton;
- (void)_updateUI;
- (void)_handleTapCancelButton:(id)arg1;
- (void)_handleTapAskButton:(id)arg1;
- (void)_requestFieldDidUpdate:(id)arg1;
- (void)setInfoRequestField:(id)arg1 inCollection:(id)arg2;
- (id)backgroundColorWhenHighlighted:(BOOL)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1 session:(id)arg2;
- (id)initWithReuseIdentifier:(id)arg1;

@end

