//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBComposerCompositionStateChangedListener-Protocol.h"
#import "FBComposerPhotosAvatarPickerControllerDelegate-Protocol.h"
#import "FBComposerPickerController-Protocol.h"

@class FBComposerCompositionState, FBComposerPhotosAvatarPickerController, FBMutableTaggableCollection, FBUserSession, NSString;
@protocol FBAvatarPickerControllerListener, FBComposerAvatarPickerControllerDelegate;

@interface FBComposerAvatarPickerController : NSObject <FBComposerPhotosAvatarPickerControllerDelegate, FBComposerPickerController, FBComposerCompositionStateChangedListener>
{
    FBUserSession *_session;
    id <FBAvatarPickerControllerListener> _listener;
    FBMutableTaggableCollection *_taggableCollection;
    BOOL _ttiLogged;
    unsigned int _numberOfAutoTaggedUsers;
    FBComposerCompositionState *_compositionState;
    FBComposerPhotosAvatarPickerController *_simpleAvatarPicker;
    BOOL _shouldSearchFieldSetFocus;
    BOOL _isInPopover;
    id <FBComposerAvatarPickerControllerDelegate> _delegate;
    FBComposerPhotosAvatarPickerController *_avatarPicker;
}

@property(retain, nonatomic) FBComposerPhotosAvatarPickerController *avatarPicker; // @synthesize avatarPicker=_avatarPicker;
@property(nonatomic) __weak id <FBComposerAvatarPickerControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL isInPopover; // @synthesize isInPopover=_isInPopover;
- (void).cxx_destruct;
- (void)avatarPickerDidCancel:(id)arg1;
- (void)avatarPicker:(id)arg1 didFinishWithSelection:(id)arg2 photoTags:(id)arg3 allowContributors:(BOOL)arg4;
- (void)avatarPicker:(id)arg1 didFinishWithSelection:(id)arg2;
- (void)avatarPicker:(id)arg1 willShowCell:(id)arg2 atIndexPath:(id)arg3;
- (id)presentableSimplifiedViewControllerWithOnlySearchBarWithTitle:(id)arg1;
- (id)presentableViewController;
- (void)dismissPopoverController;
- (struct CGSize)popoverContentSizeForOrientation:(int)arg1;
- (unsigned int)popoverStyle;
- (void)willPresentViewController;
- (void)composerCompositionStateChangedFromPreviousCompositionState:(id)arg1 toCurrentCompositionState:(id)arg2;
- (void)dealloc;
- (id)initWithSession:(id)arg1 listener:(id)arg2 taggableCollection:(id)arg3 shouldSearchFieldSetFocus:(BOOL)arg4;
- (id)initWithSession:(id)arg1 listener:(id)arg2 taggableCollection:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

