//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBCompositor : NSObject
{
}

+ (id)imageNamed:(id)arg1;
+ (id)snapshotLayer:(id)arg1 rotatedBy:(float)arg2;
+ (id)viewsNamed:(id)arg1;
+ (id)viewsWithDescription:(id)arg1;
+ (id)compositionWithName:(id)arg1;
+ (id)viewsWithComposition:(id)arg1 composition:(id)arg2;
+ (id)wrapperInProps:(id)arg1;
+ (id)shapeInProps:(id)arg1;
+ (id)propertyObjectsForProperties:(id)arg1;

@end

