//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "FBCommerceEventListener-Protocol.h"
#import "FBCommerceProductStoreFrontDataSourceDelegate-Protocol.h"
#import "FBComponentCellAppearanceEventListener-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class FBCommerceEventListenerAnnouncer, FBCommerceLogger, FBCommerceProductStoreFrontDataSource, FBUserSession, NSString, UIAlertView;

@interface FBCommerceProductStoreFrontViewController : UITableViewController <UIAlertViewDelegate, FBCommerceEventListener, FBCommerceProductStoreFrontDataSourceDelegate, FBComponentCellAppearanceEventListener>
{
    NSString *_pageID;
    NSString *_productID;
    int _currentIndex;
    NSString *_currentCollectionID;
    UIAlertView *_alertView;
    NSString *_refType;
    NSString *_refID;
    FBCommerceEventListenerAnnouncer *_announcer;
    FBCommerceProductStoreFrontDataSource *_dataSource;
    FBCommerceLogger *_logger;
    FBUserSession *_session;
}

- (void).cxx_destruct;
- (void)_logSection:(id)arg1;
- (void)commerceProductStoreFrontDataSource:(id)arg1 didFailUpdateWithError:(id)arg2;
- (void)storeFrontBannerProductDisplayed:(id)arg1 index:(int)arg2 collectionID:(id)arg3;
- (void)componentDidDisappearFromViewWithFrame:(struct CGRect)arg1 withModel:(id)arg2 atIndexPath:(id)arg3;
- (void)componentWillAppearInViewWithFrame:(struct CGRect)arg1 withModel:(id)arg2 atIndexPath:(id)arg3;
- (BOOL)fb_showNavBarSearchField;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (BOOL)fb_showAuxiliaryViewController;
- (void)viewDidDisappear:(BOOL)arg1;
- (void)viewDidAppear:(BOOL)arg1;
- (void)loadView;
- (unsigned int)supportedInterfaceOrientations;
- (void)dealloc;
- (id)init;
- (id)initWithSession:(id)arg1 pageID:(id)arg2 selectedProductID:(id)arg3 refID:(id)arg4 refType:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

