//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBActivitySuggestionManagerFactory-Protocol.h"
#import "FBAudienceEducationEligibilityControllerFactory-Protocol.h"
#import "FBAutoTaggingControllerFactory-Protocol.h"
#import "FBCollageToolLoggerFactory-Protocol.h"
#import "FBComposerActivityTagPickerControllerFactory-Protocol.h"
#import "FBComposerAlbumPickerControllerFactory-Protocol.h"
#import "FBComposerAudienceSelectionFlowControllerFactory-Protocol.h"
#import "FBComposerCompositionTextChangeHandlerFactory-Protocol.h"
#import "FBComposerDataUpdateManagerFactory-Protocol.h"
#import "FBComposerDatePickerControllerFactory-Protocol.h"
#import "FBComposerDestinationControllerFactory-Protocol.h"
#import "FBComposerLocationPickerControllerFactory-Protocol.h"
#import "FBComposerLoggerFactory-Protocol.h"
#import "FBComposerLoopsLoggerFactory-Protocol.h"
#import "FBComposerMediaPickerControllerFactory-Protocol.h"
#import "FBComposerPostCompositionViewControllerFactory-Protocol.h"
#import "FBComposerSharedLinkPickerControllerFactory-Protocol.h"
#import "FBComposerTaggableCollectionProviderFactory-Protocol.h"
#import "FBCompositionLinkShareControllerFactory-Protocol.h"
#import "FBMLETitleIconControllerFactory-Protocol.h"
#import "FBMediaDataSourceManagerFactory-Protocol.h"
#import "FBMediaTraitsObserverFactory-Protocol.h"
#import "FBMediaUploadItemManagerFactory-Protocol.h"
#import "FBPhotoTaggingAssetObserverFactory-Protocol.h"
#import "FBPlacePickerNearbyFetcherFactory-Protocol.h"

@class NSString;

@interface FBComposerScopeSingletonProvider : NSObject <FBActivitySuggestionManagerFactory, FBAudienceEducationEligibilityControllerFactory, FBAutoTaggingControllerFactory, FBComposerActivityTagPickerControllerFactory, FBComposerAlbumPickerControllerFactory, FBComposerDataUpdateManagerFactory, FBComposerLocationPickerControllerFactory, FBComposerLoggerFactory, FBComposerMediaPickerControllerFactory, FBComposerTaggableCollectionProviderFactory, FBCompositionLinkShareControllerFactory, FBMLETitleIconControllerFactory, FBMediaDataSourceManagerFactory, FBMediaTraitsObserverFactory, FBMediaUploadItemManagerFactory, FBPhotoTaggingAssetObserverFactory, FBPlacePickerNearbyFetcherFactory, FBCollageToolLoggerFactory, FBComposerPostCompositionViewControllerFactory, FBComposerAudienceSelectionFlowControllerFactory, FBComposerDatePickerControllerFactory, FBComposerDestinationControllerFactory, FBComposerLoopsLoggerFactory, FBComposerCompositionTextChangeHandlerFactory, FBComposerSharedLinkPickerControllerFactory>
{
    id _block;
    struct tuple<std::__1::mutex, signed char, id> _state;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)sharedLinkPickerController;
- (BOOL)isCreated;
- (id)textChangeHandler;
- (id)collageLogger;
- (id)loopsLogger;
- (id)mediaDataSourceManager;
- (id)mediaTraitsObserver;
- (id)taggableCollectionProvider;
- (id)postCompositionViewController;
- (id)placePickerNearbyFetcher;
- (id)photoTaggingAssetObserver;
- (id)mleTitleIconController;
- (id)mediaUploadItemManager;
- (id)mediaPickerController;
- (id)logger;
- (id)locationPickerController;
- (id)destinationController;
- (id)datePickerController;
- (id)linkShareController;
- (id)dataUpdateManager;
- (id)audienceSelectionFlowController;
- (id)autoTaggingController;
- (id)audienceEducationEligibilityController;
- (id)albumPickerController;
- (id)activityTagPickerController;
- (id)activitySuggestionManager;
- (void)invalidate;
- (id)initWithBlock:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

