//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray;
@protocol FBSectionedDataSourceWriting;

@interface FBComponentListViewDataSourceReloadAdapter : NSObject
{
    id <FBSectionedDataSourceWriting> _writeInterface;
    NSArray *_sectionedModels;
}

- (void).cxx_destruct;
- (void)reloadWithSectionedModels:(id)arg1;
- (id)init;
- (id)initWithWriteInterface:(id)arg1;

@end

