//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBCrowdsourcingNewSuggestEditsHoursUtil : NSObject
{
}

+ (id)textForHoursType:(id)arg1;
+ (id)closedZeroHours;
+ (BOOL)hasNonEmptyHoursForHoursData:(id)arg1;
+ (int)numberOfHourRowsWithValuesForDay:(int)arg1 inHoursData:(id)arg2;
+ (id)defaultHoursForRow:(int)arg1;
+ (BOOL)isHoursEmptyForDay:(int)arg1 atRow:(int)arg2 forHoursData:(id)arg3;
+ (id)prefixForDay:(int)arg1;
+ (BOOL)isRangeEmptyForTimeRange:(id)arg1;
+ (id)getHoursValueFromHoursData:(id)arg1 forDay:(int)arg2;

@end

