//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class FBMemPage, FBPlaceSummaryView, UIImageView;

@interface FBCrowdsourcingDuplicatesListCell : UITableViewCell
{
    UIImageView *_selectionImageView;
    FBPlaceSummaryView *_placeSummaryView;
    FBMemPage *_place;
}

@property(retain, nonatomic) FBMemPage *place; // @synthesize place=_place;
- (void).cxx_destruct;
- (void)setSelected:(BOOL)arg1 animated:(BOOL)arg2;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;
- (id)initWithReuseIdentifier:(id)arg1 session:(id)arg2;

@end

