//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, NSURL;

@interface FBCreativePlatformOutgoingAppAction : NSObject <NSCopying>
{
    unsigned int _subtype;
    NSString *_openAppFromComposerAction_appID;
    NSString *_openAppFromCommentAction_appID;
    NSString *_openAppStoreAction_appID;
    NSURL *_openAppStoreAction_appStoreURL;
}

+ (id)openAppStoreActionWithAppID:(id)arg1 appStoreURL:(id)arg2;
+ (id)openAppFromComposerActionWithAppID:(id)arg1;
+ (id)openAppFromCommentActionWithAppID:(id)arg1;
- (void).cxx_destruct;
- (void)matchOpenAppFromComposerAction:(CDUnknownBlockType)arg1 openAppFromCommentAction:(CDUnknownBlockType)arg2 openAppStoreAction:(CDUnknownBlockType)arg3;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

