//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBCrowdsourcingNewPlaceCreationTextFieldTableViewCellDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class FBCrowdsourcingCreationModel, NSString, UIImage;
@protocol FBCrowdsourcingPlaceCreationFormMainDataSourceDelegate;

@interface FBCrowdsourcingPlaceCreationFormMainDataSource : NSObject <UITextFieldDelegate, FBCrowdsourcingNewPlaceCreationTextFieldTableViewCellDelegate, UITableViewDataSource, UITableViewDelegate>
{
    UIImage *_cameraImage;
    FBCrowdsourcingCreationModel *_model;
    id <FBCrowdsourcingPlaceCreationFormMainDataSourceDelegate> _delegate;
}

+ (void)adjustMapView:(id)arg1 hasExactLocation:(BOOL)arg2;
@property(nonatomic) __weak id <FBCrowdsourcingPlaceCreationFormMainDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_switchValueDidChange:(id)arg1;
- (void)_didTapOnPhotoButton;
- (void)_didTapOnCameraButton;
- (id)_tableView:(id)arg1 cellForBottomSectionRowAtIndexItem:(int)arg2;
- (id)_tableView:(id)arg1 cellForLocationSectionRowAtIndexItem:(int)arg2;
- (id)_tableView:(id)arg1 cellForTopSectionRowAtIndexItem:(int)arg2;
- (BOOL)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldEditingChanged:(id)arg1;
- (id)tableView:(id)arg1 viewForFooterInSection:(int)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(int)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (float)tableView:(id)arg1 heightForFooterInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForHeaderInSection:(int)arg2;
- (float)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)initWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

