//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBDBLPinField, UIActivityIndicatorView, UIButton, UILabel;

@interface FBDBLPinRecoveryView : UIView
{
    UIView *_fakeNavBar;
    UILabel *_fakeNavBarTitle;
    UILabel *_instructionsLabel;
    UIView *_separator;
    unsigned int _passcodeLength;
    FBDBLPinField *_pinInput;
    UIButton *_removePinButton;
    UIActivityIndicatorView *_activityIndicator;
    struct UIEdgeInsets _minimumEdgeInsets;
}

@property(nonatomic) struct UIEdgeInsets minimumEdgeInsets; // @synthesize minimumEdgeInsets=_minimumEdgeInsets;
@property(readonly, nonatomic) UIActivityIndicatorView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(readonly, nonatomic) UIButton *removePinButton; // @synthesize removePinButton=_removePinButton;
@property(readonly, nonatomic) FBDBLPinField *pinInput; // @synthesize pinInput=_pinInput;
- (void).cxx_destruct;
- (id)_newRemovePasscodeButtonWithText:(id)arg1;
- (id)_newSeparator;
- (id)_newInstructions:(id)arg1;
- (id)_newNavBarTitleWithString:(id)arg1;
- (id)_newNavBar;
- (void)layoutSubviews;
- (id)initWithTitle:(id)arg1 instructions:(id)arg2 passcodeLength:(unsigned int)arg3;

@end

