//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBDevice : NSObject
{
}

+ (BOOL)systemVersionIsLessThan:(id)arg1;
+ (BOOL)systemVersionIsGreaterThanOrEqualTo:(id)arg1;
+ (id)systemVersion;
+ (BOOL)isRunningOnPadInPhoneEmulator;
+ (BOOL)prefersSystemBrowser;
+ (BOOL)supportsControlOfSoftKeyboardFrame;
+ (BOOL)isSlowerDevice;
+ (BOOL)needsLowResPhotos;
+ (id)carrierName;
+ (BOOL)supportsCamera;
+ (BOOL)supportsPhoneWithApplication:(id)arg1;
+ (BOOL)supportsPhone;
+ (id)networkName;
+ (id)networkSSID;
+ (struct FBDeviceBatteryInfo)deviceBatteryInfo;
+ (unsigned int)deviceModel;
+ (unsigned int)adjustedFillRate;
+ (unsigned int)coreCount;
+ (BOOL)isPad;
+ (id)model;
+ (id)architecture;
+ (id)machineName;
+ (id)machine;
+ (id)deviceID;
+ (void)getDeviceIDWithCompletionBlock:(CDUnknownBlockType)arg1 onQueue:(id)arg2;
+ (void)resetCache;
+ (void)initializeAndCacheValues;
+ (void)initialize;
+ (BOOL)supportsHighResThumbnails;

@end

