//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBCancelable-Protocol.h"

@interface FBDispatchCancelerWithAtomic : NSObject <FBCancelable>
{
    // Error parsing type: {atomic<bool>="__a_"AB}, name: _wasCanceled
}

- (id).cxx_construct;
- (BOOL)wasCanceled;
- (void)cancel;

@end

