//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBComposerAudiencePickerControllerDelegate-Protocol.h"
#import "FBFeedStoryPrivacyOptionsFetcherDelegate-Protocol.h"

@class FBComposerAudiencePickerViewController, FBComposerPrivacySetting, FBFeedStoryPrivacyOptionsFetcher, FBMemFeedStory, FBTaggableActivityEventObject, FBUserSession, NSArray, NSString;
@protocol FBEditPrivacyControllerDelegate, FBPrivacyItemProtocol;

@interface FBEditPrivacyController : NSObject <FBComposerAudiencePickerControllerDelegate, FBFeedStoryPrivacyOptionsFetcherDelegate>
{
    FBUserSession *_session;
    FBMemFeedStory *_story;
    FBComposerAudiencePickerViewController *_composerAudiencePickerViewController;
    id <FBPrivacyItemProtocol> _privacyItem;
    BOOL _advancedPrivacySettingsFetched;
    FBFeedStoryPrivacyOptionsFetcher *_feedStoryPrivacyOptionsFetcher;
    NSArray *_availablePrivacySettings;
    FBComposerPrivacySetting *_selectedPrivacySetting;
    NSArray *_taggedAndMentionedUsers;
    FBTaggableActivityEventObject *_taggedEvent;
    id <FBEditPrivacyControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <FBEditPrivacyControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)fetchDidFailWithError:(id)arg1;
- (void)fetchDidSucceedWithSelectedPrivacyOption:(id)arg1 allPrivacyOptions:(id)arg2 withTagPersons:(id)arg3 taggedEvent:(id)arg4;
- (void)audiencePickerControllerDidTapDoneNavigationButton:(id)arg1 finishedWithAvailablePrivacySettings:(id)arg2 selectedAudience:(id)arg3;
- (void)audiencePickerControllerDidTapCancelNavigationButton:(id)arg1;
- (void)_configureComposerAudiencePickerViewController;
- (void)_savePrivacySelection:(id)arg1;
- (id)_transformPrivacy:(id)arg1;
- (void)_loadMentionedPersonsFromStoryAndCombineWithTaggedPersons:(id)arg1 onCompletion:(CDUnknownBlockType)arg2;
- (void)_fetchAvailablePrivacySettingsForComplexPrivacyEditingWithCompletionBlock:(CDUnknownBlockType)arg1 errorBlock:(CDUnknownBlockType)arg2;
- (void)_configurePresentableViewController;
- (id)presentableViewController;
- (id)initWithPrivacyItem:(id)arg1 session:(id)arg2 story:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

