//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBEventsInviteViewControllerDelegate-Protocol.h"
#import "FBProfileSideFeedUnitContentControlling-Protocol.h"

@class FBMemEvent, FBUserSession, NSMutableDictionary, NSString;
@protocol FBNavigationCoordinator;

@interface FBEventsSideFeedInviteFriendsUnitContentController : NSObject <FBEventsInviteViewControllerDelegate, FBProfileSideFeedUnitContentControlling>
{
    FBUserSession *_session;
    NSString *_presentingEventID;
    NSMutableDictionary *_inviteeCandidatesStatus;
    id <FBNavigationCoordinator> _navigationCoordinator;
    FBMemEvent *_event;
}

- (void).cxx_destruct;
- (void)_updateInviteeStatus:(id)arg1;
- (void)_sendInvitesWithSelectedInvitees:(id)arg1;
- (void)didCancelWithInviteController:(id)arg1 forEventID:(id)arg2;
- (void)inviteController:(id)arg1 didFinishWithSelection:(id)arg2 forEventID:(id)arg3;
- (void)seeMoreButtonTapped;
- (BOOL)canPerformPrimaryAction:(id)arg1;
- (id)urlForModel:(id)arg1;
- (void)performPrimaryActionForModel:(id)arg1;
- (BOOL)hasPrimaryActionBeenTakenForModel:(id)arg1;
- (const struct FBGraphQLFieldSet *)includingFieldsQueriedInFieldSet;
- (id)thumbnailURLForModel:(id)arg1;
- (unsigned int)buttonGlyphNameForModel:(id)arg1;
- (id)seeMoreButtonTitle;
- (id)successfulSecondarySubtitleForModel:(id)arg1;
- (id)secondarySubtitleForModel:(id)arg1;
- (id)subtitleForModel:(id)arg1;
- (id)sectionTitleForUnit:(id)arg1;
- (id)copyEdge:(id)arg1 withNewNode:(id)arg2;
- (id)getUnitNameForAnalytics;
- (id)trackingStringForEdge:(id)arg1;
- (id)nodeForEdge:(id)arg1;
- (id)constructValidModelEdgesFromUnit:(id)arg1;
- (void)setEvent:(id)arg1;
- (void)setNavigationCoordinator:(id)arg1;
- (id)initWithSession:(id)arg1 presentingEventID:(id)arg2;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

