//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBExperimentContext.h"

@interface FBEventsDashboardReactNativeExperimentContext : FBExperimentContext
{
    BOOL _reactNativeEnabled;
    BOOL _cacheEnabled;
}

+ (id)parameterConfigurations;
+ (id)experimentName;
@property(nonatomic) BOOL cacheEnabled; // @synthesize cacheEnabled=_cacheEnabled;
@property(nonatomic) BOOL reactNativeEnabled; // @synthesize reactNativeEnabled=_reactNativeEnabled;

@end

