//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSMutableDictionary, NSMutableOrderedSet;
@protocol FBEventsInviteCandidateManagerDelegate;

@interface FBEventsInviteCandidateManager : NSObject
{
    NSMutableOrderedSet *_orderedSelectedCandidates;
    NSMutableDictionary *_selectedCandidatesMap;
    id <FBEventsInviteCandidateManagerDelegate> _delegate;
    int _maxSelectionCount;
}

@property(nonatomic) int maxSelectionCount; // @synthesize maxSelectionCount=_maxSelectionCount;
@property(nonatomic) __weak id <FBEventsInviteCandidateManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)removeCandidateFromInvitedList:(id)arg1;
- (void)addCandidateToSelectedList:(id)arg1;
@property(copy, nonatomic) NSArray *selectedCandidates;
- (BOOL)isCandidateSelected:(id)arg1;
@property(readonly, nonatomic) unsigned int selectedCandidateCount;
- (id)initWithMaximumSelectionCount:(unsigned int)arg1;

@end

