//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBEventsDashboardObjectFetcherProtocol-Protocol.h"

@class FBGraphQLMemPaginatedConnectionController, FBUserSession, NSString;

@interface FBEventsDashboardBirthdayObjectFetcher : NSObject <FBEventsDashboardObjectFetcherProtocol>
{
    FBUserSession *_session;
    NSString *_viewerId;
    BOOL _isLoading;
    int _loadLimit;
    int _month;
    int _day;
    FBGraphQLMemPaginatedConnectionController *_pageController;
}

- (void).cxx_destruct;
- (void)cancel;
- (id)getPeopleFromEdges:(id)arg1;
- (void)loadMore:(CDUnknownBlockType)arg1;
- (BOOL)isBusyLoadingMore;
- (BOOL)canLoadMore;
- (id)getPeopleFromResponse:(id)arg1;
- (void)resetWithStartDate:(id)arg1;
- (void)reset;
- (void)setResultLoadLimit:(int)arg1;
- (id)initWithSession:(id)arg1 viewer:(id)arg2 startDate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

