//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class NSArray, NSDictionary;

@interface FBExperimentParametersViewController : UITableViewController
{
    NSDictionary *_parameters;
    NSArray *_orderedKeys;
}

- (void).cxx_destruct;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (id)analyticsModule;
- (BOOL)fb_showBackArrowButton;
- (BOOL)fb_showNavigationJewels;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (id)initWithName:(id)arg1 parameters:(id)arg2;

@end

