//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSDictionary, NSString, UILabel;

@interface FBExpandingNavigationBarTitleViewController : UIViewController
{
    NSString *_titleText;
    UILabel *_expandingTitleView;
    NSDictionary *_textAttributes;
}

- (void).cxx_destruct;
- (BOOL)doesExpandingTitleViewWrap;
- (id)expandingTitleView;
- (id)initWithTitleText:(id)arg1 textAttributes:(id)arg2;

@end

