//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBExperimentContext.h"

@interface FBFacecastViewerCommentsExperimentContext : FBExperimentContext
{
    BOOL _enableViewerQueryPolling;
    int _count;
    int _interval;
    int _viewerWatchingTimerInSeconds;
    int _viewerWatchingNuxAnimationDelayInSeconds;
    int _viewerQueryDefaultTimeWindowInSeconds;
    int _viewerQueryPollingTimeInSeconds;
    int _viewersCounterPollInterval;
}

+ (id)experimentName;
+ (id)parameterConfigurations;
@property(nonatomic) BOOL enableViewerQueryPolling; // @synthesize enableViewerQueryPolling=_enableViewerQueryPolling;
@property(nonatomic) int viewersCounterPollInterval; // @synthesize viewersCounterPollInterval=_viewersCounterPollInterval;
@property(nonatomic) int viewerQueryPollingTimeInSeconds; // @synthesize viewerQueryPollingTimeInSeconds=_viewerQueryPollingTimeInSeconds;
@property(nonatomic) int viewerQueryDefaultTimeWindowInSeconds; // @synthesize viewerQueryDefaultTimeWindowInSeconds=_viewerQueryDefaultTimeWindowInSeconds;
@property(nonatomic) int viewerWatchingNuxAnimationDelayInSeconds; // @synthesize viewerWatchingNuxAnimationDelayInSeconds=_viewerWatchingNuxAnimationDelayInSeconds;
@property(nonatomic) int viewerWatchingTimerInSeconds; // @synthesize viewerWatchingTimerInSeconds=_viewerWatchingTimerInSeconds;
@property(nonatomic) int interval; // @synthesize interval=_interval;
@property(nonatomic) int count; // @synthesize count=_count;

@end

