//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class AVCaptureVideoPreviewLayer, UIImageView;

@interface FBFacecastCameraView : UIView
{
    BOOL _dimmed;
    UIView *_previewLayerContainer;
    AVCaptureVideoPreviewLayer *_previewLayer;
    UIImageView *_snapshotView;
    CDUnknownBlockType _flipCompletion;
}

+ (id)imageFromSampleBuffer:(struct opaqueCMSampleBuffer *)arg1 withPosition:(int)arg2;
@property(copy, nonatomic) CDUnknownBlockType flipCompletion; // @synthesize flipCompletion=_flipCompletion;
@property(retain, nonatomic) UIImageView *snapshotView; // @synthesize snapshotView=_snapshotView;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer; // @synthesize previewLayer=_previewLayer;
@property(retain, nonatomic) UIView *previewLayerContainer; // @synthesize previewLayerContainer=_previewLayerContainer;
@property(nonatomic) BOOL dimmed; // @synthesize dimmed=_dimmed;
- (void).cxx_destruct;
- (BOOL)isDimmed;
- (struct CGPoint)captureDevicePointOfInterestForPoint:(struct CGPoint)arg1;
- (void)_flipToPosition:(id)arg1;
- (void)flipFromSnapshot:(id)arg1 toPosition:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithCaptureSession:(id)arg1 orientation:(int)arg2;
- (void)layoutSubviews;
- (void)dealloc;

@end

