//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSNumber, NSString;

@interface FBFavoriteContactBuilder : NSObject
{
    NSString *_fbid;
    BOOL _isGroupContact;
    NSNumber *_rank;
}

+ (id)favoriteContact;
- (id)withRank:(id)arg1;
- (id)withGroupContactFlag:(BOOL)arg1;
- (id)withFBID:(id)arg1;
- (void)dealloc;
- (id)build;

@end

