//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBFeedSideFeedBirthdayRemindersView, UIButton, UILabel;

@protocol FBFeedSideFeedBirthdayRemindersViewDelegate <NSObject>

@optional
- (void)interactiveBirthdayView:(FBFeedSideFeedBirthdayRemindersView *)arg1 userDidTapNameLabel:(UILabel *)arg2;
- (void)interactiveBirthdayView:(FBFeedSideFeedBirthdayRemindersView *)arg1 userDidTapComposeButton:(UIButton *)arg2;
@end

