//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBFeedVideoViewPollerTarget-Protocol.h"
#import "FBInvalidating-Protocol.h"
#import "FBLegacyFeedVideoPlayerViewEndScreenDelegate-Protocol.h"
#import "FBLegacyFullScreenVideoViewControllerDelegate-Protocol.h"

@class FBLegacyFullScreenVideoViewController, FBUserSession, NSHashTable, NSNotificationCenter, NSString, UIView, ZRTariffedUxSentry;
@protocol FBFeedScrollingDelegate, FBFeedVideoPlayerContainer, FBFeedVideoViewPoller;

@interface FBFeedScrollingVideoController : NSObject <FBLegacyFullScreenVideoViewControllerDelegate, FBLegacyFeedVideoPlayerViewEndScreenDelegate, FBFeedVideoViewPollerTarget, FBInvalidating>
{
    NSNotificationCenter *_notificationCenter;
    BOOL _invalidated;
    id <FBFeedVideoViewPoller> _poller;
    NSHashTable *_suspendedViews;
    struct vector<FBTrackedVideoContainer, std::__1::allocator<FBTrackedVideoContainer>> _trackedContainers;
    UIView *_fullscreenVideoViewSuperview;
    id <FBFeedVideoPlayerContainer> _stoppedContainer;
    FBUserSession *_session;
    unsigned int _suspensionReasons;
    BOOL _queuedStopStreaming;
    id <FBFeedVideoPlayerContainer> _activeContainer;
    ZRTariffedUxSentry *_sentry;
    BOOL _velocityWithinAcceptableRange;
    double _lastScrollTime;
    double _lastScrollOriginY;
    double _lastVelocity;
    BOOL _isPadFeedRedesignEnabled;
    BOOL _cancellationWhileScrolling;
    BOOL _shouldTrackOverlayedVideos;
    BOOL _watchAndScrollPlaying;
    id <FBFeedScrollingDelegate> _feedScrollingOffsetDelegate;
    FBLegacyFullScreenVideoViewController *_fullscreenViewController;
}

@property(retain, nonatomic) FBLegacyFullScreenVideoViewController *fullscreenViewController; // @synthesize fullscreenViewController=_fullscreenViewController;
@property(nonatomic) __weak id <FBFeedScrollingDelegate> feedScrollingOffsetDelegate; // @synthesize feedScrollingOffsetDelegate=_feedScrollingOffsetDelegate;
@property(nonatomic) BOOL watchAndScrollPlaying; // @synthesize watchAndScrollPlaying=_watchAndScrollPlaying;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)enterFullScreenForVideoView:(id)arg1;
- (void)feedVideoPlayerWantsToReplay:(id)arg1;
- (void)_coveringSplitViewDidCenterView:(id)arg1;
- (void)_coveringSplitViewWillUncoverView:(id)arg1;
- (void)_applicationDidBecomeActive:(id)arg1;
- (void)_applicationWillResignActive:(id)arg1;
- (void)_removeSuspensionReason:(unsigned int)arg1;
- (void)_addSuspensionReason:(unsigned int)arg1;
- (void)fullScreenVideoPresentationViewControllerDidTapToChangeState:(id)arg1;
- (void)fullScreenVideoPresentationViewControllerDidDismiss:(id)arg1;
- (struct CGRect)fullScreenVideoPresentationViewController:(id)arg1 animationBoundsForView:(id)arg2;
- (void)_stopStreamingForNonActiveViews;
- (void)_updateActiveContainer;
- (float)_visibleVideoRatio:(id)arg1;
- (BOOL)_isVideoPlayerContainerCoveredByAnotherContainer:(id)arg1;
- (id)_channelEligibilityForContainer:(id)arg1;
- (void)_checkAcceptableScrollingVelocity;
- (float)_calculateIntersectionRatioOfView:(id)arg1;
- (struct CGRect)_feedBoundsFromWindowBounds:(struct CGRect)arg1;
- (void)_didTapVideoView:(id)arg1;
- (void)_enterFullScreenForContainer:(id)arg1 navigationCoordinator:(id)arg2 actionHandler:(id)arg3;
- (BOOL)isFullscreenSuperviewAncestorForView:(id)arg1;
- (void)exitFullScreenForVideoController:(id)arg1;
- (void)enterFullScreenForActiveVideoContainer;
- (void)enterFullScreenForVideoController:(id)arg1;
- (void)enterFullScreenForStory:(id)arg1;
- (void)enterFullScreenForVideo:(id)arg1;
- (void)updateActiveContainer:(id)arg1;
- (void)_endWatchAndScroll:(id)arg1;
- (void)_beginWatchAndScroll:(id)arg1;
- (void)_resumeInlineVideos;
- (void)_stopInlineVideos;
- (void)resumeInlineVideosWithinView:(id)arg1;
- (void)suspendInlineVideosWithinView:(id)arg1;
- (void)poll;
- (void)invalidateViewHierarchyForContainer:(id)arg1;
- (void)stopTrackingContainer:(id)arg1;
- (void)startTrackingContainer:(id)arg1 layoutIdiom:(unsigned int)arg2 playerSubOrigin:(id)arg3 videoChainingDepth:(unsigned int)arg4 navigationCoordinator:(id)arg5 actionHandler:(id)arg6;
- (void)stopFullscreenDismissalAnimation;
- (void)invalidate;
@property(readonly, nonatomic, getter=isValid) BOOL valid;
- (void)dealloc;
- (id)initWithSession:(id)arg1 poller:(id)arg2 notificationCenter:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

