//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, NSURL;

@interface FBFeedSideFeedTrendingArticlesHeader : NSObject
{
    NSURL *_coverImageURL;
    NSString *_category;
    NSString *_title;
    NSString *_domain;
}

@property(readonly, copy, nonatomic) NSString *domain; // @synthesize domain=_domain;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, copy, nonatomic) NSString *category; // @synthesize category=_category;
@property(readonly, copy, nonatomic) NSURL *coverImageURL; // @synthesize coverImageURL=_coverImageURL;
- (void).cxx_destruct;
- (id)initWithCoverImageURL:(id)arg1 category:(id)arg2 title:(id)arg3 domain:(id)arg4;

@end

