//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@class FBFeedAwesomizerCardFooterToolbox;
@protocol FBQueriedProfileFieldsProtocol;

@interface FBFeedAwesomizerFollowCardFooterComponent : CKCompositeComponent
{
    id <FBQueriedProfileFieldsProtocol> _profile;
    FBFeedAwesomizerCardFooterToolbox *_toolbox;
}

+ (id)newWithProfileEdge:(id)arg1 toolbox:(id)arg2;
@property(readonly, nonatomic) FBFeedAwesomizerCardFooterToolbox *toolbox; // @synthesize toolbox=_toolbox;
@property(readonly, nonatomic) id <FBQueriedProfileFieldsProtocol> profile; // @synthesize profile=_profile;
- (void).cxx_destruct;

@end

