//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBContentInsetTracker, FBFeedHeaderView, UIScrollView;

@interface FBFeedHeaderViewPositionManager : NSObject
{
    FBContentInsetTracker *_contentInsetTracker;
    BOOL _shouldScrollHeaderWithFeed;
    BOOL _isScrollingInFeed;
    BOOL _canAdjustHeaderView;
    BOOL _voiceOverRunning;
    BOOL _showsHeaderContainerViewShadowWhenNotVisible;
    BOOL _useInlinePublisherBar;
    UIScrollView *_scrollView;
    FBFeedHeaderView *_headerView;
    float _topLayoutGuideLength;
    float _bottomLayoutGuideLength;
    struct CGPoint _lastContentOffset;
}

+ (float)topPaddingScrollOffset;
@property(nonatomic) float bottomLayoutGuideLength; // @synthesize bottomLayoutGuideLength=_bottomLayoutGuideLength;
@property(nonatomic) float topLayoutGuideLength; // @synthesize topLayoutGuideLength=_topLayoutGuideLength;
@property(nonatomic) struct CGPoint lastContentOffset; // @synthesize lastContentOffset=_lastContentOffset;
@property(nonatomic) BOOL useInlinePublisherBar; // @synthesize useInlinePublisherBar=_useInlinePublisherBar;
@property(nonatomic) BOOL showsHeaderContainerViewShadowWhenNotVisible; // @synthesize showsHeaderContainerViewShadowWhenNotVisible=_showsHeaderContainerViewShadowWhenNotVisible;
@property(nonatomic) BOOL voiceOverRunning; // @synthesize voiceOverRunning=_voiceOverRunning;
@property(nonatomic) BOOL canAdjustHeaderView; // @synthesize canAdjustHeaderView=_canAdjustHeaderView;
@property(readonly, nonatomic) FBFeedHeaderView *headerView; // @synthesize headerView=_headerView;
@property(readonly, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)didPrependNewStories;
- (BOOL)isHeaderContainerViewPartiallyVisible;
- (void)_setBarContainerVerticalOffset:(float)arg1 cancelExtantAnimations:(BOOL)arg2 programmaticallyScrolled:(BOOL)arg3;
- (float)_additionalInsetForScrollOffsetY:(float)arg1 programmaticallyScrolled:(BOOL)arg2;
- (float)_overrideMaxBarOriginYForScrollOffsetY:(float)arg1 programmaticallyScrolled:(BOOL)arg2;
- (BOOL)_isScrollingInFeedForScrollOffsetY:(float)arg1 programmaticallyScrolled:(BOOL)arg2;
- (float)_maxBarContainerViewOriginY;
- (float)_minBarContainerViewOriginY;
- (void)_ensureHeaderContainerViewNotPartiallyVisible;
- (void)layoutBarContainerViewInRect:(struct CGRect)arg1;
@property(readonly, nonatomic) BOOL headerContainerViewHidden;
- (void)setHeaderContainerViewHidden:(BOOL)arg1 animated:(BOOL)arg2 programmaticallyScrolled:(BOOL)arg3;
- (void)setHeaderContainerViewHidden:(BOOL)arg1 animated:(BOOL)arg2;
- (float)verticalViewOffset;
- (float)visibleViewHeight;
- (float)visualViewHeight;
- (float)viewHeightIncludingShadow;
- (float)viewHeight;
- (float)scrollDeltaWithContentOffset:(struct CGPoint)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(BOOL)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)_adjustHeaderViewForScrollView:(id)arg1;
- (id)init;
- (id)initWithScrollView:(id)arg1 headerView:(id)arg2 shouldScrollHeaderWithFeed:(BOOL)arg3;

@end

