//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBScenePath, FBVideoPlaybackItem;

@interface FBFeedVideoPlayerConfig : NSObject
{
    FBVideoPlaybackItem *_videoItem;
    unsigned int _videoPlayerOptions;
    FBScenePath *_scenePath;
    int _priority;
}

@property(readonly, nonatomic) int priority; // @synthesize priority=_priority;
@property(readonly, nonatomic) FBScenePath *scenePath; // @synthesize scenePath=_scenePath;
@property(readonly, nonatomic) unsigned int videoPlayerOptions; // @synthesize videoPlayerOptions=_videoPlayerOptions;
@property(readonly, nonatomic) FBVideoPlaybackItem *videoItem; // @synthesize videoItem=_videoItem;
- (void).cxx_destruct;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initWithVideoItem:(id)arg1 videoPlayerOptions:(unsigned int)arg2 scenePath:(id)arg3 priority:(int)arg4;

@end

