//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIImage, UIView;

@protocol FBFeedSecondaryAction <NSObject>
- (NSString *)accessibilityIdentifier;
- (NSString *)detail;
- (UIImage *)icon;
- (NSString *)title;
- (void)performWithSourceView:(UIView *)arg1 sourceRect:(struct CGRect)arg2;

@optional
- (BOOL)shouldPerformAfterMenuDismissed;
- (BOOL)blueText;
- (int)menuPriority;
- (NSString *)actionNameForLogging;
@end

