//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBComposerMentionsContainerView, UIImageView, UITableView;

@interface FBFeedUFIComposerComponentMentionsContainerView : UIView
{
    FBComposerMentionsContainerView *_mentionsContainerView;
    UIImageView *_backgroundView;
    UIView *_lineAboveMentionsContainer;
    UIView *_lineBelowMentionsContainer;
    struct CGRect _storyCardFrameMinusComposerFrame;
    struct CGRect _visibleFrameForClipping;
}

@property(nonatomic) struct CGRect visibleFrameForClipping; // @synthesize visibleFrameForClipping=_visibleFrameForClipping;
@property(nonatomic) struct CGRect storyCardFrameMinusComposerFrame; // @synthesize storyCardFrameMinusComposerFrame=_storyCardFrameMinusComposerFrame;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
@property(readonly, nonatomic) UITableView *mentionsTableView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

