//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@class FBCrowdsourcingContext, FBFeedComponentToolbox, FBIntentAnalyticsInfo, FBMemPage;

@interface FBFeedStoryPlaceComponent : CKCompositeComponent
{
    FBFeedComponentToolbox *_toolbox;
    FBIntentAnalyticsInfo *_analyticsInfo;
    FBMemPage *_placePage;
    FBCrowdsourcingContext *_crowdsourcingContext;
}

+ (id)newWithPlace:(id)arg1 saveActionLink:(id)arg2 allowAddPhoto:(BOOL)arg3 toolbox:(id)arg4;
- (void).cxx_destruct;
- (void)didTapOnAddPhoto;
- (void)didTapOnMap;
- (void)didTapAttachmentCard:(id)arg1;

@end

