//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBFeedAwesomizerProfileListCardViewControllerListener-Protocol.h"

@class FBFeedAwesomizerCardAnalyticInfo, NSDate, NSMutableArray, NSMutableOrderedSet, NSMutableSet, NSString;

@interface FBFeedAwesomizerProfileListCardLogger : NSObject <FBFeedAwesomizerProfileListCardViewControllerListener>
{
    int _cardIdentifier;
    FBFeedAwesomizerCardAnalyticInfo *_analyticInfo;
    BOOL _profileSelectionAnimationsEnabled;
    NSDate *_cardOpenDate;
    float _maxContentOffsetYReached;
    NSMutableSet *_profilesThatHaveAppeared;
    NSDate *_lastTimeSpentTimeMarker;
    double _cardTimeSpent;
    double _learnMoreTimeSpent;
    BOOL _isLearnMoreOpen;
    NSMutableOrderedSet *_selectedProfiles;
    NSMutableOrderedSet *_unselectedProfiles;
    NSMutableArray *_tappedProfiles;
}

+ (id)newWithProfileListCardViewControllerListenerAnnouncer:(id)arg1;
- (void).cxx_destruct;
- (void)resetLastTimeSpentMarker;
- (void)addToCardTimeSpent;
- (void)addToLearnMoreTimeSpent;
- (void)fb_applicationWillResignActive;
- (void)fb_applicationDidBecomeActive;
- (void)profileAtIndexWasUnselected:(int)arg1;
- (void)profileAtIndexWasSelected:(int)arg1;
- (void)profileAtIndexWasOptimisticallyUnselected:(int)arg1;
- (void)profileAtIndexWasOptimisticallySelected:(int)arg1;
- (void)profileAtIndexWillAppear:(int)arg1;
- (void)scrollViewDidScroll:(struct FBScrollViewState)arg1;
- (void)learnMorePageWillClose;
- (void)learnMorePageWillOpen;
- (void)viewDidDisappear;
- (void)viewDidAppear;
- (void)cardWillCloseWithProfileProviderAnalyticInfo:(id)arg1;
- (void)cardWillOpenWithIdentifier:(int)arg1 analyticInfo:(id)arg2 profileSelectionAnimationsEnabled:(BOOL)arg3;
- (float)profileModificationCount;
- (double)cardTotalTimeSpent;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

