//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBProgressViewUpdatePolicy-Protocol.h"

@class NSString;

@interface FBFixedTimeUniformProgressViewUpdatePolicy : NSObject <FBProgressViewUpdatePolicy>
{
    double _totalTime;
    double _updateInterval;
    BOOL _animated;
}

- (BOOL)animated;
- (float)incrementForCurrentProgress:(float)arg1;
- (double)updateInterval;
- (id)initWithTotalTime:(double)arg1 updateInterval:(double)arg2 animated:(BOOL)arg3;

// Remaining properties
@property(readonly, copy, nonatomic) CDUnknownBlockType completionBlock;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

