//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBNuxPresenter-Protocol.h"
#import "FBSelfPresentingNux-Protocol.h"

@class FBFNInlineUpsellDataSource, FBFNNowNUXController, FBLocationAccessManager, FBUserSession, NSDictionary, NSString;
@protocol FBNuxDelegate;

@interface FBFNNowNUXPresenter : NSObject <FBNuxPresenter, FBSelfPresentingNux>
{
    FBFNInlineUpsellDataSource *_upsellDataSource;
    FBFNNowNUXController *_nuxController;
    FBUserSession *_session;
    FBLocationAccessManager *_locationAccessManager;
    int _nuxState;
    id <FBNuxDelegate> _nuxCoordinator;
}

@property(nonatomic) id <FBNuxDelegate> nuxCoordinator; // @synthesize nuxCoordinator=_nuxCoordinator;
- (void).cxx_destruct;
- (void)closeNuxAnimated:(BOOL)arg1;
- (void)showNux;
- (void)_loadNUXController:(id)arg1;
- (void)_loadDataIfNeeded;
- (int)nuxStateForTriggerID:(id)arg1 triggerContext:(id)arg2;
@property(readonly, nonatomic) int nuxType;
- (id)viewControllerForPresentation;
- (id)triggerIDs;
- (id)nuxID;
- (void)prepareWithServerContext:(id)arg1;
- (Class)serverContextClass;
- (BOOL)_isEnabled;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) NSDictionary *extraLogData;
@property(readonly) unsigned int hash;
@property(readonly, nonatomic) NSString *nuxAnalyticsModule;
@property(copy, nonatomic) CDUnknownBlockType onClosedBlock;
@property(readonly) Class superclass;

@end

