//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBFriendsNearbyPingActionViewDelegate-Protocol.h"
#import "FBFriendsNearbyPingDataDelegate-Protocol.h"
#import "FBKeyboardObserverDelegate-Protocol.h"
#import "FBPopoverControllerDelegate-Protocol.h"

@class FBFriendsNearbyLocationPing, FBKeyboardObserver, FBPopoverController, NSString;
@protocol FBFriendsNearbyDataController;

@interface FBFriendsNearbyPingDialogHelper : NSObject <FBFriendsNearbyPingDataDelegate, FBFriendsNearbyPingActionViewDelegate, FBPopoverControllerDelegate, FBKeyboardObserverDelegate>
{
    id <FBFriendsNearbyDataController> _dataController;
    CDUnknownBlockType _networkBlock;
    CDUnknownBlockType _completion;
    FBKeyboardObserver *_keyboardObserver;
    FBPopoverController *_presenter;
    FBFriendsNearbyLocationPing *_locationPing;
}

+ (id)_createDialogHelperWithPerson:(id)arg1 session:(id)arg2 dataController:(id)arg3 hostingView:(id)arg4 dataCompletionBlock:(CDUnknownBlockType)arg5 networkCompletionBlock:(CDUnknownBlockType)arg6;
+ (id)presentNewPingDialogForPerson:(id)arg1 session:(id)arg2 dataController:(id)arg3 hostingView:(id)arg4 dataCompletionBlock:(CDUnknownBlockType)arg5 networkCompletionBlock:(CDUnknownBlockType)arg6;
+ (id)presentEditPingDialogForPerson:(id)arg1 session:(id)arg2 untilTime:(id)arg3 dataController:(id)arg4 hostingView:(id)arg5 dataCompletionBlock:(CDUnknownBlockType)arg6 networkCompletionBlock:(CDUnknownBlockType)arg7;
@property(retain, nonatomic) FBFriendsNearbyLocationPing *locationPing; // @synthesize locationPing=_locationPing;
@property(retain, nonatomic) FBPopoverController *presenter; // @synthesize presenter=_presenter;
- (void).cxx_destruct;
- (void)fb_popoverControllerDidDismissPopover:(id)arg1 withInteraction:(unsigned int)arg2;
- (void)_adjustPopover:(struct CGRect)arg1;
- (void)keyboardObserver:(id)arg1 keyboardWillHideWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(int)arg5;
- (void)keyboardObserver:(id)arg1 keyboardWillShowWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(int)arg5;
- (void)keyboardObserver:(id)arg1 keyboardFrameWillChangeWithBeginFrame:(struct CGRect)arg2 endFrame:(struct CGRect)arg3 duration:(double)arg4 curve:(int)arg5;
- (void)dismissView;
- (id)locationPingForPerson:(id)arg1;
- (void)deletePing:(id)arg1 onDone:(CDUnknownBlockType)arg2;
- (void)sendPing:(id)arg1 onDone:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (id)initWithDataController:(id)arg1 completionBlock:(CDUnknownBlockType)arg2 networkCompletionBlock:(CDUnknownBlockType)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

