//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBCache, FBDiskCache, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface FBGIFLoader : NSObject
{
    NSObject<OS_dispatch_queue> *_callbackQueue;
    NSObject<OS_dispatch_queue> *_internalQueue;
    FBCache *_inMemoryCache;
    FBDiskCache *_diskCache;
    NSMutableDictionary *_completionBlocksForKey;
}

- (void).cxx_destruct;
- (void)clearCache;
- (void)_didLoadData:(id)arg1 forURLString:(id)arg2;
- (void)_loadDataForURLString:(id)arg1;
- (void)loadGIFWithURLString:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithCallbackQueue:(id)arg1 diskCache:(id)arg2;

@end

