//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBIntentTarget.h"

@class FBMemPerson, NSString;
@protocol FBGoodwillCampaign;

@interface FBGoodwillIntentTarget : FBIntentTarget
{
    NSString *_graphQLID;
}

+ (id)goodwillTargetForBirthday:(id)arg1;
+ (id)goodwillTargetWithCampaignGraphQLID:(id)arg1;
+ (id)goodwillIntentTargetWithBirthdayPerson:(id)arg1 birthdayComposerStyle:(unsigned int)arg2;
+ (id)goodwillIntentTargetWithCampaign:(id)arg1 campaignSource:(id)arg2;
@property(readonly, copy, nonatomic) NSString *graphQLID; // @synthesize graphQLID=_graphQLID;
- (void).cxx_destruct;
- (id)description;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)fallbackURLs;
@property(readonly, nonatomic) unsigned int birthdayComposerStyle;
@property(readonly, nonatomic) FBMemPerson *birthdayPerson;
@property(readonly, copy, nonatomic) NSString *campaignSource;
@property(readonly, nonatomic) id <FBGoodwillCampaign> goodwillCampaign;

@end

