//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBExperimentContext.h"

@class NSString;

@interface FBGroupsTabExperimentContext : FBExperimentContext
{
    BOOL _shouldShowGroupsTab;
    BOOL _showMessengerInNavigationBarForGroupsTab;
    NSString *_tabVersion;
}

+ (id)parameterConfigurations;
+ (id)experimentName;
@property(readonly, copy, nonatomic) NSString *tabVersion; // @synthesize tabVersion=_tabVersion;
@property(readonly, nonatomic) BOOL showMessengerInNavigationBarForGroupsTab; // @synthesize showMessengerInNavigationBarForGroupsTab=_showMessengerInNavigationBarForGroupsTab;
@property(readonly, nonatomic) BOOL shouldShowGroupsTab; // @synthesize shouldShowGroupsTab=_shouldShowGroupsTab;
- (void).cxx_destruct;

@end

