//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBValueObject.h"

#import "FBFIGConfig-Protocol.h"

@class FBGridViewLayout, NSString, UIColor;
@protocol FBGridViewDelegate;

@interface FBGridViewConfig : FBValueObject <FBFIGConfig>
{
    BOOL _scrollsToTop;
    BOOL _scrollEnabled;
    FBGridViewLayout *_layout;
    id <FBGridViewDelegate> _delegate;
    UIColor *_backgroundColor;
}

+ (id)newWithLayout:(id)arg1 delegate:(id)arg2 scrollsToTop:(BOOL)arg3 scrollEnabled:(BOOL)arg4 backgroundColor:(id)arg5;
@property(readonly, copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(readonly, nonatomic) BOOL scrollEnabled; // @synthesize scrollEnabled=_scrollEnabled;
@property(readonly, nonatomic) BOOL scrollsToTop; // @synthesize scrollsToTop=_scrollsToTop;
@property(readonly, nonatomic) id <FBGridViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) FBGridViewLayout *layout; // @synthesize layout=_layout;
- (void).cxx_destruct;
- (id)_initWithLayout:(id)arg1 delegate:(id)arg2 scrollsToTop:(BOOL)arg3 scrollEnabled:(BOOL)arg4 backgroundColor:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

