//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSObject, NSSet;
@protocol FBGraphQLFetchUnit, FBServiceTransactionMutating, OS_dispatch_queue;

@protocol FBGraphQLFetcher <NSObject>
- (void)maybePrefetchUnits:(NSSet *)arg1 prefetchPriority:(unsigned int)arg2 configurationCallback:(void (^)(FBGraphQLFetchConfigurationBuilder *))arg3;
- (void)maybePrefetch:(NSDictionary *)arg1 configurationCallback:(void (^)(FBGraphQLFetchConfigurationBuilder *))arg2;
- (void)maybePrefetch:(id <FBGraphQLFetchUnit>)arg1 prefetchPriority:(unsigned int)arg2 configurationCallback:(void (^)(FBGraphQLFetchConfigurationBuilder *))arg3;
- (id <FBServiceTransactionMutating>)fetchDataForUnits:(NSSet *)arg1 configurationCallback:(void (^)(FBGraphQLFetchConfigurationBuilder *))arg2 callbackQueue:(NSObject<OS_dispatch_queue> *)arg3 cachedResponseCallback:(void (^)(NSArray *))arg4 networkResponseCallback:(void (^)(NSArray *))arg5 errorCallback:(void (^)(NSError *, id <FBNetworkerRequestStatus>))arg6;
- (id <FBServiceTransactionMutating>)fetchDataForUnit:(id <FBGraphQLFetchUnit>)arg1 configurationCallback:(void (^)(FBGraphQLFetchConfigurationBuilder *))arg2 callbackQueue:(NSObject<OS_dispatch_queue> *)arg3 cachedResponseCallback:(void (^)(FBGraphQLFetcherCacheLookupResponse *))arg4 networkResponseCallback:(void (^)(FBGraphQLResponse *, id <FBNetworkerRequestStatus>))arg5 errorCallback:(void (^)(NSError *, id <FBNetworkerRequestStatus>))arg6;
@end

