//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBServiceTransactionMutating-Protocol.h"

@class NSString;
@protocol FBServiceTransactionMutating;

@interface FBGraphQLServiceTransactionToken : NSObject <FBServiceTransactionMutating>
{
    BOOL _cancelled;
    BOOL _cachedFetchCompleted;
    BOOL _networkFetchCompleted;
    id <FBServiceTransactionMutating> _serviceToken;
}

@property(retain, nonatomic) id <FBServiceTransactionMutating> serviceToken; // @synthesize serviceToken=_serviceToken;
- (void).cxx_destruct;
- (void)changePriorityToNewPriority:(int)arg1;
- (void)cancel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

