//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBMemModelObject, FBNetworkerRequest, FBUserSession, NSString;

@protocol FBGraphQLMutation <NSObject>
- (FBMemModelObject *)payloadFromResponse:(id)arg1;
- (FBNetworkerRequest *)mutationRequest:(FBUserSession *)arg1;
- (NSString *)commonMutationIdentifier;
- (void (^)(NSString *, NSError *))errorHandler;
- (void (^)(NSString *, FBMemModelObject *))successHandler;
- (FBMemModelObject *)rollbackOptimisticPayload;
- (FBMemModelObject *)optimisticPayload;
- (id)input;
- (NSString *)actorId;
- (NSString *)clientMutationId;
- (NSString *)mutationName;
@end

