//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "UIActionSheetDelegate-Protocol.h"

@class FBGroupsAdminIDsDataSource, FBUserSession, NSString, UIActionSheet;
@protocol FBGroupsBasicPersonActionSheetViewControllerDelegate, FBIntentHandler;

@interface FBGroupsBasicPersonActionSheetViewController : NSObject <UIActionSheetDelegate>
{
    UIActionSheet *_actionSheet;
    int _viewProfileButtonIndex;
    int _messageButtonIndex;
    int _makeAdminIndex;
    int _removeAsAdminIndex;
    int _removeButtonIndex;
    int _blockButtonIndex;
    int _unblockButtonIndex;
    NSString *_groupID;
    NSString *_personID;
    NSString *_personName;
    id <FBIntentHandler> _intentHandler;
    FBGroupsAdminIDsDataSource *_dataSource;
    id <FBGroupsBasicPersonActionSheetViewControllerDelegate> _delegate;
    FBUserSession *_session;
}

@property(readonly, nonatomic) FBUserSession *session; // @synthesize session=_session;
@property(nonatomic) __weak id <FBGroupsBasicPersonActionSheetViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_resetActionSheet;
- (id)_getActionSheetForPersonID:(id)arg1 adminIDs:(id)arg2;
- (void)_showConfirmationDialogToLeaveGroup;
- (void)leaveGroupWithGroupID:(id)arg1;
- (id)groupWithGroupID:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)setIntentHandler:(id)arg1;
- (void)showActionSheetWithUnblockOptionForPersonID:(id)arg1 personName:(id)arg2;
- (void)showActionSheetForPersonID:(id)arg1 personName:(id)arg2;
- (void)invalidateDataSource;
- (void)dealloc;
- (id)initWithSession:(id)arg1 groupID:(id)arg2;
- (id)initWithSession:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

