//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@protocol FBSearchInputContextProtocol;

@interface FBGraphSearchNullStateSectionHeaderWithActionComponent : CKCompositeComponent
{
    id <FBSearchInputContextProtocol> _context;
}

+ (id)newWithModel:(id)arg1 context:(id)arg2 actionType:(unsigned int)arg3;
- (void).cxx_destruct;
- (void)didTapAboutSuggestedSearches:(id)arg1;
- (void)didTapEditRecentSearches:(id)arg1;

@end

