//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBInterstitialViewController.h"

#import "FBInterstitialViewControlling-Protocol.h"
#import "FBInterstitialViewDelegate-Protocol.h"

@class FBInterstitialView, FBInterstitialViewConfig, FBUserSession, NSString, UIPageControl, UIView;
@protocol FBGroupCompletionCardInterstitialViewControllerDelegate;

@interface FBGroupCompletionCardInterstitialViewController : FBInterstitialViewController <FBInterstitialViewControlling, FBInterstitialViewDelegate>
{
    FBUserSession *_session;
    UIView *_cardView;
    FBInterstitialView *_cardContentView;
    FBInterstitialViewConfig *_config;
    UIPageControl *_pageControl;
    BOOL _completed;
    id <FBGroupCompletionCardInterstitialViewControllerDelegate> _delegate;
    int _currentPageNumber;
    int _numberOfPages;
}

@property(nonatomic) int numberOfPages; // @synthesize numberOfPages=_numberOfPages;
@property(nonatomic) int currentPageNumber; // @synthesize currentPageNumber=_currentPageNumber;
@property(readonly, nonatomic) BOOL completed; // @synthesize completed=_completed;
@property(nonatomic) __weak id <FBGroupCompletionCardInterstitialViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)interstitialView:(id)arg1 didSelectSecondaryButton:(id)arg2;
- (void)interstitialView:(id)arg1 didSelectPrimaryButton:(id)arg2;
- (void)_configureInterstitialView;
- (id)interstitialView;
- (void)markCompletedWithPrimaryButtonTitle:(id)arg1 secondaryButtonTitle:(id)arg2;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithSession:(id)arg1 config:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(nonatomic) BOOL showStatusBar;
@property(readonly) Class superclass;

@end

