//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBGraphQLBatchRequest, NSMutableArray, NSMutableDictionary;

@interface FBGraphQLBatchResponsesBuffer : NSObject
{
    FBGraphQLBatchRequest *_request;
    NSMutableArray *_arrayOfBuffers;
    unsigned int _vendedResponsesCount;
    NSMutableDictionary *_countForQueriesReferenceParameters;
}

- (void).cxx_destruct;
- (BOOL)hasVendedAllExpectedResponses;
- (id)vendNextResponse;
- (id)_responseBufferForQuery:(id)arg1;
- (void)addResponse:(id)arg1;
- (id)initForRequest:(id)arg1;
- (id)init;

@end

