//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBMessengerStatusUpdateFetcher-Protocol.h"

@class FBGraphQLMessengerStatusUpdateFetchRequest, FBUserSession, NSString;
@protocol FBMessengerStatusUpdateFetchListener, FBPerforming;

@interface FBGraphQLMessengerStatusUpdateFetcher : NSObject <FBMessengerStatusUpdateFetcher>
{
    id <FBMessengerStatusUpdateFetchListener> _listener;
    FBGraphQLMessengerStatusUpdateFetchRequest *_outstandingRequest;
    id <FBPerforming> _responsePerformer;
    FBUserSession *_session;
}

- (void)cancelFetchOfMessengerStatusUpdatesForAllContacts;
- (void)fetchMessengerStatusUpdatesForAllContacts;
- (void)dealloc;
- (id)initWithSession:(id)arg1 responsePerformer:(id)arg2 listener:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

