//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBExperimentContext.h"

@class NSString;

@interface FBGroupCommerceFilterViewExperimentContext : FBExperimentContext
{
    BOOL _showSecondaryFeedButtonOnMainMall;
    NSString *_secondaryFeedButtonText;
    int _mainFeedType;
    int _secondaryFeedType;
    Class _mainFeedStreamClass;
    Class _secondaryFeedStreamClass;
}

+ (id)parameterConfigurations;
+ (id)experimentName;
@property(retain, nonatomic) Class secondaryFeedStreamClass; // @synthesize secondaryFeedStreamClass=_secondaryFeedStreamClass;
@property(retain, nonatomic) Class mainFeedStreamClass; // @synthesize mainFeedStreamClass=_mainFeedStreamClass;
@property(nonatomic) int secondaryFeedType; // @synthesize secondaryFeedType=_secondaryFeedType;
@property(nonatomic) int mainFeedType; // @synthesize mainFeedType=_mainFeedType;
@property(copy, nonatomic) NSString *secondaryFeedButtonText; // @synthesize secondaryFeedButtonText=_secondaryFeedButtonText;
@property(nonatomic) BOOL showSecondaryFeedButtonOnMainMall; // @synthesize showSecondaryFeedButtonOnMainMall=_showSecondaryFeedButtonOnMainMall;
- (void).cxx_destruct;

@end

