//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol FBGraphQLObjectFactory, FBGraphQLResponseParserImpl;

@interface FBGraphQLResponseParser : NSObject
{
    id <FBGraphQLResponseParserImpl> _impl;
}

@property(readonly, retain, nonatomic) id <FBGraphQLObjectFactory> objectFactory;
@property(nonatomic) BOOL allowResponsesWithStrippedNulls;
- (id)parse:(id)arg1 query:(id)arg2 managedObjectContext:(id)arg3 error:(id *)arg4;
- (void)dealloc;
- (id)initWithObjectFactory:(id)arg1;
- (id)init;

@end

