//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@protocol FBGraphQLConnectionStoreEdgeFiltering;

@interface FBGraphQLConnectionEdgeFilter : NSObject
{
    id <FBGraphQLConnectionStoreEdgeFiltering> _filter;
    int _priority;
}

@property(readonly, nonatomic) int priority; // @synthesize priority=_priority;
@property(readonly, nonatomic) id <FBGraphQLConnectionStoreEdgeFiltering> filter; // @synthesize filter=_filter;
- (void).cxx_destruct;
- (id)init;
- (id)initWithFilter:(id)arg1 priority:(int)arg2;

@end

