//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBHorizontalSwipeBasedDismissalManager;

@protocol FBHorizontalSwipeBasedDismissalManagerDelegate <NSObject>
- (void)horizontalSwipeBasedDismissalManagerDidDetectDismissalGesture:(FBHorizontalSwipeBasedDismissalManager *)arg1;

@optional
- (void)horizontalSwipeBasedDismissalManager:(FBHorizontalSwipeBasedDismissalManager *)arg1 didUpdateContainerTranslationProgress:(float)arg2;
- (void)horizontalSwipeBasedDismissalManagerDidBeginSwipingContainerView:(FBHorizontalSwipeBasedDismissalManager *)arg1;
- (void)horizontalSwipeBasedDismissalManagerDidEndContainerReset:(FBHorizontalSwipeBasedDismissalManager *)arg1;
@end

