//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBHorizontalImageListCountView, FBUserSession, NSArray;

@interface FBHorizontalImageListView : UIView
{
    int _maxPicturesToShow;
    float _imageSize;
    float _imagePadding;
    unsigned int _othersCount;
    unsigned int _imageListViewStyle;
    NSArray *_imageViews;
    FBHorizontalImageListCountView *_othersView;
    FBUserSession *_session;
    NSArray *_imageURLs;
    float _cornerRadius;
}

+ (struct CGSize)viewSizeForNumberOfImages:(int)arg1 othersCount:(int)arg2 imageSize:(float)arg3 imagePadding:(float)arg4 style:(unsigned int)arg5;
@property(nonatomic) float cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) unsigned int othersCount; // @synthesize othersCount=_othersCount;
@property(copy, nonatomic) NSArray *imageURLs; // @synthesize imageURLs=_imageURLs;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)_setupViews;
- (id)_placesProfileImageView;
- (id)initWithImageURLs:(id)arg1 maxPicturesToShow:(int)arg2 imageSize:(float)arg3 session:(id)arg4;
- (id)initWithImageURLs:(id)arg1 maxPicturesToShow:(int)arg2 imageSize:(float)arg3 othersCount:(unsigned int)arg4 imagePadding:(float)arg5 session:(id)arg6;
- (id)initWithImageURLs:(id)arg1 maxPicturesToShow:(int)arg2 imageSize:(float)arg3 othersCount:(unsigned int)arg4 imagePadding:(float)arg5 session:(id)arg6 style:(unsigned int)arg7;

@end

