//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBExperimentContext.h"

@interface FBIdleDetectorWarmStartExperimentContext : FBExperimentContext
{
    BOOL _delayAppConfigService;
    BOOL _delayBookmarkDecoratorDataSource;
    BOOL _delayBookmarkGraphQLLoader;
    BOOL _delayBookmarkNavigationViewCoordinator;
    BOOL _delayPlacePickerPrefetch;
    BOOL _delayGravityManager;
    BOOL _delayGravityListener;
    BOOL _delayPlaceTips;
    BOOL _delayStarRatings;
    BOOL _delayGuideNullState;
    BOOL _delayRapidFeedback;
    unsigned int _secondsBeforeIdleDetectorFiresAfterWarmStart;
}

+ (BOOL)allowUserInterfaceIdiom:(int)arg1;
+ (id)parameterConfigurations;
+ (id)experimentName;
@property(nonatomic) BOOL delayRapidFeedback; // @synthesize delayRapidFeedback=_delayRapidFeedback;
@property(nonatomic) BOOL delayGuideNullState; // @synthesize delayGuideNullState=_delayGuideNullState;
@property(nonatomic) BOOL delayStarRatings; // @synthesize delayStarRatings=_delayStarRatings;
@property(nonatomic) BOOL delayPlaceTips; // @synthesize delayPlaceTips=_delayPlaceTips;
@property(nonatomic) BOOL delayGravityListener; // @synthesize delayGravityListener=_delayGravityListener;
@property(nonatomic) BOOL delayGravityManager; // @synthesize delayGravityManager=_delayGravityManager;
@property(nonatomic) BOOL delayPlacePickerPrefetch; // @synthesize delayPlacePickerPrefetch=_delayPlacePickerPrefetch;
@property(nonatomic) BOOL delayBookmarkNavigationViewCoordinator; // @synthesize delayBookmarkNavigationViewCoordinator=_delayBookmarkNavigationViewCoordinator;
@property(nonatomic) BOOL delayBookmarkGraphQLLoader; // @synthesize delayBookmarkGraphQLLoader=_delayBookmarkGraphQLLoader;
@property(nonatomic) BOOL delayBookmarkDecoratorDataSource; // @synthesize delayBookmarkDecoratorDataSource=_delayBookmarkDecoratorDataSource;
@property(nonatomic) BOOL delayAppConfigService; // @synthesize delayAppConfigService=_delayAppConfigService;
@property(readonly, nonatomic) unsigned int secondsBeforeIdleDetectorFiresAfterWarmStart; // @synthesize secondsBeforeIdleDetectorFiresAfterWarmStart=_secondsBeforeIdleDetectorFiresAfterWarmStart;
- (id)rapidFeedbackWarmStartNotificationName;
- (id)guideNullStateWarmStartNotificationName;
- (id)starRatingsWarmStartNotificationName;
- (id)placeTipsWarmStartNotificationName;
- (id)gravityListenerWarmStartNotificationName;
- (id)gravityManagerWarmStartNotificationName;
- (id)placePickerPrefetchWarmStartNotificationName;
- (id)bookmarkNavigationViewCoordinatorWarmStartNotificationName;
- (id)bookmarkGraphQLLoaderWarmStartNotificationName;
- (id)bookmarkDecoratorDataSourceWarmStartNotificationName;
- (id)appConfigServiceWarmStartNotificationName;

@end

