//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBImageProcessingConcurrentRequest.h"

@class NSDictionary, UIImage;

@interface FBImageProcessingFaceCropRequest : FBImageProcessingConcurrentRequest
{
    UIImage *_image;
    NSDictionary *_faces;
    BOOL _useRGBColorSpace;
    float _compressionRate;
    NSDictionary *_faceCropJPEGs;
}

@property(retain, nonatomic) NSDictionary *faceCropJPEGs; // @synthesize faceCropJPEGs=_faceCropJPEGs;
- (void).cxx_destruct;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (void)executeWithContext:(id)arg1;
- (id)_dataFromCrop:(struct CGImage *)arg1 width:(unsigned long)arg2 height:(unsigned long)arg3 bytesPerRow:(unsigned long)arg4 colorSpace:(struct CGColorSpace *)arg5 bitmapInfo:(unsigned int)arg6;
- (id)initWithImage:(id)arg1 faces:(id)arg2 useRGBColorSpace:(BOOL)arg3 compressionRate:(float)arg4 completion:(CDUnknownBlockType)arg5 cancel:(CDUnknownBlockType)arg6;

@end

