//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBEventListener-Protocol.h"

@class FBLogarithmicBucketizer, NSString, UIApplication, UIView;
@protocol FBApplicationSendEventHookable, FBInteractionLagLogger;

@interface FBInteractionLagTracker : NSObject <FBEventListener>
{
    UIView *_view;
    UIApplication<FBApplicationSendEventHookable> *_application;
    id <FBInteractionLagLogger> _logger;
    FBLogarithmicBucketizer *_stats;
    unsigned int _option;
    struct __CFRunLoopObserver *_runloopObserver;
    struct vector<double, std::__1::allocator<double>> _touchEventTimestamps;
    NSString *_eventName;
    CDUnknownBlockType _timeBlock;
}

@property(copy, nonatomic) CDUnknownBlockType timeBlock; // @synthesize timeBlock=_timeBlock;
@property(retain, nonatomic) UIView *view; // @synthesize view=_view;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_stopRunloopObserver;
- (void)_startRunloopObserver;
- (void)_prepareRunloopObserverIfNeeded;
- (void)didSendEvent:(id)arg1;
- (void)willSendEvent:(id)arg1;
- (void)_report;
- (void)_removeApplicationEventHook;
- (void)_addApplicationEventHook;
- (void)stop;
- (void)startForView:(id)arg1;
- (void)dealloc;
- (id)initWithApplication:(id)arg1 logger:(id)arg2 option:(unsigned int)arg3 eventName:(id)arg4 stats:(id)arg5 timeBlock:(CDUnknownBlockType)arg6;
- (id)initWithApplication:(id)arg1 logger:(id)arg2 option:(unsigned int)arg3 eventName:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

