//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBCoreShareAction.h"

#import "FBMailCoreShareAction-Protocol.h"
#import "FBMailShareActionDelegate-Protocol.h"

@class FBMailShareAction, NSDictionary, NSString;
@protocol FBCoreShareActionDelegate, FBNavigationCoordinator;

@interface FBInternalMailShareAction : FBCoreShareAction <FBMailShareActionDelegate, FBMailCoreShareAction>
{
    NSString *_analyticsModule;
    NSDictionary *_analyticsExtras;
    id <FBNavigationCoordinator> _navigationCoordinator;
    FBMailShareAction *_mailShareAction;
    id <FBCoreShareActionDelegate> _delegate;
}

+ (BOOL)canSendMail;
@property(nonatomic) __weak id <FBCoreShareActionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)shareAction:(id)arg1 didShareWithResponse:(id)arg2;
- (void)shareAction:(id)arg1 percentCompleted:(double)arg2;
- (void)mailShareAction:(id)arg1 didFinishWithMailComposeViewController:(id)arg2 result:(int)arg3 error:(id)arg4;
- (void)presentMailComposerViewController:(id)arg1;
- (void)performShareActionWithShareableURL:(id)arg1 shareableImageURL:(id)arg2 shareableImage:(id)arg3 shareTitle:(id)arg4 shareMessage:(id)arg5;
- (id)initWithNavigationCoordinator:(id)arg1 analyticsModule:(id)arg2 analyticsExtras:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

