//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBCoreShareAction.h"

#import "FBReshareCoreShareAction-Protocol.h"

@class FBComposerPrivacySetting, FBComposerPublisherData, FBInternalReshareStatusListener, FBUserSession, NSArray, NSDictionary, NSString;
@protocol FBCoreShareActionDelegate;

@interface FBInternalReshareShareAction : FBCoreShareAction <FBReshareCoreShareAction>
{
    FBInternalReshareStatusListener *_reshareStatusListener;
    FBComposerPublisherData *_composerPublisherData;
    FBComposerPrivacySetting *_shareNowPrivacySetting;
    FBUserSession *_userSession;
    NSString *_analyticsModule;
    NSArray *_trackingCodes;
    NSDictionary *_analyticsExtras;
    id <FBCoreShareActionDelegate> _delegate;
}

@property(nonatomic) __weak id <FBCoreShareActionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_cleanupAfterSharing;
- (void)_logConclusionAnalyticsWithCompositionId:(id)arg1 shareType:(id)arg2;
- (void)performShareActionWithShareableURL:(id)arg1 shareableImageURL:(id)arg2 shareableImage:(id)arg3 shareTitle:(id)arg4 shareMessage:(id)arg5;
- (id)initWithShareable:(id)arg1 actor:(id)arg2 composerSourceType:(id)arg3 publicationOrigin:(id)arg4 postReactionEnabled:(BOOL)arg5 userSession:(id)arg6 analyticsModule:(id)arg7 trackingCodes:(id)arg8 analyticsExtras:(id)arg9;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

