//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBValueObject.h"

#import "FBFIGConfig-Protocol.h"

@class FBImageDownloader, NSAttributedString, NSString, UIColor, UIFont;

@interface FBItemContentViewConfig : FBValueObject <FBFIGConfig>
{
    NSAttributedString *_title;
    unsigned int _titleMaxLines;
    UIFont *_titleFallbackFont;
    UIColor *_titleFallbackColor;
    UIColor *_titleShadowColor;
    float _titleShadowBlur;
    NSAttributedString *_subtitle;
    unsigned int _subtitleMaxLines;
    UIFont *_subtitleFallbackFont;
    UIColor *_subtitleFallbackColor;
    UIColor *_subtitleShadowColor;
    float _subtitleShadowBlur;
    NSAttributedString *_secondarySubtitle;
    unsigned int _secondarySubtitleMaxLines;
    UIFont *_secondarySubtitleFallbackFont;
    UIColor *_secondarySubtitleFallbackColor;
    UIColor *_secondarySubtitleShadowColor;
    float _secondarySubtitleShadowBlur;
    NSAttributedString *_tertiarySubtitle;
    unsigned int _tertiarySubtitleMaxLines;
    UIFont *_tertiarySubtitleFallbackFont;
    UIColor *_tertiarySubtitleFallbackColor;
    UIColor *_tertiarySubtitleShadowColor;
    float _tertiarySubtitleShadowBlur;
    UIColor *_backgroundColor;
    float _verticalSpacing;
    FBImageDownloader *_imageDownloader;
    struct CGSize _titleShadowOffset;
    struct CGSize _subtitleShadowOffset;
    struct CGSize _secondarySubtitleShadowOffset;
    struct CGSize _tertiarySubtitleShadowOffset;
    struct UIEdgeInsets _insets;
}

+ (id)newWithTitle:(id)arg1 titleMaxLines:(unsigned int)arg2 titleFallbackFont:(id)arg3 titleFallbackColor:(id)arg4 titleShadowOffset:(struct CGSize)arg5 titleShadowColor:(id)arg6 titleShadowBlur:(float)arg7 subtitle:(id)arg8 subtitleMaxLines:(unsigned int)arg9 subtitleFallbackFont:(id)arg10 subtitleFallbackColor:(id)arg11 subtitleShadowOffset:(struct CGSize)arg12 subtitleShadowColor:(id)arg13 subtitleShadowBlur:(float)arg14 secondarySubtitle:(id)arg15 secondarySubtitleMaxLines:(unsigned int)arg16 secondarySubtitleFallbackFont:(id)arg17 secondarySubtitleFallbackColor:(id)arg18 secondarySubtitleShadowOffset:(struct CGSize)arg19 secondarySubtitleShadowColor:(id)arg20 secondarySubtitleShadowBlur:(float)arg21 tertiarySubtitle:(id)arg22 tertiarySubtitleMaxLines:(unsigned int)arg23 tertiarySubtitleFallbackFont:(id)arg24 tertiarySubtitleFallbackColor:(id)arg25 tertiarySubtitleShadowOffset:(struct CGSize)arg26 tertiarySubtitleShadowColor:(id)arg27 tertiarySubtitleShadowBlur:(float)arg28 backgroundColor:(id)arg29 verticalSpacing:(float)arg30 insets:(struct UIEdgeInsets)arg31 imageDownloader:(id)arg32;
@property(readonly, nonatomic) FBImageDownloader *imageDownloader; // @synthesize imageDownloader=_imageDownloader;
@property(readonly, nonatomic) struct UIEdgeInsets insets; // @synthesize insets=_insets;
@property(readonly, nonatomic) float verticalSpacing; // @synthesize verticalSpacing=_verticalSpacing;
@property(readonly, copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(readonly, nonatomic) float tertiarySubtitleShadowBlur; // @synthesize tertiarySubtitleShadowBlur=_tertiarySubtitleShadowBlur;
@property(readonly, copy, nonatomic) UIColor *tertiarySubtitleShadowColor; // @synthesize tertiarySubtitleShadowColor=_tertiarySubtitleShadowColor;
@property(readonly, nonatomic) struct CGSize tertiarySubtitleShadowOffset; // @synthesize tertiarySubtitleShadowOffset=_tertiarySubtitleShadowOffset;
@property(readonly, copy, nonatomic) UIColor *tertiarySubtitleFallbackColor; // @synthesize tertiarySubtitleFallbackColor=_tertiarySubtitleFallbackColor;
@property(readonly, copy, nonatomic) UIFont *tertiarySubtitleFallbackFont; // @synthesize tertiarySubtitleFallbackFont=_tertiarySubtitleFallbackFont;
@property(readonly, nonatomic) unsigned int tertiarySubtitleMaxLines; // @synthesize tertiarySubtitleMaxLines=_tertiarySubtitleMaxLines;
@property(readonly, copy, nonatomic) NSAttributedString *tertiarySubtitle; // @synthesize tertiarySubtitle=_tertiarySubtitle;
@property(readonly, nonatomic) float secondarySubtitleShadowBlur; // @synthesize secondarySubtitleShadowBlur=_secondarySubtitleShadowBlur;
@property(readonly, copy, nonatomic) UIColor *secondarySubtitleShadowColor; // @synthesize secondarySubtitleShadowColor=_secondarySubtitleShadowColor;
@property(readonly, nonatomic) struct CGSize secondarySubtitleShadowOffset; // @synthesize secondarySubtitleShadowOffset=_secondarySubtitleShadowOffset;
@property(readonly, copy, nonatomic) UIColor *secondarySubtitleFallbackColor; // @synthesize secondarySubtitleFallbackColor=_secondarySubtitleFallbackColor;
@property(readonly, copy, nonatomic) UIFont *secondarySubtitleFallbackFont; // @synthesize secondarySubtitleFallbackFont=_secondarySubtitleFallbackFont;
@property(readonly, nonatomic) unsigned int secondarySubtitleMaxLines; // @synthesize secondarySubtitleMaxLines=_secondarySubtitleMaxLines;
@property(readonly, copy, nonatomic) NSAttributedString *secondarySubtitle; // @synthesize secondarySubtitle=_secondarySubtitle;
@property(readonly, nonatomic) float subtitleShadowBlur; // @synthesize subtitleShadowBlur=_subtitleShadowBlur;
@property(readonly, copy, nonatomic) UIColor *subtitleShadowColor; // @synthesize subtitleShadowColor=_subtitleShadowColor;
@property(readonly, nonatomic) struct CGSize subtitleShadowOffset; // @synthesize subtitleShadowOffset=_subtitleShadowOffset;
@property(readonly, copy, nonatomic) UIColor *subtitleFallbackColor; // @synthesize subtitleFallbackColor=_subtitleFallbackColor;
@property(readonly, copy, nonatomic) UIFont *subtitleFallbackFont; // @synthesize subtitleFallbackFont=_subtitleFallbackFont;
@property(readonly, nonatomic) unsigned int subtitleMaxLines; // @synthesize subtitleMaxLines=_subtitleMaxLines;
@property(readonly, copy, nonatomic) NSAttributedString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, nonatomic) float titleShadowBlur; // @synthesize titleShadowBlur=_titleShadowBlur;
@property(readonly, copy, nonatomic) UIColor *titleShadowColor; // @synthesize titleShadowColor=_titleShadowColor;
@property(readonly, nonatomic) struct CGSize titleShadowOffset; // @synthesize titleShadowOffset=_titleShadowOffset;
@property(readonly, copy, nonatomic) UIColor *titleFallbackColor; // @synthesize titleFallbackColor=_titleFallbackColor;
@property(readonly, copy, nonatomic) UIFont *titleFallbackFont; // @synthesize titleFallbackFont=_titleFallbackFont;
@property(readonly, nonatomic) unsigned int titleMaxLines; // @synthesize titleMaxLines=_titleMaxLines;
@property(readonly, copy, nonatomic) NSAttributedString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)_initWithTitle:(id)arg1 titleMaxLines:(unsigned int)arg2 titleFallbackFont:(id)arg3 titleFallbackColor:(id)arg4 titleShadowOffset:(struct CGSize)arg5 titleShadowColor:(id)arg6 titleShadowBlur:(float)arg7 subtitle:(id)arg8 subtitleMaxLines:(unsigned int)arg9 subtitleFallbackFont:(id)arg10 subtitleFallbackColor:(id)arg11 subtitleShadowOffset:(struct CGSize)arg12 subtitleShadowColor:(id)arg13 subtitleShadowBlur:(float)arg14 secondarySubtitle:(id)arg15 secondarySubtitleMaxLines:(unsigned int)arg16 secondarySubtitleFallbackFont:(id)arg17 secondarySubtitleFallbackColor:(id)arg18 secondarySubtitleShadowOffset:(struct CGSize)arg19 secondarySubtitleShadowColor:(id)arg20 secondarySubtitleShadowBlur:(float)arg21 tertiarySubtitle:(id)arg22 tertiarySubtitleMaxLines:(unsigned int)arg23 tertiarySubtitleFallbackFont:(id)arg24 tertiarySubtitleFallbackColor:(id)arg25 tertiarySubtitleShadowOffset:(struct CGSize)arg26 tertiarySubtitleShadowColor:(id)arg27 tertiarySubtitleShadowBlur:(float)arg28 backgroundColor:(id)arg29 verticalSpacing:(float)arg30 insets:(struct UIEdgeInsets)arg31 imageDownloader:(id)arg32;
- (id)_attributedString:(id)arg1 stringWithDefaultFontFallback:(id)arg2 textColor:(id)arg3;
- (id)truncationTokenForAttributedString:(id)arg1;
- (id)tertiarySubtitleWithFontFallback;
- (id)secondarySubtitleWithFontFallback;
- (id)subtitleWithFontFallback;
- (id)titleWithFontFallback;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

