//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBDataDeserializing-Protocol.h"

@class NSSet;

@interface FBJSONResponseDeserializer : NSObject <FBDataDeserializing>
{
    Class _expectedType;
    NSSet *_expectedTypes;
}

@property(readonly, copy, nonatomic) NSSet *expectedTypes; // @synthesize expectedTypes=_expectedTypes;
- (void).cxx_destruct;
- (id)_parseJSONDataFragment:(id)arg1 error:(id *)arg2;
- (void)deserialize:(id)arg1 responseProcessor:(id)arg2 callbackQueue:(id)arg3 completionCallback:(CDUnknownBlockType)arg4 failureCallback:(CDUnknownBlockType)arg5;
- (id)description;
- (id)initWithExpectedTypes:(id)arg1;
- (id)initWithExpectedType:(Class)arg1;

@end

