//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "CKStatefulViewComponent.h"

@class FBFeedComponentToolbox, FBFeedEventBus, FBFeedVideoPlayerConfig, FBIntentAnalyticsInfo, FBMemSponsorshipData, FBMemVideo, NSArray;
@protocol FBQueriedEntityFieldsProtocol;

@interface FBLegacyBaseVideoPlayerComponent : CKStatefulViewComponent
{
    FBIntentAnalyticsInfo *_analyticsInfo;
    FBFeedComponentToolbox *_toolbox;
    id <FBQueriedEntityFieldsProtocol> _parent;
    unsigned int _videoPlayerOptions;
    FBMemVideo *_video;
    FBFeedVideoPlayerConfig *_config;
    FBMemSponsorshipData *_sponsorship;
    unsigned int _videoChainingDepth;
    NSArray *_trackingCodes;
    FBFeedEventBus *_eventBus;
}

+ (id)newWithVideo:(id)arg1 parent:(id)arg2 sponsorship:(id)arg3 videoPlayerOptions:(unsigned int)arg4 size:(const struct CKComponentSize *)arg5 eventBus:(id)arg6 toolbox:(id)arg7;
@property(readonly, nonatomic) FBFeedEventBus *eventBus; // @synthesize eventBus=_eventBus;
@property(readonly, copy, nonatomic) NSArray *trackingCodes; // @synthesize trackingCodes=_trackingCodes;
@property(readonly, nonatomic) unsigned int videoChainingDepth; // @synthesize videoChainingDepth=_videoChainingDepth;
@property(retain, nonatomic) FBMemSponsorshipData *sponsorship; // @synthesize sponsorship=_sponsorship;
@property(readonly, nonatomic) FBFeedVideoPlayerConfig *config; // @synthesize config=_config;
@property(readonly, nonatomic) FBMemVideo *video; // @synthesize video=_video;
@property(readonly, nonatomic) unsigned int videoPlayerOptions; // @synthesize videoPlayerOptions=_videoPlayerOptions;
@property(readonly, nonatomic) id <FBQueriedEntityFieldsProtocol> parent; // @synthesize parent=_parent;
@property(readonly, nonatomic) FBFeedComponentToolbox *toolbox; // @synthesize toolbox=_toolbox;
@property(readonly, copy, nonatomic) FBIntentAnalyticsInfo *analyticsInfo; // @synthesize analyticsInfo=_analyticsInfo;
- (void).cxx_destruct;

@end

