//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBFeedVideoActionHandler-Protocol.h"
#import "FBFeedVideoPlayerContainer-Protocol.h"

@class FBFeedComponentToolbox, FBFeedEventBus, FBFeedScrollingVideoController, FBLegacyVideoPlayerView, FBTimer, FBVideoAutoplayNuxController, FBVideoLoopListener, NSArray, NSString, UIView;
@protocol FBQueriedEntityFieldsProtocol, FBVideoPlaybackController;

@interface FBLegacyFeedVideoDisplayController : NSObject <FBFeedVideoPlayerContainer, FBFeedVideoActionHandler>
{
    UIView *_containerView;
    unsigned int _videoPlayerOptions;
    id <FBQueriedEntityFieldsProtocol> _parent;
    NSArray *_trackingCodes;
    FBFeedComponentToolbox *_toolbox;
    BOOL _isTracking;
    id <FBVideoPlaybackController> _videoPlaybackController;
    FBFeedEventBus *_eventBus;
    FBVideoLoopListener *_loopListener;
    unsigned int _layoutIdiom;
    FBVideoAutoplayNuxController *_autoplayNuxController;
    FBTimer *_autoplayNuxTimer;
    FBLegacyVideoPlayerView *_videoPlayerView;
    unsigned int _videoChainingDepth;
}

@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(readonly, nonatomic) unsigned int videoPlayerOptions; // @synthesize videoPlayerOptions=_videoPlayerOptions;
@property(nonatomic) unsigned int videoChainingDepth; // @synthesize videoChainingDepth=_videoChainingDepth;
@property(readonly, nonatomic) FBLegacyVideoPlayerView *videoPlayerView; // @synthesize videoPlayerView=_videoPlayerView;
- (void).cxx_destruct;
- (void)_autoplayNuxTimerCallback;
- (BOOL)_videoViewIsWithinThePortionOfTheScreenToAllowDisplay;
- (void)openURL:(id)arg1 fromStory:(id)arg2 attachment:(id)arg3 trackingCodes:(id)arg4 extras:(id)arg5;
- (BOOL)_videoIsFullscreen;
@property(readonly, nonatomic) unsigned int layoutIdiom;
- (void)stopPlayingVideo;
- (void)didDisplay;
- (id)videoContainerTrackingCodes;
- (id)memModel;
- (id)videoPlaybackController;
@property(readonly, nonatomic) FBFeedScrollingVideoController *feedScrollingVideoController;
- (BOOL)isInFullScreen;
- (void)performFullScreenActions;
- (void)enterFullScreenWithBlock:(CDUnknownBlockType)arg1;
- (void)stopContainerTrackingWithShouldInvalidate:(BOOL)arg1;
- (void)stopContainerTracking;
- (void)viewWillBeReusedByFeedVideoDisplayController:(id)arg1;
- (void)startContainerTracking;
- (void)dealloc;
- (id)initWithVideoPlaybackController:(id)arg1 containerView:(id)arg2 videoPlayerOptions:(unsigned int)arg3 parent:(id)arg4 eventBus:(id)arg5 trackingCodes:(id)arg6 toolbox:(id)arg7;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

