//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBVideoPlaybackLoggingDataProvider-Protocol.h"

@class NSArray, NSNumber, NSString;

@interface FBLegacyVideoPlayerLogger : NSObject <FBVideoPlaybackLoggingDataProvider>
{
    NSArray *_trackingCodes;
    NSString *_playerOrigin;
    NSString *_playerSubOrigin;
    unsigned int _chainingDepth;
    unsigned int _videoPlayReason;
    unsigned int _debugReason;
    NSString *_previousVideoID;
    BOOL _isSponsored;
    NSString *_channelEligibility;
    BOOL _isHLS;
    BOOL _isLiveStreaming;
    NSNumber *_isMonetizable;
    NSString *_channelAdsOpportunity;
    NSString *_channelSessionID;
    NSNumber *_channelDepthLevel;
    NSNumber *isMonetizable;
    NSString *channelAdsOpportunity;
    NSString *channelSessionID;
    NSNumber *channelDepthLevel;
    unsigned int _source;
}

@property(nonatomic) unsigned int source; // @synthesize source=_source;
@property(copy, nonatomic) NSNumber *channelDepthLevel; // @synthesize channelDepthLevel;
@property(copy, nonatomic) NSString *channelSessionID; // @synthesize channelSessionID;
@property(copy, nonatomic) NSString *channelAdsOpportunity; // @synthesize channelAdsOpportunity;
@property(copy, nonatomic) NSNumber *isMonetizable; // @synthesize isMonetizable;
@property(nonatomic) BOOL isLiveStreaming; // @synthesize isLiveStreaming=_isLiveStreaming;
@property(nonatomic) BOOL isHLS; // @synthesize isHLS=_isHLS;
@property(nonatomic) NSString *channelEligibility; // @synthesize channelEligibility=_channelEligibility;
@property(nonatomic) BOOL isSponsored; // @synthesize isSponsored=_isSponsored;
@property(copy, nonatomic) NSString *previousVideoID; // @synthesize previousVideoID=_previousVideoID;
@property(nonatomic) unsigned int debugReason; // @synthesize debugReason=_debugReason;
@property(copy, nonatomic) NSArray *trackingCodes; // @synthesize trackingCodes=_trackingCodes;
@property(nonatomic) unsigned int videoPlayReason; // @synthesize videoPlayReason=_videoPlayReason;
@property(copy, nonatomic) NSString *playerSubOrigin; // @synthesize playerSubOrigin=_playerSubOrigin;
@property(copy, nonatomic) NSString *playerOrigin; // @synthesize playerOrigin=_playerOrigin;
- (void).cxx_destruct;
@property(nonatomic) unsigned int playerSource;
- (void)logVideoViewPlayerAllocated:(id)arg1 videoInitializationTracker:(id)arg2;
- (void)logVideoView:(id)arg1 muteStateChanged:(BOOL)arg2;
- (void)logVideoViewDidDisplay:(id)arg1 initial:(BOOL)arg2 autoplayFailureReasons:(id)arg3;
- (void)logVideoView:(id)arg1 didReceiveInvalidTimePosition:(double)arg2 duringSeek:(BOOL)arg3;
- (void)logVideoViewMetadataReady:(id)arg1 videoInitializationTracker:(id)arg2;
- (void)logVideoViewDidSeek:(id)arg1 sourceTimePosition:(double)arg2;
- (void)logVideoViewRequestedPlaying:(id)arg1 waterfallCounter:(id)arg2 videoInitializationTracker:(id)arg3 concurrentDownloads:(unsigned int)arg4;
- (void)logVideoViewDidPlay:(id)arg1 waterfallCounter:(id)arg2 videoInitializationTracker:(id)arg3;
- (void)logVideoViewDidCancel:(id)arg1 waterfallCounter:(id)arg2 videoInitializationTracker:(id)arg3;
- (void)logVideoViewDidPauseByApp:(id)arg1 waterfallCounter:(id)arg2;
- (void)logVideoViewDidPauseByiOS:(id)arg1 waterfallCounter:(id)arg2;
- (void)logVideoView:(id)arg1 failedWithError:(id)arg2 playbackMode:(BOOL)arg3 waterfallCounter:(id)arg4 videoInitializationTracker:(id)arg5;
- (void)logVideoViewDidFinishPlaying:(id)arg1 waterfallCounter:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

