//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBNetworkerRequest.h"

@class NSString;

@interface FBLikeRequest : FBNetworkerRequest
{
    BOOL _unlike;
    NSString *_FBID;
    NSString *_tracking;
    unsigned int _contentCreationOrigin;
}

@property(nonatomic) unsigned int contentCreationOrigin; // @synthesize contentCreationOrigin=_contentCreationOrigin;
@property(nonatomic, getter=isUnlike) BOOL unlike; // @synthesize unlike=_unlike;
@property(copy, nonatomic) NSString *tracking; // @synthesize tracking=_tracking;
@property(copy, nonatomic) NSString *FBID; // @synthesize FBID=_FBID;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)networkRequest;
- (id)initWithFBID:(id)arg1 trackingCodes:(id)arg2 contentCreationOrigin:(unsigned int)arg3 callbackPerformer:(id)arg4;
- (id)initWithFBID:(id)arg1 trackingCodes:(id)arg2 callbackPerformer:(id)arg3;

@end

