//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBLigerBaseExperimentContext.h"

@interface FBLigerSchedulingExperimentContext : FBLigerBaseExperimentContext
{
    BOOL _schedulerEnabled;
    int _upperboundLowPri;
    int _upperboundNormalPri;
    int _upperboundHighPri;
}

+ (id)parameterConfigurations;
+ (id)experimentName;
@property(nonatomic) int upperboundHighPri; // @synthesize upperboundHighPri=_upperboundHighPri;
@property(nonatomic) int upperboundNormalPri; // @synthesize upperboundNormalPri=_upperboundNormalPri;
@property(nonatomic) int upperboundLowPri; // @synthesize upperboundLowPri=_upperboundLowPri;
@property(nonatomic) BOOL schedulerEnabled; // @synthesize schedulerEnabled=_schedulerEnabled;

@end

