//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBGLogSink-Protocol.h"

@interface FBLogGLogSink : NSObject <FBGLogSink>
{
}

- (void)logSoftErrorFromFile:(id)arg1 atLine:(unsigned long)arg2 inFunction:(id)arg3 withSeverity:(int)arg4 withMessage:(id)arg5;
- (void)logMessage:(id)arg1 withSeverity:(int)arg2;

@end

