//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBIdleDetector, FBUserSession;
@protocol FBServiceTransactionMutating;

@interface FBLWICallToActionGetDirectionsAddressValidator : NSObject
{
    FBUserSession *_userSession;
    id <FBServiceTransactionMutating> _geoCodingHandle;
    FBIdleDetector *_validationIdleDetector;
}

- (void).cxx_destruct;
- (void)_fetchGeoCodingWithAddress:(id)arg1 validationResultBlock:(CDUnknownBlockType)arg2;
- (void)validateAddress:(id)arg1 validationResultBlock:(CDUnknownBlockType)arg2;
- (id)initWithSession:(id)arg1;

@end

