//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBCoreShareActionDelegate-Protocol.h"

@class FBMailShareAction, MFMailComposeViewController, NSError, UIViewController;

@protocol FBMailShareActionDelegate <FBCoreShareActionDelegate>

@optional
- (void)mailShareAction:(FBMailShareAction *)arg1 didFinishWithMailComposeViewController:(MFMailComposeViewController *)arg2 result:(int)arg3 error:(NSError *)arg4;
- (UIViewController *)presentingViewController;
- (void)presentMailComposerViewController:(MFMailComposeViewController *)arg1;
@end

