//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBUserSession, MKMapSnapshotter, NSArray, NSString, UIColor;

@interface FBMapSnapshotRequest : NSObject
{
    BOOL _cancelled;
    NSArray *_routePoints;
    NSArray *_annotationPoints;
    float _lineWidth;
    UIColor *_lineColor;
    float _borderWidth;
    UIColor *_borderColor;
    unsigned int _mapType;
    MKMapSnapshotter *_snapshotter;
    FBUserSession *_session;
    CDUnknownBlockType _completion;
    NSString *_routeKey;
    struct CGSize _size;
    CDStruct_feeb6407 _region;
}

@property(readonly, nonatomic) NSString *routeKey; // @synthesize routeKey=_routeKey;
@property(getter=isCancelled) BOOL cancelled; // @synthesize cancelled=_cancelled;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(readonly, nonatomic) FBUserSession *session; // @synthesize session=_session;
@property(readonly, nonatomic) CDStruct_feeb6407 region; // @synthesize region=_region;
@property(readonly, nonatomic) struct CGSize size; // @synthesize size=_size;
@property(retain, nonatomic) MKMapSnapshotter *snapshotter; // @synthesize snapshotter=_snapshotter;
@property(nonatomic) unsigned int mapType; // @synthesize mapType=_mapType;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) float borderWidth; // @synthesize borderWidth=_borderWidth;
@property(retain, nonatomic) UIColor *lineColor; // @synthesize lineColor=_lineColor;
@property(nonatomic) float lineWidth; // @synthesize lineWidth=_lineWidth;
@property(copy, nonatomic) NSArray *annotationPoints; // @synthesize annotationPoints=_annotationPoints;
@property(copy, nonatomic) NSArray *routePoints; // @synthesize routePoints=_routePoints;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *diskCacheKey;
- (id)keyForCoordinatePoints:(id)arg1;
- (id)debugDescription;
- (void)callCompletionWithImage:(struct CGImage *)arg1 withRouteEndPoints:(id)arg2;
- (void)cancel;
- (void)stop;
- (id)initWithSize:(struct CGSize)arg1 region:(CDStruct_feeb6407)arg2 session:(id)arg3;

@end

