//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBMagicStoryTitleFormatters : NSObject
{
}

+ (id)_dayFormatter;
+ (id)_capitalizedDayStringForDate:(id)arg1;
+ (id)subtitleForStoryWithPhotoCount:(unsigned int)arg1 videoCount:(unsigned int)arg2;
+ (id)titleForStoryWithAssets:(id)arg1;
+ (id)titleForStoryWithLocationNameAndDate:(id)arg1 assets:(id)arg2;

@end

