//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBComposerPresentationHandler-Protocol.h"

@class FBComposerComposedResult, FBNavigationCoordinatorComposerPresentationHandler, NSString, UIViewController;
@protocol FBNavigationCoordinator;

@interface FBMagicStoriesPushBehindPresentationHandler : NSObject <FBComposerPresentationHandler>
{
    UIViewController *_vc;
    FBNavigationCoordinatorComposerPresentationHandler *_realHandler;
    id <FBNavigationCoordinator> _coordinator;
    FBComposerComposedResult *_composerComposedResult;
}

@property(retain, nonatomic) FBComposerComposedResult *composerComposedResult; // @synthesize composerComposedResult=_composerComposedResult;
- (void).cxx_destruct;
- (void)presentPopoverOverlayViewController:(id)arg1 popoverInfo:(id)arg2 options:(unsigned int)arg3 animated:(BOOL)arg4;
- (void)presentModalViewController:(id)arg1 fromViewController:(id)arg2 options:(unsigned int)arg3 animated:(BOOL)arg4 completionHandler:(CDUnknownBlockType)arg5;
- (void)dismissViewController:(id)arg1 animated:(BOOL)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)initWithNavigationCoordinator:(id)arg1 magicStoryVC:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

