//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBMemPageCardController.h"

#import "FBCardViewProvider-Protocol.h"
#import "FBPageGameAboutCellDelegate-Protocol.h"
#import "FBPhotoViewControllerDelegate-Protocol.h"
#import "FBSimpleMediaViewProviderDelegate-Protocol.h"

@class FBPageGameAboutCell, FBPhotoViewController, FBStoryAttachmentAlbumPhotoView, NSString, UIView;
@protocol FBPageCardProtocol;

@interface FBMemPageGameAboutCardController : FBMemPageCardController <FBPageGameAboutCellDelegate, FBSimpleMediaViewProviderDelegate, FBPhotoViewControllerDelegate, FBCardViewProvider>
{
    FBPageGameAboutCell *_cardCell;
    FBStoryAttachmentAlbumPhotoView *_photoView;
    FBPhotoViewController *_photoViewController;
}

- (void).cxx_destruct;
- (void)photoViewController:(id)arg1 didDismissPhoto:(id)arg2;
- (id)simpleMediaViewProvider:(id)arg1 viewOrLayerForPhoto:(id)arg2;
- (void)pageGameAboutCellDidTapScreenshot:(id)arg1 photo:(id)arg2 withPhotoArray:(id)arg3 photoView:(id)arg4 photoIndex:(unsigned int)arg5;
- (void)pageGameAboutCellDidSelectMoreInfo:(id)arg1;
- (void)pageGameAboutCell:(id)arg1 didTapURL:(id)arg2;
- (void)pageGameAboutCellDidChangeHeight:(id)arg1;
- (void)configureWithPage:(id)arg1;
@property(readonly, nonatomic) UIView<FBPageCardProtocol> *cardView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

