//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBRichTextView, NSAttributedString;

@interface FBMemPagePlacesBusinessInfoView : UIView
{
    FBRichTextView *_specialtyLabel;
    FBRichTextView *_cuisineLabel;
    FBRichTextView *_parkingLabel;
    FBRichTextView *_combinedLabel;
    struct CGSize _specialtySize;
    struct CGSize _parkingSize;
    struct CGSize _cuisineSize;
    struct CGSize _combinedSize;
    BOOL _shouldTakeSeparateLines;
    NSAttributedString *_specialtyText;
    NSAttributedString *_parkingText;
    NSAttributedString *_cuisineText;
}

@property(copy, nonatomic) NSAttributedString *cuisineText; // @synthesize cuisineText=_cuisineText;
@property(copy, nonatomic) NSAttributedString *parkingText; // @synthesize parkingText=_parkingText;
@property(copy, nonatomic) NSAttributedString *specialtyText; // @synthesize specialtyText=_specialtyText;
- (void).cxx_destruct;
- (id)_decorateString:(id)arg1;
- (void)_updateLabelDisplaySettingForWidth:(float)arg1;
- (void)_setupCombinedLabel;
- (void)_setupLabels;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)reload;
- (id)initWithFrame:(struct CGRect)arg1;

@end

