//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBMemPageTimelineHeaderBatchingQuery : NSObject
{
}

+ (id)graphQLQueryWithChildLocationsCount:(id)arg1 contextItemIconSize:(id)arg2 criticReviewsCount:(id)arg3 device:(id)arg4 enableImageShareAttachment:(id)arg5 entityType:(id)arg6 entityCardContextInfoCard:(id)arg7 entityCardContextRedirectedFromEntityId:(id)arg8 entityCardContextSurfaceInfoCard:(id)arg9 eventsNum:(id)arg10 eventsStartAfterTimestamp:(id)arg11 feedbackIncludeReactions:(id)arg12 feedbackIncludeSeenBy:(id)arg13 formatType:(id)arg14 friendRecommendationsCount:(id)arg15 genericAttachmentFallbackSquareImageDimension:(id)arg16 genericAttachmentLargeSquareImageDimension:(id)arg17 genericAttachmentPortraitImageHeight:(id)arg18 genericAttachmentPortraitImageWidth:(id)arg19 genericAttachmentSmallCoverImageHeight:(id)arg20 genericAttachmentSmallCoverImageWidth:(id)arg21 genericAttachmentSmallSquareImageDimension:(id)arg22 genericAttachmentTallCoverImageHeight:(id)arg23 genericAttachmentTallCoverImageWidth:(id)arg24 inChannelsExperiment:(id)arg25 includeAdminInfo:(id)arg26 includeNegativeFeedbackActions:(id)arg27 isOwned:(id)arg28 isZeroRated:(id)arg29 mediaType:(id)arg30 nonfriendRecommendationsCount:(id)arg31 numBylines:(id)arg32 pageID:(id)arg33 productsNum:(id)arg34 renderLocation:(id)arg35 renderActorInGutter:(id)arg36 scale:(id)arg37 shouldCheckStories:(id)arg38 shouldLoadStreamingImage:(id)arg39 sourceIdInfoCard:(id)arg40 storyCheckCount:(id)arg41 streamingImageResolution:(id)arg42 videoThumbnailSize:(id)arg43 videosCount:(id)arg44;

@end

