//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBModalAnimation-Protocol.h"

@class NSString, UIView;

@interface FBModalPushBackAnimation : NSObject <FBModalAnimation>
{
    UIView *_animatedView;
    struct CGAffineTransform _transform;
}

- (void).cxx_destruct;
- (id)_animatedViewForPresentation:(BOOL)arg1 inTransition:(id)arg2;
- (void)cleanUpAfterPresentation:(BOOL)arg1 inTransition:(id)arg2;
- (id)animatedViewsForPresentation:(BOOL)arg1 inTransition:(id)arg2;
- (void)animatePresentation:(BOOL)arg1 alongsideTransition:(id)arg2;
- (void)prepareForPresentation:(BOOL)arg1 inTransition:(id)arg2;
- (id)initWithScale:(float)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

