//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBMStickerTrayConfigFetcherDelegate-Protocol.h"
#import "FBMStickerTrayConfigSenderDelegate-Protocol.h"

@class FBMStickerManager, FBMStickerPackDownloaderQueue, FBMStickerTrayConfigFetcher, FBMStickerTrayConfigSender, FBMStickerTrayConfigStore, FBMStickerTrayConfiguration, FBMTrayStickerPacksMerger, NSString;
@protocol FBMStickerTrayConfigSyncListener;

@interface FBMStickerTrayConfigSyncOperation : NSObject <FBMStickerTrayConfigFetcherDelegate, FBMStickerTrayConfigSenderDelegate>
{
    FBMStickerManager *_stickerManager;
    FBMStickerPackDownloaderQueue *_downloaderQueue;
    CDUnknownBlockType _downloaderProvider;
    FBMStickerTrayConfigStore *_stickerTrayConfigStore;
    CDUnknownBlockType _stickerTrayConfigFetcherProvider;
    CDUnknownBlockType _stickerTrayConfigSenderProvider;
    FBMStickerTrayConfigFetcher *_stickerTrayConfigFetcher;
    FBMStickerTrayConfigSender *_stickerTrayConfigSender;
    FBMTrayStickerPacksMerger *_trayStickerPacksMerger;
    FBMStickerTrayConfiguration *_trayConfigurationBeforeSync;
    id <FBMStickerTrayConfigSyncListener> _delegate;
    unsigned int _type;
    unsigned int _state;
}

@property(readonly, nonatomic) unsigned int state; // @synthesize state=_state;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(nonatomic) __weak id <FBMStickerTrayConfigSyncListener> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_clearSendRequest;
- (void)_clearFetchRequest;
- (void)_updateStickerTrayWithRemoteConfig:(id)arg1;
- (void)_postTrayConfigIfNeeded:(id)arg1;
- (void)_writeStickerTrayConfigUpdateToServer:(id)arg1;
- (void)_fetchStickerTrayConfig;
- (void)_queueStickerPacksForDownload:(id)arg1;
- (void)_resumePackDownloads;
- (void)stickerTrayConfigSender:(id)arg1 didFailWithError:(id)arg2;
- (void)stickerTrayConfigSender:(id)arg1 didSendStickerTrayConfig:(id)arg2;
- (void)stickerTrayConfigFetcher:(id)arg1 didFailWithError:(id)arg2;
- (void)stickerTrayConfigFetcher:(id)arg1 didFetchStickerTrayConfig:(id)arg2;
- (id)initWithLayoutIdiom:(unsigned int)arg1 session:(id)arg2;
- (id)initWithStickerManager:(id)arg1 stickerPackDownloaderQueue:(id)arg2 stickerPackDownloaderProvider:(CDUnknownBlockType)arg3 stickerTrayConfigFetcherProvider:(CDUnknownBlockType)arg4 stickerTrayConfigSenderProvider:(CDUnknownBlockType)arg5 trayStickerPacksMerger:(id)arg6 stickerTrayConfigStore:(id)arg7;
- (void)cancel;
- (void)start;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

