//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class FBMStoreStickerPack, FBNetworkImageView, UIButton, UIImageView, UILabel, UIProgressView;

@interface FBMStickerPackCell : UITableViewCell
{
    UIProgressView *_progressBar;
    UIImageView *_downloadedIcon;
    UIImageView *_separatorImageView;
    FBMStoreStickerPack *_stickerPack;
    UIButton *_downloadButton;
    FBNetworkImageView *_stickerPackThumbnailView;
    UILabel *_stickerPackTitleView;
    UILabel *_stickerPackSubtitleView;
}

@property(retain, nonatomic) UILabel *stickerPackSubtitleView; // @synthesize stickerPackSubtitleView=_stickerPackSubtitleView;
@property(retain, nonatomic) UILabel *stickerPackTitleView; // @synthesize stickerPackTitleView=_stickerPackTitleView;
@property(retain, nonatomic) FBNetworkImageView *stickerPackThumbnailView; // @synthesize stickerPackThumbnailView=_stickerPackThumbnailView;
@property(readonly, nonatomic) UIImageView *downloadedIcon; // @synthesize downloadedIcon=_downloadedIcon;
@property(retain, nonatomic) UIButton *downloadButton; // @synthesize downloadButton=_downloadButton;
@property(readonly, nonatomic) UIProgressView *progressBar; // @synthesize progressBar=_progressBar;
@property(retain, nonatomic) FBMStoreStickerPack *stickerPack; // @synthesize stickerPack=_stickerPack;
- (void).cxx_destruct;
- (void)_addSeparatorIfNeeded;
- (float)_iconOriginX;
- (float)_downloadOriginX;
- (void)layoutSubviews;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2 layoutIdiom:(unsigned int)arg3 imageDownloader:(id)arg4;

@end

