//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBMusicPreviewViewFocusListener-Protocol.h"
#import "FBMusicPreviewViewListener-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class FBMusicSong, NSString, NSURL, UIView;
@protocol FBMusicPlayer, FBMusicPreviewViewListener;

@interface FBMusicPreviewActionSheetPresenter : NSObject <UIActionSheetDelegate, FBMusicPreviewViewListener, FBMusicPreviewViewFocusListener>
{
    id <FBMusicPlayer> _player;
    id <FBMusicPreviewViewListener> _viewListener;
    FBMusicSong *_song;
    UIView *_view;
    int _nativeButtonIndex;
    NSURL *_nativeButtonURL;
    BOOL _isInstall;
}

- (void).cxx_destruct;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)albumArtTapped;
- (void)focusedOnViewForSong:(id)arg1;
- (id)init;
- (id)initWithView:(id)arg1 player:(id)arg2 viewListener:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

