//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBNativeArticleEngagementActionFactory : NSObject
{
}

+ (id)engagementActionControllerWithType:(int)arg1 session:(id)arg2 metrics:(id)arg3 target:(id)arg4 trackingCodes:(id)arg5;

@end

