//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@class NSString, NSURL, NSURLRequest, UIScrollView, UIView;
@protocol FBNativeArticleWebViewDelegate;

@protocol FBNativeArticleWebViewProtocol
@property(readonly, nonatomic) UIView *view;
@property(readonly, nonatomic) UIScrollView *scrollView;
@property(nonatomic) __weak id <FBNativeArticleWebViewDelegate> delegate;
- (void)evaluateJavaScript:(NSString *)arg1 completionHandler:(void (^)(id, NSError *))arg2;
- (BOOL)isLoading;
- (void)stopLoading;
- (void)goBack;
- (void)goForward;
- (BOOL)canGoBack;
- (BOOL)canGoForward;
- (void)loadHTMLString:(NSString *)arg1 baseURL:(NSURL *)arg2;
- (void)loadRequest:(NSURLRequest *)arg1;
- (id)initWithFrame:(struct CGRect)arg1 scalesPageToFit:(BOOL)arg2 suppressesIncrementalRendering:(BOOL)arg3;
@end

