//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSSet;
@protocol FBNativeArticlePreloadHandlerDelegate, OS_dispatch_queue;

@interface FBNativeArticlePreloadHandler : NSObject
{
    id <FBNativeArticlePreloadHandlerDelegate> _delegate;
    NSSet *_blockControllersInPreloadViewport;
    NSObject<OS_dispatch_queue> *_preloadQueue;
    struct CGRect _preloadableViewport;
}

@property(nonatomic) struct CGRect preloadableViewport; // @synthesize preloadableViewport=_preloadableViewport;
- (void).cxx_destruct;
- (void)_notifyBlockControllersExitingPreloadViewport:(id)arg1;
- (void)_notifyBlockControllersEnteringPreloadViewport:(id)arg1;
- (id)initWithDelegate:(id)arg1 queue:(id)arg2;

@end

