//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBInvalidating-Protocol.h"

@class FBAppModuleManager, FBNativeThirdPartyURLHandler, FBNavigationController, FBUserSession, NSString;
@protocol FBAppSessionController, FBNavigationCoordinator;

@interface FBNavigationViewCoordinatorBookmarkHandler : NSObject <FBInvalidating>
{
    BOOL _invalidated;
    FBUserSession *_session;
    id <FBNavigationCoordinator> _navigationCoordinator;
    FBNavigationController *_navigationController;
    CDUnknownBlockType _rootViewControllerProvider;
    id <FBAppSessionController> _appSessionController;
    FBAppModuleManager *_appModuleManager;
    FBNativeThirdPartyURLHandler *_nativeThirdPartyURLHandler;
    CDUnknownBlockType _fallbackHandler;
    CDUnknownBlockType _completionHandler;
}

- (void).cxx_destruct;
- (BOOL)_shouldRedirectFromBookmarkForMenuItem:(id)arg1;
- (void)_showMenuItem:(id)arg1 fromAppSectionManager:(BOOL)arg2;
- (void)handleMenuItem:(id)arg1 fromAppSectionManager:(BOOL)arg2;
- (BOOL)shouldHandleChangeToMenuItem:(id)arg1;
- (void)_bookmarkSelectionChangeNotification:(id)arg1;
@property(readonly, nonatomic, getter=isValid) BOOL valid;
- (void)invalidate;
- (void)dealloc;
- (id)initWithSession:(id)arg1 navigationCoordinator:(id)arg2 navigationController:(id)arg3 appSessionController:(id)arg4 appModuleManager:(id)arg5 rootViewControllerProvider:(CDUnknownBlockType)arg6 fallbackHandler:(CDUnknownBlockType)arg7 presentedBookmarkCompletion:(CDUnknownBlockType)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

