//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "FBWebViewRightBarButtonItemView-Protocol.h"

@class FBBouncyPressButton, FBNavigationBarProfileView, NSString, UIButton;
@protocol FBNavigationBarCurrentUserViewDelegate;

@interface FBNavigationBarCurrentUserView : UIView <FBWebViewRightBarButtonItemView>
{
    FBNavigationBarProfileView *_profileView;
    FBBouncyPressButton *_menuButton;
    UIButton *_chatBarButtonItem;
    UIView *_divider;
    BOOL _displayDivebar;
    id <FBNavigationBarCurrentUserViewDelegate> _delegate;
}

@property(nonatomic) __weak id <FBNavigationBarCurrentUserViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) BOOL displayDivebar; // @synthesize displayDivebar=_displayDivebar;
@property(readonly, nonatomic) UIButton *menuButton; // @synthesize menuButton=_menuButton;
- (void).cxx_destruct;
- (void)_didTapChatButton:(id)arg1;
- (void)_didTapMenuButton:(id)arg1;
- (void)_didTapProfileView:(id)arg1;
- (BOOL)shouldShowForWebViewControllerPolicyInternal;
- (void)setThumbnailURL:(id)arg1;
- (void)setName:(id)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (float)profileViewAvailableWidth;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 session:(id)arg2 displayDivebar:(BOOL)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

