//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBValueObject.h"

#import "FBFIGConfig-Protocol.h"

@class NSString, UIColor, UIFont;

@interface FBNavigationBarTitleControlConfig : FBValueObject <FBFIGConfig>
{
    BOOL _hideArrow;
    NSString *_title;
    UIFont *_titleFont;
    UIColor *_titleTextColor;
    int _titleLineBreakMode;
    NSString *_subtitle;
    UIFont *_subtitleFont;
    UIColor *_subtitleTextColor;
    int _subtitleLineBreakMode;
    unsigned int _arrowShading;
    UIColor *_backgroundColor;
}

+ (id)newWithTitle:(id)arg1 titleFont:(id)arg2 titleTextColor:(id)arg3 titleLineBreakMode:(int)arg4 subtitle:(id)arg5 subtitleFont:(id)arg6 subtitleTextColor:(id)arg7 subtitleLineBreakMode:(int)arg8 arrowShading:(unsigned int)arg9 hideArrow:(BOOL)arg10 backgroundColor:(id)arg11;
@property(readonly, copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(readonly, nonatomic) BOOL hideArrow; // @synthesize hideArrow=_hideArrow;
@property(readonly, nonatomic) unsigned int arrowShading; // @synthesize arrowShading=_arrowShading;
@property(readonly, nonatomic) int subtitleLineBreakMode; // @synthesize subtitleLineBreakMode=_subtitleLineBreakMode;
@property(readonly, copy, nonatomic) UIColor *subtitleTextColor; // @synthesize subtitleTextColor=_subtitleTextColor;
@property(readonly, copy, nonatomic) UIFont *subtitleFont; // @synthesize subtitleFont=_subtitleFont;
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, nonatomic) int titleLineBreakMode; // @synthesize titleLineBreakMode=_titleLineBreakMode;
@property(readonly, copy, nonatomic) UIColor *titleTextColor; // @synthesize titleTextColor=_titleTextColor;
@property(readonly, copy, nonatomic) UIFont *titleFont; // @synthesize titleFont=_titleFont;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)_initWithTitle:(id)arg1 titleFont:(id)arg2 titleTextColor:(id)arg3 titleLineBreakMode:(int)arg4 subtitle:(id)arg5 subtitleFont:(id)arg6 subtitleTextColor:(id)arg7 subtitleLineBreakMode:(int)arg8 arrowShading:(unsigned int)arg9 hideArrow:(BOOL)arg10 backgroundColor:(id)arg11;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

