//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "MKMapViewDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class FBNearbyPlacesLoggerHelper, FBNearbyPlacesMapView, FBNearbyPlacesResultListModel, NSArray, NSString;
@protocol FBNearbyPlacesMapViewControllerDelegate;

@interface FBNearbyPlacesMapViewController : UIViewController <MKMapViewDelegate, UICollectionViewDelegate, UICollectionViewDataSource>
{
    FBNearbyPlacesResultListModel *_model;
    FBNearbyPlacesMapView *_nearbyPlacesMapView;
    unsigned int _currentIndex;
    BOOL _isUserInteractingWithMap;
    BOOL _didUserDragMap;
    BOOL _isInitFlow;
    id <FBNearbyPlacesMapViewControllerDelegate> _delegate;
    NSArray *_annotations;
    FBNearbyPlacesLoggerHelper *_nearbyPlacesLoggerHelper;
}

@property(retain, nonatomic) FBNearbyPlacesLoggerHelper *nearbyPlacesLoggerHelper; // @synthesize nearbyPlacesLoggerHelper=_nearbyPlacesLoggerHelper;
@property(copy, nonatomic) NSArray *annotations; // @synthesize annotations=_annotations;
@property(nonatomic) __weak id <FBNearbyPlacesMapViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)mapView:(id)arg1 regionDidChangeAnimated:(BOOL)arg2;
- (void)mapView:(id)arg1 regionWillChangeAnimated:(BOOL)arg2;
- (void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (int)collectionView:(id)arg1 numberOfItemsInSection:(int)arg2;
- (void)_centerPinIfNotVisibleOnMap:(id)arg1;
- (void)_updateDidUserInteractWithMapForRegionChange;
- (void)_updateCurrentSelected:(unsigned int)arg1;
- (void)_didTapSearchThisAreaButton;
- (void)_didTapUserLocation;
- (void)_addMapAnnotations;
- (BOOL)_isAnnotationVisibleToUser:(id)arg1;
- (CDStruct_feeb6407)_userVisibleMapRect;
- (id)_expandedMapRegion:(id)arg1;
- (void)_layoutMapRegionWithModel;
- (BOOL)_isUserCloseToResult;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)arg1;
- (void)clearDataForFetching;
- (void)updateMapViewWithModel;
- (void)updateWithModel:(id)arg1;
- (id)initWithModel:(id)arg1 loggerHelper:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

