//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class FBNearbyPlacesTypeaheadIconView, FBUserSession, UIImage, UIImageView, UILabel;

@interface FBNearbyPlacesCategoryMenuItemView : UIButton
{
    FBUserSession *_session;
    UIImageView *_loadingView;
    UILabel *_categoryLabel;
    FBNearbyPlacesTypeaheadIconView *_iconView;
    UIImage *_defaultImage;
}

@property(retain, nonatomic) UIImage *defaultImage; // @synthesize defaultImage=_defaultImage;
- (void).cxx_destruct;
- (id)_circleImageWithColor:(id)arg1 imageSize:(float)arg2;
- (void)layoutSubviews;
- (void)updateViewWithCategory:(id)arg1;
- (void)updateViewState:(int)arg1;
- (id)initWithSession:(id)arg1;

@end

