//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBNearbyPlacesBaseLogger.h"

@class NSMutableArray, NSMutableSet, NSString;
@protocol FBNearbyPlacesRecommendationsLoggerDatasource;

@interface FBNearbyPlacesRecommendationsLogger : FBNearbyPlacesBaseLogger
{
    unsigned int _maxSeenResultIndex;
    NSMutableArray *_seenHereCardIDs;
    unsigned int _maxSeenHereCardIndex;
    BOOL _hasLoggedViewOpened;
    NSString *_clientSessionID;
    NSString *_searchResultListID;
    NSMutableSet *_alreadySentEvents;
    id <FBNearbyPlacesRecommendationsLoggerDatasource> _datasource;
    NSString *_hereCardResponseID;
    NSMutableArray *_seenResultIDs;
}

+ (id)filterMaskAsArray:(unsigned int)arg1;
+ (id)sortOptionAsString:(unsigned int)arg1;
+ (id)stringForResultCellTapAction:(unsigned int)arg1;
+ (id)stringForResultCellType:(unsigned int)arg1;
+ (id)stringForResultListSearchType:(unsigned int)arg1;
@property(retain, nonatomic) NSMutableArray *seenResultIDs; // @synthesize seenResultIDs=_seenResultIDs;
@property(copy, nonatomic) NSString *hereCardResponseID; // @synthesize hereCardResponseID=_hereCardResponseID;
@property(readonly, nonatomic) BOOL hasLoggedViewOpened; // @synthesize hasLoggedViewOpened=_hasLoggedViewOpened;
@property(nonatomic) __weak id <FBNearbyPlacesRecommendationsLoggerDatasource> datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) NSMutableSet *alreadySentEvents; // @synthesize alreadySentEvents=_alreadySentEvents;
@property(copy, nonatomic) NSString *searchResultListID; // @synthesize searchResultListID=_searchResultListID;
@property(copy, nonatomic) NSString *clientSessionID; // @synthesize clientSessionID=_clientSessionID;
- (void).cxx_destruct;
- (id)_nonNilClientSessionID;
- (id)_userHasLocationServiceString;
- (id)_commonExtras;
@property(readonly, copy, nonatomic) NSString *analyticsModule;
- (void)logMapResultsViewControllerBackButtonTapped;
- (void)logMapPlaceResultCardWasTappedWithPlaceID:(id)arg1 overallRank:(unsigned int)arg2 resultsCount:(unsigned int)arg3;
- (void)logMapPlaceResultCardWasSwipedWithPlaceID:(id)arg1 overallRank:(unsigned int)arg2 resultsCount:(unsigned int)arg3;
- (void)logMapResultPinWasTappedWithPlaceID:(id)arg1;
- (void)logNoResultsViewSeeMapButtonTapped;
- (void)logViewMapButtonWasToggledWithWillDisplayMap:(BOOL)arg1;
- (void)logSearchThisAreaButtonWasTapped;
- (void)logSearchThisAreaButtonIsVisible;
- (void)_logHereCardEvent:(id)arg1 cellType:(unsigned int)arg2 withPageID:(id)arg3 cardRank:(unsigned int)arg4 cardCount:(unsigned int)arg5 addOnExtras:(id)arg6;
- (void)_logHereCardHugeCellTapAction:(unsigned int)arg1 withPage:(id)arg2 cardRank:(unsigned int)arg3 cardCount:(unsigned int)arg4 addOnExtras:(id)arg5;
- (void)logHereCardHugeCellTapAction:(unsigned int)arg1 withPage:(id)arg2 cardRank:(unsigned int)arg3 cardCount:(unsigned int)arg4 photoIndex:(unsigned int)arg5 photoResultsCount:(unsigned int)arg6;
- (void)logHereCardHugeCellTapAction:(unsigned int)arg1 withPage:(id)arg2 cardRank:(unsigned int)arg3 cardCount:(unsigned int)arg4;
- (void)logHereCardEvent:(id)arg1 cellType:(unsigned int)arg2 withPage:(id)arg3 cardRank:(unsigned int)arg4 cardCount:(unsigned int)arg5;
- (void)logSortFilterButtonTap:(id)arg1 toggleState:(BOOL)arg2 filterMask:(unsigned int)arg3 sortType:(unsigned int)arg4;
- (void)logSessionDidEnd;
- (void)logOpenedView;
- (void)logScrolledOldCellHereCards:(id)arg1 toPlaceIndex:(unsigned int)arg2;
- (void)logScrolledHugeCellHereCards;
- (void)logScrollResultsWithResultsSeenIDs:(id)arg1 lastIndexSeen:(unsigned int)arg2;
- (void)logScrolledResults;
- (void)logTappedClusterToZoomIn;
- (void)logTappedClusterToOpenTableWithClusterAnnotation:(id)arg1;
- (void)logViewResultsListOnMap:(id)arg1;
- (void)logResultsListReceivedResults:(id)arg1 fromCache:(BOOL)arg2;
- (void)logOldFlowViewResultsList:(id)arg1;
- (void)logViewResultsList:(id)arg1;
- (void)_logTableListResultTappedWithPageFBID:(id)arg1 atRow:(unsigned int)arg2 resultsCount:(unsigned int)arg3 listSource:(unsigned int)arg4 hasFriendContext:(BOOL)arg5 aboveTheFold:(BOOL)arg6 sortApplied:(BOOL)arg7 cellType:(unsigned int)arg8 tapAction:(unsigned int)arg9 addOnExtras:(id)arg10;
- (void)logTableListResultTappedWithPageFBID:(id)arg1 atRow:(unsigned int)arg2 resultsCount:(unsigned int)arg3 listSource:(unsigned int)arg4 hasFriendContext:(BOOL)arg5 aboveTheFold:(BOOL)arg6 sortApplied:(BOOL)arg7 cellType:(unsigned int)arg8 tapAction:(unsigned int)arg9 photoIndex:(unsigned int)arg10 photoResultsCount:(unsigned int)arg11;
- (void)logTableListResultTappedWithPageFBID:(id)arg1 atRow:(unsigned int)arg2 resultsCount:(unsigned int)arg3 listSource:(unsigned int)arg4 hasFriendContext:(BOOL)arg5 aboveTheFold:(BOOL)arg6 sortApplied:(BOOL)arg7 cellType:(unsigned int)arg8 tapAction:(unsigned int)arg9;
- (void)resetSeenHereCardIDs;
- (BOOL)hasSeenHereCardID:(id)arg1;
- (void)addSeenHereCardID:(id)arg1 withRowIndex:(unsigned int)arg2;
- (void)resetSeenResultIDs;
- (BOOL)hasSeenResultID:(id)arg1;
- (void)addSeenResultID:(id)arg1 withRowIndex:(unsigned int)arg2;
- (id)initWithEntryPoint:(unsigned int)arg1;
- (id)init;

@end

