//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBDuplicatedFacebookAPIProperties-Protocol.h"
#import "FBHttpRequest-Protocol.h"
#import "FBHttpRequestDelegate-Protocol.h"
#import "FBResponseHandlerDelegate-Protocol.h"

@class FBRequesterConfiguration, FBScenePath, FBUDPPrimer, NSString, NSURLRequest;
@protocol FBCallPath, FBNetworkTransactionSurfacing, FBNetworkerRequestDelegate, FBNetworkerRequestStatus, FBPerforming, FBRequest, FBResponseHandling, OS_dispatch_queue;

@interface FBNetworkerRequest : NSObject <FBResponseHandlerDelegate, FBHttpRequest, FBHttpRequestDelegate, FBDuplicatedFacebookAPIProperties>
{
    struct {
        char delegateDidStart;
        char delegateDidSucceed;
        char delegateDidFail;
        char delegateDidCancel;
        char delegateDidUpdateDownloadProgress;
        char delegateDidUpdateUploadProgress;
        char delegateDidUploadData;
        char delegateDidReceiveData;
        char delegateDidReceiveResponse;
        char delegateWillRetry;
    } _flags;
    NSObject<OS_dispatch_queue> *_queue;
    id <FBRequest> _generatedRequest;
    NSURLRequest *_generatedUrlRequest;
    BOOL _generated;
    id <FBResponseHandling> _responseHandler;
    id <FBNetworkerRequestStatus> _mostRecentSuccessStatus;
    BOOL _didDeliverData;
    BOOL _finished;
    BOOL _cancelled;
    FBNetworkerRequest *_selfDeallocGuard;
    id <FBResponseHandling> _responseHandlerDeallocGuard;
    BOOL _includeAccessToken;
    BOOL _requestAsLoggedInAccount;
    BOOL _enableUDPPriming;
    BOOL _allowRetry;
    BOOL _silentLoading;
    BOOL _disableCustomProtocols;
    id <FBCallPath> _callPath;
    NSString *_actorFBID;
    NSString *_accessTokenOverride_DEPRECATED;
    FBRequesterConfiguration *_requesterConfiguration;
    FBScenePath *_scenePath;
    int _priority;
    unsigned int _priorityOrder;
    id <FBNetworkerRequestDelegate> _delegate;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failureBlock;
    id <FBPerforming> _callbackPerformer;
    NSString *_name;
    NSString *_analyticsUUID;
    FBUDPPrimer *_udpPrimer;
    unsigned int _hardTimeout;
    id <FBNetworkTransactionSurfacing> _currentTransactionToken;
    CDUnknownBlockType _urlRequestGenerator;
}

+ (void)setDefaultConfiguration:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType urlRequestGenerator; // @synthesize urlRequestGenerator=_urlRequestGenerator;
@property(retain, nonatomic) id <FBNetworkTransactionSurfacing> currentTransactionToken; // @synthesize currentTransactionToken=_currentTransactionToken;
@property(nonatomic) unsigned int hardTimeout; // @synthesize hardTimeout=_hardTimeout;
@property(retain, nonatomic) FBUDPPrimer *udpPrimer; // @synthesize udpPrimer=_udpPrimer;
@property(readonly, copy, nonatomic) NSString *analyticsUUID; // @synthesize analyticsUUID=_analyticsUUID;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(nonatomic) BOOL disableCustomProtocols; // @synthesize disableCustomProtocols=_disableCustomProtocols;
@property(nonatomic) BOOL silentLoading; // @synthesize silentLoading=_silentLoading;
@property(nonatomic) BOOL allowRetry; // @synthesize allowRetry=_allowRetry;
@property(retain, nonatomic) id <FBPerforming> callbackPerformer; // @synthesize callbackPerformer=_callbackPerformer;
@property(copy, nonatomic) CDUnknownBlockType failureBlock; // @synthesize failureBlock=_failureBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(retain, nonatomic) id <FBNetworkerRequestDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned int priorityOrder; // @synthesize priorityOrder=_priorityOrder;
@property(nonatomic) int priority; // @synthesize priority=_priority;
@property(retain, nonatomic) FBScenePath *scenePath; // @synthesize scenePath=_scenePath;
@property(retain, nonatomic) FBRequesterConfiguration *requesterConfiguration; // @synthesize requesterConfiguration=_requesterConfiguration;
@property(nonatomic) BOOL enableUDPPriming; // @synthesize enableUDPPriming=_enableUDPPriming;
@property(nonatomic) BOOL requestAsLoggedInAccount; // @synthesize requestAsLoggedInAccount=_requestAsLoggedInAccount;
@property(nonatomic) BOOL includeAccessToken; // @synthesize includeAccessToken=_includeAccessToken;
@property(copy, nonatomic) NSString *accessTokenOverride_DEPRECATED; // @synthesize accessTokenOverride_DEPRECATED=_accessTokenOverride_DEPRECATED;
@property(copy, nonatomic) NSString *actorFBID; // @synthesize actorFBID=_actorFBID;
@property(retain, nonatomic) id <FBCallPath> callPath; // @synthesize callPath=_callPath;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)_performCallbackBlock:(CDUnknownBlockType)arg1 andCleanup:(BOOL)arg2;
- (void)responseHandler:(id)arg1 didFailWithError:(id)arg2;
- (void)responseHandler:(id)arg1 didHandleResponse:(id)arg2 finalResponse:(BOOL)arg3;
- (void)networker:(id)arg1 didReceiveHeadersWithStatus:(id)arg2;
- (void)networker:(id)arg1 didUploadDataWithStatus:(id)arg2;
- (void)networker:(id)arg1 didDownloadData:(id)arg2 status:(id)arg3;
- (void)networker:(id)arg1 didCancelWithStatus:(id)arg2;
- (void)networker:(id)arg1 willRetryWithError:(id)arg2 status:(id)arg3;
- (void)networker:(id)arg1 didFailWithError:(id)arg2 status:(id)arg3;
- (void)networker:(id)arg1 didFinishWithStatus:(id)arg2;
- (void)networker:(id)arg1 didStartRequestWithStatus:(id)arg2;
@property(readonly, copy, nonatomic) NSString *logName;
@property(readonly, copy, nonatomic) NSString *logNamespace;
@property(readonly, nonatomic) NSURLRequest *request;
- (void)cancel;
- (id)description;
- (id)networkRequest;
- (id)callbackQueue;
- (id)initWithCallbackPerformer:(id)arg1 queue:(id)arg2;
- (id)initWithCallbackPerformer:(id)arg1;
- (id)init;

@end

