//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBNotificationsNavigationFactory : NSObject
{
}

+ (id)_boostPostURLFromAttachment:(id)arg1 session:(id)arg2 fallback:(id)arg3;
+ (id)_pagePostPermalinkURLFromAttachment:(id)arg1 fallback:(id)arg2 notificationLoggingContext:(id)arg3;
+ (id)intentTargetForNotificationStory:(id)arg1 session:(id)arg2 notificationLoggingContext:(id)arg3;
+ (id)intentTargetForNotificationStory:(id)arg1 session:(id)arg2 viewerFBID:(id)arg3 notificationLoggingContext:(id)arg4;

@end

