//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBGraphQLPagedDownloadRequest.h"

@class NSArray, NSString;

@interface FBNotificationsDownloadRequest : FBGraphQLPagedDownloadRequest
{
    unsigned int _limit;
    NSString *_environment;
    NSString *_source;
    NSArray *_notificationDeltaCacheIDs;
    BOOL _useLiteQuery;
}

- (void).cxx_destruct;
- (BOOL)cachedQueryEnabled;
- (id)newQueryWithCursor:(id)arg1;
- (id)initWithTargetID:(id)arg1 callbackPerformer:(id)arg2 limit:(int)arg3 environment:(id)arg4 source:(id)arg5 notificationDeltaCacheIDs:(id)arg6 useLiteQuery:(BOOL)arg7;

@end

