//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBScenePathContext.h"

@class NSMapTable;

@interface FBNumericalScenePathContext : FBScenePathContext
{
    NSMapTable *_indexToPath;
    NSMapTable *_indexToHolder;
    struct Mutex _lock;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)_holderForIndex:(unsigned int)arg1;
- (void)invalidateIndex:(unsigned int)arg1;
- (void)updateActiveIndex:(unsigned int)arg1;
- (id)pathForIndex:(unsigned int)arg1;
- (id)initWithRootView:(id)arg1 delegate:(id)arg2;

@end

