//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class FBNuxCoordinator, FBUserSession, NSArray;

@interface FBNuxQPPromotionListViewController : UITableViewController
{
    FBNuxCoordinator *_nuxCoordinator;
    NSArray *_nuxPresenters;
    FBUserSession *_session;
}

@property(nonatomic) __weak FBUserSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (id)_promotionForIndexPath:(id)arg1;
- (id)_promotionsForSection:(int)arg1;
- (id)_nuxPresentersFromConfigurationProfile:(id)arg1;
- (id)analyticsModule;
- (BOOL)fb_showNavigationJewels;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(int)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (int)numberOfSectionsInTableView:(id)arg1;
- (BOOL)fb_showAuxiliaryViewController;
- (id)initWithSession:(id)arg1;
- (id)init;
- (int)preferredInterfaceOrientationForPresentation;
- (unsigned int)supportedInterfaceOrientations;

@end

