//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBMediaUploadItem.h"

@class NSString;
@protocol FBPhotoAttachmentProtocol;

@interface FBOpenGraphMediaAttachmentUploadItem : FBMediaUploadItem
{
    id <FBPhotoAttachmentProtocol> _imageAttachment;
}

- (void).cxx_destruct;
- (id)publishedMediaTags;
- (id)nextUploadRequestFromRequestParameter:(id)arg1;
- (id)apiParametersWithProcessedContext:(id)arg1;
- (void)processMediaItemWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)mediaIDFromResult:(id)arg1;
- (id)thumbnailImage;
- (int)mediaUploadItemType;
@property(readonly, copy, nonatomic) NSString *assetID;
- (id)init;
- (id)initWithImageAttachment:(id)arg1 publisherData:(id)arg2 logger:(id)arg3 experimentManager:(id)arg4 networkDispatcher:(id)arg5;

@end

