//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString;

@interface FBPageAccountInfo : FBValueObject <NSCopying, NSCoding>
{
    NSString *_pageName;
    unsigned int _permissions;
}

@property(readonly, nonatomic) unsigned int permissions; // @synthesize permissions=_permissions;
@property(readonly, copy, nonatomic) NSString *pageName; // @synthesize pageName=_pageName;
- (void).cxx_destruct;
- (id)initWithPageName:(id)arg1 permissions:(unsigned int)arg2;

@end

