//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBPageAdminPostPromoteRequestFactory : NSObject
{
}

+ (id)_campaignStatusforRunStatus:(unsigned int)arg1;
+ (unsigned int)defaultHardTimeout;
+ (id)createSaveStickySettingsRequestWithPageID:(id)arg1 budget:(id)arg2 currency:(id)arg3 adAccountID:(id)arg4 campaignLength:(id)arg5 audience:(id)arg6 targeting:(id)arg7 actorFBID:(id)arg8;
+ (id)createAdminInfoRequestsWithPageID:(id)arg1 storyID:(id)arg2 stickyBudget:(id)arg3 adAccountID:(id)arg4 audience:(id)arg5 targeting:(id)arg6 campaignLength:(id)arg7 maxBudgetRecommendationsCount:(unsigned int)arg8 actorFBID:(id)arg9;
+ (id)createBoostedPostInitialRequestsWithPageID:(id)arg1 storyID:(id)arg2 maxBudgetRecommendationsCount:(unsigned int)arg3 audience:(id)arg4 actorFBID:(id)arg5 useStickySettings:(BOOL)arg6;
+ (id)createBoostedPostBudgetsFetchRequestWithPageID:(id)arg1 componentApp:(id)arg2 storyID:(id)arg3 stickyBudget:(id)arg4 audience:(id)arg5 targeting:(id)arg6 campaignLength:(id)arg7 maxBudgetCount:(unsigned int)arg8 adAccountID:(id)arg9 actorFBID:(id)arg10 callbackPerformer:(id)arg11;
+ (id)createBudgetRecommendationsRequestWithPageID:(id)arg1 componentApp:(id)arg2 storyID:(id)arg3 stickyBudget:(id)arg4 audience:(id)arg5 targeting:(id)arg6 campaignLength:(id)arg7 maxBudgetCount:(unsigned int)arg8 adAccountID:(id)arg9 actorFBID:(id)arg10;
+ (id)modifyRoeCampaignRequestWithPromotionID:(id)arg1 budgetValue:(id)arg2 stopTime:(id)arg3 actorFBID:(id)arg4 adsRunStatus:(unsigned int)arg5 storyID:(id)arg6 batchStoryStatusRequest:(BOOL)arg7;
+ (id)createModifyRoeCampaignBatchRequestWithPromotionID:(id)arg1 budgetValue:(id)arg2 stopTime:(id)arg3 actorFBID:(id)arg4 adsRunStatus:(unsigned int)arg5 storyID:(id)arg6 batchStoryStatusRequest:(BOOL)arg7;
+ (id)createRoeCampaignRequestWithStoryLegacyAPIID:(id)arg1 storyID:(id)arg2 budget:(id)arg3 currency:(id)arg4 startTime:(id)arg5 stopTime:(id)arg6 audience:(id)arg7 targeting:(id)arg8 adAccountID:(id)arg9 adConversionPixelID:(id)arg10 actorFBID:(id)arg11 placement:(id)arg12;

@end

