//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBPageImageInfo;

@protocol FBPageHeaderImageDownloaderDelegate <NSObject>
- (void)finishedDownloadingProfilePic:(FBPageImageInfo *)arg1;
- (void)finishedDownloadingCoverPhoto:(FBPageImageInfo *)arg1;
- (BOOL)isProfilePicDisplayed:(FBPageImageInfo *)arg1;
- (BOOL)isCoverPhotoDisplayed:(FBPageImageInfo *)arg1;
@end

