//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBMemPageCardCell.h"

#import "FBPageCardProtocol-Protocol.h"

@class FBPageActionableLinkView, FBPageStackingView, NSString;
@protocol FBPageActivitiesPostLinksCardCellDelegate;

@interface FBPageActivitiesPostLinksCardCell : FBMemPageCardCell <FBPageCardProtocol>
{
    FBPageStackingView *_stackingView;
    unsigned int _scheduledPostCount;
    unsigned int _draftPostCount;
    id <FBPageActivitiesPostLinksCardCellDelegate> _delegate;
    FBPageActionableLinkView *_scheduledPostsView;
    FBPageActionableLinkView *_draftPostsView;
}

@property(retain, nonatomic) FBPageActionableLinkView *draftPostsView; // @synthesize draftPostsView=_draftPostsView;
@property(retain, nonatomic) FBPageActionableLinkView *scheduledPostsView; // @synthesize scheduledPostsView=_scheduledPostsView;
@property(nonatomic) __weak id <FBPageActivitiesPostLinksCardCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) unsigned int draftPostCount; // @synthesize draftPostCount=_draftPostCount;
@property(nonatomic) unsigned int scheduledPostCount; // @synthesize scheduledPostCount=_scheduledPostCount;
- (void).cxx_destruct;
- (void)_openDraftPosts;
- (void)_openScheduledPosts;
- (void)configureWithViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

