//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@class FBMemFeedStory, FBPageCustomPostsContext;

@interface FBPageCustomPostsComponent : CKCompositeComponent
{
    FBMemFeedStory *_story;
    FBPageCustomPostsContext *_context;
}

+ (id)newWithStory:(id)arg1 context:(id)arg2;
@property(readonly, nonatomic) FBPageCustomPostsContext *context; // @synthesize context=_context;
@property(readonly, nonatomic) FBMemFeedStory *story; // @synthesize story=_story;
- (void).cxx_destruct;
- (void)didTapSecondaryActionButton:(id)arg1;

@end

