//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBCommentStreamDisabledWhileEditingProtocol-Protocol.h"
#import "FBCommentsModelControllerListener-Protocol.h"
#import "FBComponentCollectionViewDataSourceEventListener-Protocol.h"
#import "FBComponentCollectionViewDataSourceSelectionEventListener-Protocol.h"
#import "FBComponentScrollEventListener-Protocol.h"

@class FBCommentsModelController, FBMemFeedback, FBPermalinkCellActionsMenu, FBPermalinkComponentDescriptor, FBPermalinkFeedbackAnalyticsManager, FBPermalinkOverlaySpinnerManager, FBPermalinkScrollPositionManager, FBPermalinkSource, FBPermalinkSourceAggregator, FBPermalinkSourceCollectionViewDataSourceAdapter, FBUserSession, NSMutableArray, NSString;
@protocol FBPermalinkCommentsManagerDelegate;

@interface FBPermalinkCommentsManager : NSObject <FBCommentsModelControllerListener, FBComponentCollectionViewDataSourceSelectionEventListener, FBComponentCollectionViewDataSourceEventListener, FBCommentStreamDisabledWhileEditingProtocol, FBComponentScrollEventListener>
{
    FBUserSession *_userSession;
    NSMutableArray *_commentWithRepliesManagers;
    FBPermalinkSourceAggregator *_commentWithRepliesSourcesAggregator;
    FBPermalinkSourceCollectionViewDataSourceAdapter *_dataSourceAdapter;
    FBPermalinkSourceAggregator *_sourceAggregator;
    BOOL _shouldApplyScrollPosition;
    FBMemFeedback *_feedback;
    FBCommentsModelController *_commentsController;
    FBPermalinkComponentDescriptor *_commentsLoadInitialSpinner;
    FBPermalinkComponentDescriptor *_commentsTailPager;
    FBPermalinkComponentDescriptor *_commentsNeckPager;
    FBPermalinkSource *_commentsLoadInitialSpinnerSource;
    FBPermalinkSource *_commentsTailPagerSource;
    FBPermalinkSource *_commentsNeckRankedPagerSource;
    FBPermalinkSource *_commentsNeckPagerSource;
    FBPermalinkSource *_commentsTailRankedPagerSource;
    NSString *_focusedCommentID;
    BOOL _isInitialLoad;
    BOOL _isLoadingNeckComments;
    BOOL _isLoadingTailComments;
    BOOL _isLoadingHeadComments;
    FBPermalinkCellActionsMenu *_cellActionsMenu;
    FBPermalinkScrollPositionManager *_scrollPositionManager;
    FBPermalinkOverlaySpinnerManager *_overlaySpinnerManager;
    FBPermalinkFeedbackAnalyticsManager *_analyticsManager;
    BOOL _disableWhileEditingComment;
    BOOL _headCommentsFinishedLoading;
    id <FBPermalinkCommentsManagerDelegate> _delegate;
}

@property(nonatomic) __weak id <FBPermalinkCommentsManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) BOOL headCommentsFinishedLoading; // @synthesize headCommentsFinishedLoading=_headCommentsFinishedLoading;
@property(readonly, nonatomic) FBCommentsModelController *commentsController; // @synthesize commentsController=_commentsController;
@property(nonatomic) BOOL disableWhileEditingComment; // @synthesize disableWhileEditingComment=_disableWhileEditingComment;
- (void).cxx_destruct;
- (void)scrollViewDidScroll:(struct FBScrollViewState)arg1;
- (void)dataSourceDidEndUpdates:(id)arg1;
- (void)dataSourceWillEndUpdates:(id)arg1 changeset:(struct Changeset)arg2;
- (void)dataSource:(id)arg1 didUnhighlightItemAtIndexPath:(id)arg2;
- (void)dataSource:(id)arg1 didHighlightItemAtIndexPath:(id)arg2;
- (void)updateComment:(id)arg1 highlighted:(BOOL)arg2;
- (void)dataSource:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (void)modelController:(id)arg1 didFailToEditComment:(id)arg2 error:(id)arg3;
- (void)modelController:(id)arg1 didEditComment:(id)arg2;
- (void)modelControllerDidFinishHeadLoading:(id)arg1;
- (void)modelControllerDidFinishTailLoading:(id)arg1;
- (void)modelControllerDidFinishNeckLoading:(id)arg1;
- (void)modelControllerWillStartHeadLoading:(id)arg1;
- (void)modelControllerWillStartTailLoading:(id)arg1;
- (void)modelControllerWillStartNeckLoading:(id)arg1;
- (void)modelController:(id)arg1 didUpdateFeedback:(id)arg2;
- (void)modelController:(id)arg1 didUpdateComments:(id)arg2 atIndexes:(id)arg3;
- (void)modelController:(id)arg1 didRemoveComments:(id)arg2 atIndexes:(id)arg3;
- (void)modelController:(id)arg1 didInsertComments:(id)arg2 atIndexes:(id)arg3;
- (void)_stopInitialLoadingSpinner;
- (void)_logSpinnerAnalyticsWithDescriptor:(id)arg1 oldDescriptor:(id)arg2 loadType:(unsigned int)arg3;
- (void)_updateTailPager;
- (void)_updateNeckPager;
- (id)_tailPagerSource;
- (id)_neckPagerSource;
- (void)_updateCommentPagers;
- (void)_updateComments:(id)arg1 atIndexes:(id)arg2;
- (void)_removeComments:(id)arg1 atIndexes:(id)arg2;
- (void)_insertComments:(id)arg1 atIndexes:(id)arg2;
- (void)_showInitialSpinner;
- (void)_prepareLoadingInitialCommentsWithFeedback:(id)arg1 focusedCommentID:(id)arg2;
- (void)loadFocusedCommentWithID:(id)arg1 feedback:(id)arg2;
- (void)loadHeadCommentsWithFeedback:(id)arg1;
- (int)_commentIndexForComment:(id)arg1;
- (id)_managerOfComment:(id)arg1;
- (id)topLevelCommentForComment:(id)arg1;
- (id)commentsWithState:(unsigned int)arg1;
- (void)setState:(unsigned int)arg1 forComment:(id)arg2;
- (void)loadTailComments;
- (void)loadNeckComments;
- (id)initWithUserSession:(id)arg1 dataSourceWriteInterface:(id)arg2 scrollPositionManager:(id)arg3 overlaySpinnerManager:(id)arg4 analyticsManager:(id)arg5 delegate:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

