//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBPermalinkStoryDownloaderDelegate-Protocol.h"

@class FBFeedbackViewController, FBPermalinkLogger, FBPermalinkStoryDownloader, FBUserSession, FBViewerContext, NSString;
@protocol FBPermalinkStoryRequestManagerDelegate;

@interface FBPermalinkStoryRequestManager : NSObject <FBPermalinkStoryDownloaderDelegate>
{
    NSString *_storyGraphQLID;
    NSString *_storyLegacyAPIPostID;
    unsigned int _layoutIdiom;
    FBUserSession *_session;
    FBViewerContext *_viewer;
    FBFeedbackViewController *_feedbackViewController;
    FBPermalinkLogger *_logger;
    FBPermalinkStoryDownloader *_storyDownloader;
    id <FBPermalinkStoryRequestManagerDelegate> _delegate;
}

@property(nonatomic) __weak id <FBPermalinkStoryRequestManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)permalinkStoryDownloader:(id)arg1 didFailDownloadWithError:(id)arg2 isCanceled:(BOOL)arg3;
- (void)permalinkStoryDownloader:(id)arg1 didCompleteDownloadForStory:(id)arg2;
- (void)permalinkStoryDownloaderWillProcessDownload:(id)arg1;
- (void)cancelRequest;
- (void)downloadStory;
- (id)initWithStoryGraphQLID:(id)arg1 storyLegacyAPIPostID:(id)arg2 layoutIdiom:(unsigned int)arg3 session:(id)arg4 viewer:(id)arg5 logger:(id)arg6 feedbackViewController:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

