//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBPhotoStoryFeedbackView.h"

@class FBMemFeedback, FBRichTextTouchShimLayer, NSString;

@interface FBPhotoStoryFeedbackPhotoView : FBPhotoStoryFeedbackView
{
    FBRichTextTouchShimLayer *_messageLabel;
    NSString *_preferredContentSizeCategory;
}

+ (id)_attributedPhotoMessageForPhoto:(id)arg1 attributedStringsCache:(id)arg2 preferredContentSizeCategory:(id)arg3;
+ (struct CGSize)viewSizeForPhoto:(id)arg1 width:(float)arg2 session:(id)arg3 attributedStringsCache:(id)arg4 toolbox:(id)arg5;
+ (id)uniqueIDForViewWithWidth:(float)arg1 photo:(id)arg2;
- (void).cxx_destruct;
- (void)layoutTextContentViewForWidth:(float)arg1;
- (BOOL)canViewerShare;
- (void)setPhoto:(id)arg1;
@property(readonly, nonatomic) FBMemFeedback *feedback;
- (id)initWithSession:(id)arg1 toolbox:(id)arg2 shareable:(id)arg3;

@end

