//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBAbstractMediaSetRequestProvider.h"

@class NSString;

@interface FBPhotosGridRequestProvider : FBAbstractMediaSetRequestProvider
{
    NSString *_customTitle;
}

@property(copy, nonatomic) NSString *customTitle; // @synthesize customTitle=_customTitle;
- (void).cxx_destruct;
- (id)mediaSetTitleForResponse:(id)arg1 session:(id)arg2;
- (const struct FBGraphQLFieldSet *)edgeFieldSet;
- (id)queryForAfter:(id)arg1;

@end

