//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class CKComponentHostingView, FBCache, FBFeedComponentToolbox, FBMemPhoto, FBPhotoTagButton, FBRoundedCornerView, FBUFIBar, FBUserSession, FBWebPhotoView, NSString, UIImageView, UILongPressGestureRecognizer, UITapGestureRecognizer;
@protocol FBPhotoStoryFeedbackViewDelegate, FBShareable;

@interface FBPhotoStoryFeedbackView : UIView <UIGestureRecognizerDelegate>
{
    BOOL _addBlingLineInset;
    UIView *_cardView;
    UIView *_contentView;
    BOOL _isCardlessUIEnabled;
    UILongPressGestureRecognizer *_photoLongPressGestureRecognizer;
    UIImageView *_photoOverlay;
    UITapGestureRecognizer *_photoTapGestureRecognizer;
    UIView *_separator;
    id <FBShareable> _shareable;
    FBPhotoTagButton *_tagButton;
    UITapGestureRecognizer *_tapGestureRecognizer;
    FBFeedComponentToolbox *_toolbox;
    FBRoundedCornerView *_topLeftRoundedCorner;
    FBRoundedCornerView *_topRightRoundedCorner;
    FBUFIBar *_ufiBar;
    CKComponentHostingView *_ufiBarHostingView;
    id <FBPhotoStoryFeedbackViewDelegate> _delegate;
    FBMemPhoto *_photo;
    FBWebPhotoView *_photoView;
    FBUserSession *_session;
    UIView *_textContentView;
    FBCache *_attributedStringsCache;
}

+ (id)componentForModel:(id)arg1 context:(id)arg2;
+ (id)defaultRichTextLayerWithSession:(id)arg1;
+ (struct UIEdgeInsets)photoEdgeInsets;
+ (float)effectiveWidthForWidth:(float)arg1;
+ (struct UIEdgeInsets)edgeInsets;
+ (struct CGSize)sizeForPhoto:(id)arg1 withWidth:(float)arg2;
+ (unsigned int)imageFlagForPhoto:(id)arg1 width:(float)arg2;
@property(retain, nonatomic) FBCache *attributedStringsCache; // @synthesize attributedStringsCache=_attributedStringsCache;
@property(readonly, nonatomic) UIView *textContentView; // @synthesize textContentView=_textContentView;
@property(readonly, nonatomic) FBUserSession *session; // @synthesize session=_session;
@property(readonly, nonatomic) FBWebPhotoView *photoView; // @synthesize photoView=_photoView;
@property(retain, nonatomic) FBMemPhoto *photo; // @synthesize photo=_photo;
@property(nonatomic) __weak id <FBPhotoStoryFeedbackViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_setupGestureRecognizers;
- (void)_applyPhotoOverlay;
- (void)_didTapPhoto;
- (void)_didLongPressPhoto:(id)arg1;
- (void)_didTapBlingLine;
- (void)_didTapShare:(id)arg1 context:(id)arg2;
- (void)_didTapTag;
- (void)_didTapComment;
- (void)_applyRoundedCornersToView:(id)arg1;
- (void)_handleLinkTapAtLocation:(struct CGPoint)arg1;
- (void)_didReceiveTap:(id)arg1;
- (struct CGRect)convertCommentButtonToView:(id)arg1;
- (struct CGRect)convertFeedbackSentenceButtonToView:(id)arg1;
- (struct CGRect)convertShareButtonToView:(id)arg1;
- (void)updateUFIWithFeedback:(id)arg1;
- (float)layoutSubviewsAndCalculateHeightForWidth:(float)arg1;
- (void)layoutTextContentViewForWidth:(float)arg1;
- (void)layoutSubviews;
- (id)feedback;
- (BOOL)canViewerShare;
- (void)dealloc;
- (id)initWithSession:(id)arg1 toolbox:(id)arg2 shareable:(id)arg3;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

