//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBCropViewControllerDelegate-Protocol.h"
#import "FBModalWebFlowDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UIPopoverPresentationControllerDelegate-Protocol.h"

@class FBMemPhoto, FBPhotoMenuItemOrderExperimentContext, FBProfilePicturePickerStatusView, FBUserSession, FBViewerContext, NSArray, NSString, UIActionSheet, UIAlertView, UIView;
@protocol FBNavigationCoordinator, FBPhotoActionSheetControllerDelegate, FBPhotoActionSheetOptionsProvider, FBPhotoDeletionProtocol;

@interface FBPhotoActionSheetController : NSObject <UIActionSheetDelegate, FBCropViewControllerDelegate, FBModalWebFlowDelegate, UIPopoverPresentationControllerDelegate, UIAlertViewDelegate>
{
    id <FBPhotoActionSheetOptionsProvider> _actionSheetOptionsProvider;
    id <FBNavigationCoordinator> _navigationCoordinator;
    id <FBPhotoDeletionProtocol> _photoDeletionController;
    UIView *_presentingView;
    FBProfilePicturePickerStatusView *_profilePictureStatusView;
    FBUserSession *_session;
    FBViewerContext *_targetForMakingProfilePicture;
    FBPhotoMenuItemOrderExperimentContext *_itemOrderExpContext;
    BOOL _showingAlertController;
    NSArray *_actionMenuItems;
    UIActionSheet *_actionSheet;
    NSString *_analyticsModule;
    id <FBPhotoActionSheetControllerDelegate> _delegate;
    FBMemPhoto *_photo;
    UIAlertView *_profilePrivacyAlertView;
    struct CGRect _actionSheetDisplayRect;
}

+ (unsigned int)defaultPhotoActionSheetOptionsForPhoto:(id)arg1 session:(id)arg2;
+ (void)setAllowsSendAsMessage:(BOOL)arg1;
+ (struct CGRect)actionSheetRectFromTouchPoint:(struct CGPoint)arg1;
@property(retain, nonatomic) UIAlertView *profilePrivacyAlertView; // @synthesize profilePrivacyAlertView=_profilePrivacyAlertView;
@property(retain, nonatomic) FBMemPhoto *photo; // @synthesize photo=_photo;
@property(nonatomic) __weak id <FBPhotoActionSheetControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSString *analyticsModule; // @synthesize analyticsModule=_analyticsModule;
@property(nonatomic) struct CGRect actionSheetDisplayRect; // @synthesize actionSheetDisplayRect=_actionSheetDisplayRect;
@property(retain, nonatomic) UIActionSheet *actionSheet; // @synthesize actionSheet=_actionSheet;
@property(copy, nonatomic) NSArray *actionMenuItems; // @synthesize actionMenuItems=_actionMenuItems;
- (void).cxx_destruct;
- (void)_usePhotoAsProfilePictureWithTarget:(id)arg1;
- (BOOL)_shouldShowProfilePicWarning;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(int)arg2;
- (void)_usePhotoAsProfilePictureForPage;
- (void)_usePhotoAsProfilePicture;
- (void)_usePhotoAsCoverPhoto;
- (void)_showProfilePictureStatusView;
- (void)_showPhotoPermissionView;
- (void)_shareButtonHit;
- (void)_sendCropRequest:(struct CGRect)arg1;
- (void)_savePhotoToAssetLibrary;
- (void)_reportPhoto;
- (void)_presentCropViewControllerForProfilePicture;
- (void)_openInApp;
- (void)_installApp;
- (void)_editPrivacy;
- (void)_showDeleteFailedAlertView;
- (void)_deletePhoto;
- (BOOL)_haveDelegateHandleActionSheetOptionIfNeeded:(unsigned int)arg1;
- (void)_confirmUntagPhoto;
- (void)_confirmDeletePhoto;
- (void)_sendAsMessage;
- (void)_cleanUpActionSheet;
- (void)_recreateActionSheetAtRect:(struct CGRect)arg1;
- (id)_photoAlertControllerWithModalViewCoordinator:(id)arg1 actionMenuItems:(id)arg2;
- (void)popoverPresentationControllerDidDismissPopover:(id)arg1;
- (void)cropViewControllerDidCancelCrop:(id)arg1;
- (void)cropViewControllerDidConfirmCrop:(id)arg1;
- (void)actionSheetCancel:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)handleTransitionToSize:(struct CGSize)arg1 rectBlock:(CDUnknownBlockType)arg2 withTransitionCoordinator:(id)arg3;
- (void)displayActionSheetFromRect:(struct CGRect)arg1 inView:(id)arg2 animated:(BOOL)arg3;
- (void)dismissActionSheetAnimated:(BOOL)arg1;
- (BOOL)actionSheetIsVisible;
- (void)dealloc;
- (id)initWithPhoto:(id)arg1 actionSheetOptionsProvider:(id)arg2 delegate:(id)arg3 analyticsModule:(id)arg4 navigationCoordinator:(id)arg5 session:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

