//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBPickUpMediaAttachmentNode.h"

#import "ASMultiplexImageNodeDataSource-Protocol.h"
#import "FBVideoAttachmentNode-Protocol.h"

@class ASMultiplexImageNode, FBVideoOverlayNode, FBVideoScrubbingNode, NSString, UIView;
@protocol FBVideoAttachmentNodeDelegate;

@interface FBPickUpVideoAttachmentNode : FBPickUpMediaAttachmentNode <ASMultiplexImageNodeDataSource, FBVideoAttachmentNode>
{
    ASMultiplexImageNode *_previewImageNode;
    FBVideoOverlayNode *_videoOverlayNode;
    FBVideoScrubbingNode *_videoScrubbingNode;
    UIView *_videoView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FBVideoScrubbingNode *scrubbingNode;
@property(readonly, nonatomic) FBVideoOverlayNode *overlayNode;
@property(retain, nonatomic) UIView *videoView;
- (struct CGSize)openedSizeForOrientation:(int)arg1;
- (id)openedOverlayNode;
- (id)multiplexImageNode:(id)arg1 URLForImageIdentifier:(id)arg2;
- (void)applyOrientationRotation:(float)arg1 withProgress:(float)arg2;
- (void)didExitHierarchy;
- (void)stopPlayingVideo;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layout;
- (struct CGSize)calculateSizeThatFits:(struct CGSize)arg1;
- (id)init;
- (void)dealloc;
- (id)initWithPreviewURL:(id)arg1 session:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <FBVideoAttachmentNodeDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

