//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBPageableItemViewStatePersistence-Protocol.h"
#import "FBPickUpAttachmentNodeDelegate-Protocol.h"

@class FBAttachmentNode, FBPickUpPhotoAttachmentNode;

@protocol FBPickUpPhotoAttachmentNodeDelegate <FBPickUpAttachmentNodeDelegate, FBPageableItemViewStatePersistence>

@optional
- (struct CGSize)photoAttachment:(FBPickUpPhotoAttachmentNode *)arg1 openedSizeForOrientation:(int)arg2 defaultSize:(struct CGSize)arg3;
- (void)photoAttachmentDidSettleAsInactivePage:(FBPickUpPhotoAttachmentNode *)arg1 wasActivePage:(BOOL)arg2;
- (void)photoAttachmentDidSettleAsActivePage:(FBPickUpPhotoAttachmentNode *)arg1;
- (void)photoAttachmentMaySettleAsActivePage:(FBPickUpPhotoAttachmentNode *)arg1;
- (void)photoAttachmentDidBeginMoving:(FBPickUpPhotoAttachmentNode *)arg1;
- (void)photoAttachmentDidExitPagingRange:(FBAttachmentNode *)arg1;
- (void)photoAttachmentDidEnterPagingRange:(FBPickUpPhotoAttachmentNode *)arg1;
- (void)photoAttachmentDidCleanUpAfterPaging:(FBPickUpPhotoAttachmentNode *)arg1;
- (void)photoAttachment:(FBPickUpPhotoAttachmentNode *)arg1 didPrepareForPagingInContext:(unsigned int)arg2;
@end

