//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CALayer, FBPlacesCategoryMenuItemButton, FBUserSession, UIImageView;
@protocol FBPlacesCategoryMenuItemViewDelegate;

@interface FBPlacesCategoryMenuItemView : UIView
{
    CALayer *_leftBorder;
    CALayer *_bottomBorder;
    FBUserSession *_session;
    FBPlacesCategoryMenuItemButton *_itemButton;
    UIImageView *_loadingView;
    BOOL _showBottomBorder;
    BOOL _showLeftBorder;
    id <FBPlacesCategoryMenuItemViewDelegate> _delegate;
}

@property(nonatomic) BOOL showLeftBorder; // @synthesize showLeftBorder=_showLeftBorder;
@property(nonatomic) BOOL showBottomBorder; // @synthesize showBottomBorder=_showBottomBorder;
@property(nonatomic) __weak id <FBPlacesCategoryMenuItemViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)_circleImageWithColor:(id)arg1 imageSize:(float)arg2;
- (void)layoutSubviews;
- (void)updateCategoryItemWithTitleString:(id)arg1 urlImage:(id)arg2;
- (void)updateCategoryItemWithTitleString:(id)arg1 image:(id)arg2;
- (void)updateViewState:(int)arg1;
- (void)_didTapOnCategoryButton;
- (id)initWithSession:(id)arg1;

@end

