//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UIImageView;
@protocol FBPlatformLoadingViewDelegate;

@interface FBPlatformLoadingView : UIView
{
    NSString *_launchImageBaseName;
    UIImageView *_imageView;
    UIButton *_cancelButton;
    UIButton *_continueButton;
    BOOL _continueButtonEnabled;
    id <FBPlatformLoadingViewDelegate> _delegate;
}

@property(nonatomic) __weak id <FBPlatformLoadingViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic, getter=isContinueButtonEnabled) BOOL continueButtonEnabled; // @synthesize continueButtonEnabled=_continueButtonEnabled;
- (void).cxx_destruct;
- (id)_makeButtonWithTitle:(id)arg1 action:(SEL)arg2;
- (void)_ensureContinueButton;
- (void)_continueButtonTapped:(id)arg1;
- (void)_cancelButtonTapped:(id)arg1;
- (void)setOrientation:(int)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 orientation:(int)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

