//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBPlatformJSDialogOverride.h"

@class NSMutableDictionary, NSString, NSURL;

@interface FBPlatformMutableJSDialogOverride : FBPlatformJSDialogOverride
{
    NSMutableDictionary *_readwriteExtras;
}

+ (BOOL)supportsSecureCoding;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
@property(copy, nonatomic) NSString *version; // @dynamic version;
@property(copy, nonatomic) NSURL *URL; // @dynamic URL;
@property(copy, nonatomic) NSString *method; // @dynamic method;
@property(nonatomic) BOOL hideNavBar; // @dynamic hideNavBar;
@property(nonatomic) BOOL enableScroll; // @dynamic enableScroll;
- (id)initWithPlatformJSDialogOverride:(id)arg1;
- (id)init;

@end

