//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBPlatformPhotoAttachment.h"

@class NSURL, UIImage;

@interface FBPlatformLocalPhotoAttachment : FBPlatformPhotoAttachment
{
    NSURL *_temporaryImageFileName;
    UIImage *_imageBeingWritten;
}

@property(retain, nonatomic) UIImage *imageBeingWritten; // @synthesize imageBeingWritten=_imageBeingWritten;
- (void).cxx_destruct;
- (void)_writeToTemporaryFile:(id)arg1;
- (id)existingFBID;
- (BOOL)requiresUpload;
- (void)loadImageDataForUploadWithCompressionRate:(float)arg1 maximumDimension:(int)arg2 specialCasePanoramas:(BOOL)arg3 loggingBlock:(CDUnknownBlockType)arg4 completionBlock:(CDUnknownBlockType)arg5;
- (id)initWithAssetID:(id)arg1 image:(id)arg2 platformPhotoMetadata:(id)arg3;

@end

