//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBPopoverControllerDelegate-Protocol.h"

@class FBPopoverController, NSString, UIViewController;
@protocol FBPopoverOverlayDelegate;

@interface FBPopoverOverlay : NSObject <FBPopoverControllerDelegate>
{
    FBPopoverController *_popoverController;
    BOOL _shouldAutomaticallyResizeWithKeyboard;
    BOOL _centeredVertically;
    id <FBPopoverOverlayDelegate> _delegate;
    UIViewController *_containerViewController;
    CDUnknownBlockType _didDismissBlock;
    struct CGSize _customContentSize;
}

@property(nonatomic) BOOL centeredVertically; // @synthesize centeredVertically=_centeredVertically;
@property(nonatomic) struct CGSize customContentSize; // @synthesize customContentSize=_customContentSize;
@property(nonatomic) BOOL shouldAutomaticallyResizeWithKeyboard; // @synthesize shouldAutomaticallyResizeWithKeyboard=_shouldAutomaticallyResizeWithKeyboard;
@property(copy, nonatomic) CDUnknownBlockType didDismissBlock; // @synthesize didDismissBlock=_didDismissBlock;
@property(readonly, nonatomic) UIViewController *containerViewController; // @synthesize containerViewController=_containerViewController;
@property(nonatomic) __weak id <FBPopoverOverlayDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (float)_popoverTopPadding;
- (float)_popoverBottomPadding;
- (void)fb_popoverControllerDidDismissPopover:(id)arg1 withInteraction:(unsigned int)arg2;
- (void)fb_popoverControllerWillDismissPopover:(id)arg1 withInteraction:(unsigned int)arg2;
- (BOOL)fb_popoverControllerShouldDismissPopover:(id)arg1 withInteraction:(unsigned int)arg2;
- (BOOL)_delegateShouldDismiss;
- (void)updateLayout;
- (BOOL)dismissPopoverOverlayAnimated:(BOOL)arg1 skipShouldDismissDelegate:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (BOOL)dismissPopoverOverlayAnimated:(BOOL)arg1 skipShouldDismissDelegate:(BOOL)arg2;
- (void)presentPopoverOverlayAnimated:(BOOL)arg1 completion:(CDUnknownBlockType)arg2;
- (void)presentPopoverOverlayAnimated:(BOOL)arg1;
- (void)dealloc;
@property(readonly, nonatomic) UIViewController *contentViewController;
- (id)init;
- (id)initWithContentViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

