//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBComposerStickyGuardrailViewControllerDelegate-Protocol.h"

@class FBComposerStickyGuardrailViewController, FBMemFeedStory, FBPopoverController, FBUserSession;
@protocol FBPrivacyPostUpsellViewControllerDelegate;

@interface FBPrivacyPostUpsellViewController : NSObject <FBComposerStickyGuardrailViewControllerDelegate>
{
    FBUserSession *_session;
    FBMemFeedStory *_feedStory;
    FBComposerStickyGuardrailViewController *_guardrailViewController;
    FBPopoverController *_stickyUpsellPopoverController;
    id <FBPrivacyPostUpsellViewControllerDelegate> _delegate;
}

+ (BOOL)eligibleForStickyUpsellForStory:(id)arg1 session:(id)arg2;
@property(nonatomic) __weak id <FBPrivacyPostUpsellViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_dismissPopover;
- (void)stickyGuardrailViewControllerUserDidDismissView:(id)arg1 withEvent:(unsigned int)arg2;
- (void)stickyGuardrailViewControllerUserDidChangePrivacyToSuggested:(id)arg1;
- (id)_suggestedPrivacySetting;
- (id)_originalPrivacySetting;
- (id)_generateAudienceEducationData;
- (void)_sendStickyUpsellRequestForEvent:(unsigned int)arg1;
- (void)dealloc;
- (id)presentablePopoverControllerWithFrame:(struct CGRect)arg1;
- (id)initWithSession:(id)arg1 story:(id)arg2;

@end

