//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBSyncEngine-Protocol.h"

@class NSArray, NSDate, NSError, NSOperation, NSOperationQueue, NSString;
@protocol FBFacebookRequestSender, FBSyncEngineDelegate;

@interface FBPresenceSyncEngine : NSObject <FBSyncEngine>
{
    id <FBFacebookRequestSender> _requestSender;
    NSOperationQueue *_queue;
    NSOperation *_pendingSyncOperation;
    id <FBSyncEngineDelegate> _delegate;
    NSDate *_syncStartTime;
    NSArray *_syncEvents;
    NSError *_error;
    NSOperationQueue *_operationQueue;
    NSError *_syncError;
}

@property(retain) NSError *syncError; // @synthesize syncError=_syncError;
@property(retain) NSArray *syncEvents; // @synthesize syncEvents=_syncEvents;
@property(retain, nonatomic) NSDate *syncStartTime; // @synthesize syncStartTime=_syncStartTime;
@property(retain, nonatomic) NSOperation *pendingSyncOperation; // @synthesize pendingSyncOperation=_pendingSyncOperation;
@property(retain, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) id <FBFacebookRequestSender> requestSender; // @synthesize requestSender=_requestSender;
@property id <FBSyncEngineDelegate> delegate; // @synthesize delegate=_delegate;
- (id)syncGroupConversationParticipantForResult:(id)arg1;
- (id)_syncPersonForResult:(id)arg1;
- (id)_syncEventsForResponse:(id)arg1;
- (void)syncPresenceInBackground;
- (void)_onSyncComplete:(id)arg1;
- (void)_onSyncError:(id)arg1;
- (void)cleanUpSync;
- (void)cancelSync;
- (void)forceUserSyncWithPreviousSyncSummary:(id)arg1;
- (void)syncUsersWithPreviousSyncSummary:(id)arg1;
- (void)dealloc;
- (id)initWithFacebookRequestSender:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

