//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBUserSession, NSString;
@protocol FBNetworkTransactionSurfacing, FBProfileQuestionRequestParserDelegate, FBServiceTransactionMutating;

@interface FBProfileQuestionRequestParser : NSObject
{
    id <FBServiceTransactionMutating> _saveQuestionToken;
    id <FBServiceTransactionMutating> _skipQuestionAndGetNextToken;
    id <FBNetworkTransactionSurfacing> _skipQuestionToken;
    id <FBServiceTransactionMutating> _firstQuestionToken;
    CDStruct_2c43369c _coordinate;
    id <FBProfileQuestionRequestParserDelegate> _delegate;
    FBUserSession *_session;
    NSString *_surface;
}

@property(copy, nonatomic) NSString *surface; // @synthesize surface=_surface;
@property(retain, nonatomic) FBUserSession *session; // @synthesize session=_session;
@property(nonatomic) __weak id <FBProfileQuestionRequestParserDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cancel;
- (id)_sendQuestionRequestWithQuestionID:(id)arg1 questionSessionID:(id)arg2 session:(id)arg3 parameters:(id)arg4 finishType:(unsigned int)arg5;
- (void)saveCurrentQuestionAndRequestNextQuestion:(id)arg1 questionSessionID:(id)arg2 pageID:(id)arg3 privacy:(id)arg4 session:(id)arg5;
- (void)skipCurrentQuestionAndRequestNextQuestion:(id)arg1 questionSessionID:(id)arg2 session:(id)arg3;
- (void)skipCurrentQuestion:(id)arg1 questionSessionID:(id)arg2 session:(id)arg3;
- (id)_createUpdateRequestWithQuestionID:(id)arg1 parameters:(id)arg2;
- (void)requestFirstQuestion;
- (void)dealloc;
- (id)initWithSession:(id)arg1 coordinate:(CDStruct_c3b9c2ee)arg2 surface:(id)arg3;
- (id)initWithSession:(id)arg1 surface:(id)arg2;

@end

