//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@interface FBProfileProtileNavBarComponent : CKCompositeComponent
{
}

+ (id)newWithItems:(id)arg1 shouldShowTopLine:(BOOL)arg2 barWidth:(float)arg3 insets:(struct UIEdgeInsets)arg4 toolbox:(id)arg5;

@end

