//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBProfileTypeaheadDataSourceDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"

@class FBUserSession, NSArray, NSString;
@protocol FBProfileTypeaheadCompositeDataSourceDelegate;

@interface FBProfileTypeaheadCompositeDataSource : NSObject <UITableViewDataSource, FBProfileTypeaheadDataSourceDelegate>
{
    FBUserSession *_session;
    NSArray *_dataSourceArray;
    NSString *_currentSearchQuery;
    id <FBProfileTypeaheadCompositeDataSourceDelegate> _delegate;
}

@property(nonatomic) __weak id <FBProfileTypeaheadCompositeDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)objectIDsForLogging;
- (id)_deduplicatedResults;
@property(readonly, nonatomic, getter=isLoading) BOOL loading;
- (void)profileTypeaheadDataSourceDidChangeContents:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (int)tableView:(id)arg1 numberOfRowsInSection:(int)arg2;
- (void)updateResultsForSearchQuery:(id)arg1;
- (id)initWithDataSources:(id)arg1 session:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

