//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCopying-Protocol.h"

@class NSString, NSURL;

@interface FBPresenceIconModel : FBValueObject <NSCopying>
{
    NSURL *_smallImageURL;
    NSURL *_largeImageURL;
    NSString *_graphQLID;
    NSString *_imageAssetName;
    unsigned int _iconType;
}

@property(readonly, nonatomic) unsigned int iconType; // @synthesize iconType=_iconType;
@property(readonly, copy, nonatomic) NSString *imageAssetName; // @synthesize imageAssetName=_imageAssetName;
@property(readonly, copy, nonatomic) NSString *graphQLID; // @synthesize graphQLID=_graphQLID;
@property(readonly, copy, nonatomic) NSURL *largeImageURL; // @synthesize largeImageURL=_largeImageURL;
@property(readonly, copy, nonatomic) NSURL *smallImageURL; // @synthesize smallImageURL=_smallImageURL;
- (void).cxx_destruct;
- (id)initWithSmallImageURL:(id)arg1 largeImageURL:(id)arg2 graphQLID:(id)arg3 imageAssetName:(id)arg4 iconType:(unsigned int)arg5;

@end

