//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface FBPrivacyPickerAnalyticsData : NSObject
{
    unsigned long long _timeSpentStartTime;
    NSString *_source;
    NSString *_composerSession;
}

@property(readonly, nonatomic) unsigned long long timeSpentStartTime; // @synthesize timeSpentStartTime=_timeSpentStartTime;
@property(readonly, copy, nonatomic) NSString *composerSession; // @synthesize composerSession=_composerSession;
@property(readonly, copy, nonatomic) NSString *source; // @synthesize source=_source;
- (void).cxx_destruct;
- (id)markTimeSpentStart;
- (id)initWithSource:(id)arg1 composerSession:(id)arg2 timeSpentStartTime:(unsigned long long)arg3;
- (id)initWithSource:(id)arg1 composerSession:(id)arg2;

@end

