//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBFriendListModelControllerDelegate-Protocol.h"

@class FBFriendListModelController, FBPresenceAmbientInfoListenerAnnouncer, NSDictionary, NSString;

@interface FBPresenceAmbientInfoFetcher : NSObject <FBFriendListModelControllerDelegate>
{
    FBPresenceAmbientInfoListenerAnnouncer *_announcer;
    FBFriendListModelController *_friendListModelController;
    NSDictionary *_syncPeopleByPersonID;
}

- (void).cxx_destruct;
- (void)modelController:(id)arg1 didCompleteSearchOperationReturningPeople:(id)arg2;
- (id)searchOperationForSyncStore:(id)arg1;
- (void)stopFetching;
- (void)beginFetching;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (void)dealloc;
- (id)initWithSyncEngineManager:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

