//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBNuxPresenter-Protocol.h"

@class FBQPPromotion, FBQuickPromotionEligibilityChecker, FBQuickPromotionServerContext, FBUserSession, NSArray, NSDictionary, NSString;
@protocol FBNuxDelegate;

@interface FBQuickPromotionBaseNuxPresenter : NSObject <FBNuxPresenter>
{
    id <FBNuxDelegate> _nuxCoordinator;
    FBQPPromotion *_displayedPromotion;
    NSArray *_promotions;
    FBUserSession *_session;
    FBQuickPromotionServerContext *_context;
    FBQuickPromotionEligibilityChecker *_eligibilityChecker;
}

@property(retain, nonatomic) FBQuickPromotionEligibilityChecker *eligibilityChecker; // @synthesize eligibilityChecker=_eligibilityChecker;
@property(retain, nonatomic) FBQuickPromotionServerContext *context; // @synthesize context=_context;
@property(retain, nonatomic) FBUserSession *session; // @synthesize session=_session;
@property(copy, nonatomic) NSArray *promotions; // @synthesize promotions=_promotions;
@property(retain, nonatomic) FBQPPromotion *displayedPromotion; // @synthesize displayedPromotion=_displayedPromotion;
@property(nonatomic) __weak id <FBNuxDelegate> nuxCoordinator; // @synthesize nuxCoordinator=_nuxCoordinator;
- (void).cxx_destruct;
- (id)newBannerViewControllerWithContext:(id)arg1;
- (id)bestPromotionForTrigger:(id)arg1 withContext:(id)arg2;
- (id)bestPromotionForTrigger:(id)arg1;
- (unsigned int)preferredPresentationMethod;
@property(readonly, nonatomic) NSDictionary *extraLogData;
@property(readonly, nonatomic) NSString *nuxAnalyticsModule;
- (int)nuxStateForTriggerID:(id)arg1 triggerContext:(id)arg2;
- (void)prepareWithServerContext:(id)arg1;
- (id)viewControllerForPresentation;
@property(readonly, nonatomic) int nuxType;
- (Class)serverContextClass;
- (id)versionID;
- (id)triggerIDs;
- (id)nuxID;
- (id)init;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(copy, nonatomic) CDUnknownBlockType onClosedBlock;
@property(readonly) Class superclass;

@end

