//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBQuickPromotionFilter.h"

@class NSDictionary;

@interface FBQuickPromotionAggregatedCapFilter : FBQuickPromotionFilter
{
    unsigned int _cap;
    NSDictionary *_promotions;
}

+ (id)expectedParams;
+ (id)filterTypeKey;
- (void).cxx_destruct;
- (BOOL)passesFilterWithContext:(id)arg1 withDebugInfo:(id *)arg2;
@property(readonly, nonatomic) unsigned int currentTotal;
@property(readonly, nonatomic) NSDictionary *promotions; // @synthesize promotions=_promotions;
@property(readonly, nonatomic) unsigned int cap; // @synthesize cap=_cap;

@end

