//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBItemContentView, FBReactionControlAlphaChangeOnHighlight;

@interface FBReactionEventProfileBlockItemView : UIView
{
    FBItemContentView *_itemContentView;
    UIView *_leftHandView;
    UIView *_dividerView;
    FBReactionControlAlphaChangeOnHighlight *_control;
}

@property(retain, nonatomic) FBReactionControlAlphaChangeOnHighlight *control; // @synthesize control=_control;
- (void).cxx_destruct;
- (struct CGSize)_availableSizeForItemContentViewInTotalSize:(struct CGSize)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 itemContentViewConfig:(id)arg2 leftHandView:(id)arg3 hasBottomDivider:(BOOL)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

