//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class FBImageDownloader, FBItemView_DEPRECATED, FBNetworkImageView, NSAttributedString, NSString, NSURL, UIView;

@interface FBReactionSettingsItemCell : UITableViewCell
{
    FBImageDownloader *_imageDownloader;
    FBItemView_DEPRECATED *_itemView;
    FBNetworkImageView *_imageView;
    UIView *_borderBottom;
    struct UIEdgeInsets _insets;
    BOOL _checked;
    BOOL _bottomBorderFullWidth;
    NSString *_name;
    NSAttributedString *_subtitle;
    NSAttributedString *_secondarySubtitle;
    NSURL *_imageURL;
}

@property(nonatomic) BOOL bottomBorderFullWidth; // @synthesize bottomBorderFullWidth=_bottomBorderFullWidth;
@property(nonatomic) BOOL checked; // @synthesize checked=_checked;
@property(copy, nonatomic) NSURL *imageURL; // @synthesize imageURL=_imageURL;
@property(copy, nonatomic) NSAttributedString *secondarySubtitle; // @synthesize secondarySubtitle=_secondarySubtitle;
@property(copy, nonatomic) NSAttributedString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (id)initWithImageDownloader:(id)arg1 contentInsets:(struct UIEdgeInsets)arg2 reuseIdentifier:(id)arg3;

@end

