//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "CKCompositeComponent.h"

@interface FBResearchPollMultipleChoiceResultComponent : CKCompositeComponent
{
}

+ (id)newWithResponseEdge:(id)arg1 totalCount:(unsigned int)arg2 optionIndex:(unsigned int)arg3 contentSizeCategory:(id)arg4;

@end

