//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBReactionAttachmentActionAdapter-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class FBActionBarItem, FBMemEvent, FBReactionAdapterContext, FBUserSession, NSMutableDictionary, NSString, UIActionSheet, UIButton;
@protocol FBQueriedReactionStoryAttachmentActionFieldsProtocol, FBReactionAttachmentActionAdapterDelegate;

@interface FBReactionRespondToEventAttachmentActionAdapter : NSObject <UIActionSheetDelegate, FBReactionAttachmentActionAdapter>
{
    FBActionBarItem *_actionBarItem;
    UIButton *_actionButton;
    FBMemEvent *_event;
    id <FBQueriedReactionStoryAttachmentActionFieldsProtocol> _attachmentAction;
    FBUserSession *_session;
    UIActionSheet *_actionSheet;
    NSMutableDictionary *_actionSheetIndexToMutationRsvpStatus;
    FBReactionAdapterContext *_reactionContext;
    id <FBReactionAttachmentActionAdapterDelegate> delegate;
}

+ (id)_glyphForEventStatus:(id)arg1;
@property(nonatomic) __weak id <FBReactionAttachmentActionAdapterDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)_handleRespondEventActionWithRsvpStatus:(id)arg1;
- (void)_openRespondEventActionSheet;
- (void)configureActionViewWithEvent:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(int)arg2;
- (void)attachmentActionTapped;
- (id)actionButton;
- (id)actionBarItem;
- (id)initWithReactionContext:(id)arg1 resultStyle:(id)arg2 attachmentAction:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

