//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "ASControlNode.h"

@class ASDisplayNode, ASNetworkImageNode, ASTextNode, FBRelatedArticlesNodeMetrics, NSString;

@interface FBRelatedArticlesNode : ASControlNode
{
    NSString *_titleText;
    FBRelatedArticlesNodeMetrics *_metrics;
    ASTextNode *_articleTitleNode;
    ASNetworkImageNode *_articleImageNode;
    ASDisplayNode *_hairlineNode;
    NSString *_canonicalURLString;
}

@property(readonly, copy, nonatomic) NSString *canonicalURLString; // @synthesize canonicalURLString=_canonicalURLString;
- (void).cxx_destruct;
- (struct CGSize)calculateSizeThatFits:(struct CGSize)arg1;
- (void)layout;
- (id)initWithTitleText:(id)arg1 imageURLString:(id)arg2 canonicalURLString:(id)arg3 metrics:(id)arg4 imageCache:(id)arg5 imageDownload:(id)arg6;

@end

