//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray;

@interface FBReactionAttachmentActionAdapterArray : NSObject
{
    NSMutableArray *_attachmentActionAdapters;
}

- (void).cxx_destruct;
- (unsigned int)indexOfAttachmentActionAdapter:(id)arg1;
- (id)attachmentActionAdapterForIndex:(unsigned int)arg1;
- (unsigned int)numberOfAttachmentActionAdapters;
- (id)initWithAttachmentActions:(id)arg1 reactionContext:(id)arg2;
- (id)init;

@end

