//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBReactionAttachmentsQuery : NSObject
{
}

+ (id)graphQLQueryWithAfterCursor:(id)arg1 count:(id)arg2 device:(id)arg3 enableImageShareAttachment:(id)arg4 feedbackIncludeReactions:(id)arg5 feedbackIncludeSeenBy:(id)arg6 formatType:(id)arg7 genericAttachmentFallbackSquareImageDimension:(id)arg8 genericAttachmentLargeSquareImageDimension:(id)arg9 genericAttachmentPortraitImageHeight:(id)arg10 genericAttachmentPortraitImageWidth:(id)arg11 genericAttachmentSmallCoverImageHeight:(id)arg12 genericAttachmentSmallCoverImageWidth:(id)arg13 genericAttachmentSmallSquareImageDimension:(id)arg14 genericAttachmentTallCoverImageHeight:(id)arg15 genericAttachmentTallCoverImageWidth:(id)arg16 inChannelsExperiment:(id)arg17 isZeroRated:(id)arg18 mediaType:(id)arg19 numBylines:(id)arg20 reactionStoryId:(id)arg21 renderLocation:(id)arg22 renderActorInGutter:(id)arg23 scale:(id)arg24 shouldLoadStreamingImage:(id)arg25 streamingImageResolution:(id)arg26 videoThumbnailSize:(id)arg27;

@end

