//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

@class FBMemPerson, FBRequestTabFriendListDataSource, NSArray;

@protocol FBRequestTabFriendListDataSourceDelegate
- (void)friendListDataSource:(FBRequestTabFriendListDataSource *)arg1 didRemoveFriendAtIndex:(unsigned int)arg2;
- (void)friendListDataSource:(FBRequestTabFriendListDataSource *)arg1 didUpdateFriend:(FBMemPerson *)arg2 atIndex:(unsigned int)arg3;
- (void)friendListDataSource:(FBRequestTabFriendListDataSource *)arg1 didLoadFriends:(NSArray *)arg2;
@end

