//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBUserSession, NSArray, NSMutableArray;
@protocol FBRequestTabFriendListDataSourceDelegate;

@interface FBRequestTabFriendListDataSource : NSObject
{
    FBUserSession *_session;
    NSMutableArray *_friends;
    unsigned int _numOfFriendsInList;
    id <FBRequestTabFriendListDataSourceDelegate> _delegate;
}

@property(nonatomic) __weak id <FBRequestTabFriendListDataSourceDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_personChanged:(id)arg1;
- (void)_addConsistencyObserver:(id)arg1;
- (id)_parseResponse:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *friends;
- (void)startFetching;
- (id)initWithSession:(id)arg1;

@end

