//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBComposerFlowDelegate-Protocol.h"
#import "FBPublishingCompletionEventListener-Protocol.h"
#import "FBReactionAttachmentActionAdapter-Protocol.h"

@class FBActionBarItem, FBPublishingCompletionEventForwarder, FBReactionAdapterContext, FBUserSession, NSString, UIButton;
@protocol FBQueriedReactionStoryAttachmentActionFieldsProtocol, FBReactionAttachmentActionAdapterDelegate;

@interface FBReactionWriteOnTimelineAttachmentActionAdapter : NSObject <FBComposerFlowDelegate, FBPublishingCompletionEventListener, FBReactionAttachmentActionAdapter>
{
    FBActionBarItem *_actionBarItem;
    id <FBQueriedReactionStoryAttachmentActionFieldsProtocol> _attachmentAction;
    FBReactionAdapterContext *_reactionContext;
    UIButton *_actionButton;
    FBPublishingCompletionEventForwarder *_publishingEventForwarder;
    id <FBReactionAttachmentActionAdapterDelegate> delegate;
    FBUserSession *_session;
}

@property(retain, nonatomic) FBUserSession *session; // @synthesize session=_session;
@property(nonatomic) __weak id <FBReactionAttachmentActionAdapterDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)cleanUpPublicationHandling;
- (void)publicationCompletedThroughTerminalFailureOfPublication:(id)arg1 withError:(id)arg2;
- (void)publicationCompletedThroughSuccessOfPublication:(id)arg1 withResponse:(id)arg2;
- (void)publicationCompletedThroughCancellationOfPublication:(id)arg1;
- (void)composerCompletedWithResult:(id)arg1;
- (id)actionButton;
- (void)attachmentActionTapped;
- (id)actionBarItem;
- (id)initWithReactionContext:(id)arg1 resultStyle:(id)arg2 attachmentAction:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

