//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBReuseInstanceProvider-Protocol.h"
#import "FBReusePoolDelegate-Protocol.h"

@class NSMapTable, NSString;

@interface FBReusePoolController : NSObject <FBReusePoolDelegate, FBReuseInstanceProvider>
{
    struct RecursiveMutex _lock;
    NSMapTable *_poolByBlockControllerClass;
    NSMapTable *_blockControllerClassByPool;
    NSMapTable *_blockControllerByReuseID;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)reusePool:(id)arg1 didReclaimInstanceWithIdentifier:(id)arg2;
- (void)reusePool:(id)arg1 prepareInstanceForReuse:(id)arg2;
- (void)_performBlockWithReusePool:(CDUnknownBlockType)arg1 forBlockController:(id)arg2;
- (void)enqueueInstance:(id)arg1;
- (id)dequeueInstance:(id)arg1;
- (void)removeBlockController:(id)arg1;
- (void)_allocatePoolForBlockControllerClassIfNecessary:(Class)arg1 loadToCapacity:(BOOL)arg2;
- (void)reset;
- (void)addBlockController:(id)arg1 loadToCapacity:(BOOL)arg2;
- (void)initializePoolForBlockControllerClass:(Class)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

