//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSTextCheckingResult, UIView;

@interface FBRichTextComponentActionContext : NSObject
{
    NSTextCheckingResult *_result;
    UIView *_view;
    struct CGPoint _location;
}

@property(readonly, nonatomic) struct CGPoint location; // @synthesize location=_location;
@property(readonly, nonatomic) UIView *view; // @synthesize view=_view;
@property(readonly, nonatomic) NSTextCheckingResult *result; // @synthesize result=_result;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithResult:(id)arg1 view:(id)arg2 location:(struct CGPoint)arg3;

@end

