//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBRichStoryEntityGIFProtocol-Protocol.h"

@class NSNumber, NSString;
@protocol FBRichStoryEntityImageProtocol;

@interface FBRichStoryEntityGIF : NSObject <FBRichStoryEntityGIFProtocol>
{
    NSString *_urlString;
    id <FBRichStoryEntityImageProtocol> _previewImage;
    NSNumber *_width;
    NSNumber *_height;
}

+ (id)gifWithURLString:(id)arg1 previewImage:(id)arg2 width:(id)arg3 height:(id)arg4;
@property(nonatomic) NSNumber *height; // @synthesize height=_height;
@property(nonatomic) NSNumber *width; // @synthesize width=_width;
@property(nonatomic) id <FBRichStoryEntityImageProtocol> previewImage; // @synthesize previewImage=_previewImage;
@property(copy, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
- (void).cxx_destruct;
- (id)initWithURLString:(id)arg1 previewImage:(id)arg2 width:(id)arg3 height:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

