//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBRsvpSegmentedControl;
@protocol FBRsvpSegmentedControlAdapterDelegate;

@interface FBRsvpSegmentedControlAdapter : NSObject
{
    int _supportedRsvpStatus;
    float _segmentedControlWidth;
    FBRsvpSegmentedControl *_segmentedControl;
    id <FBRsvpSegmentedControlAdapterDelegate> _delegate;
}

@property(nonatomic) __weak id <FBRsvpSegmentedControlAdapterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)didSelectRsvpToolbarButton:(id)arg1;
- (int)rsvpStatusForSegmentIndex:(int)arg1;
- (id)rsvpStatusCodeForRsvpStatus:(int)arg1;
- (id)toolbarTitleForRsvpStatus:(int)arg1;
- (id)toolbarSegmentTitles;
@property(readonly, nonatomic) FBRsvpSegmentedControl *segmentedControl;
- (id)initWithSupportedRsvpStatuses:(int)arg1 segmentedControlWidth:(float)arg2 delegate:(id)arg3;

@end

