//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FBSegmentedViewDelegate-Protocol.h"

@class FBKVOController, FBScenePathContext, FBSegmentedContainerView, FBSegmentedView, NSArray, NSMutableDictionary, NSString;

@interface FBSegmentedContainerViewController : UIViewController <FBSegmentedViewDelegate>
{
    int _displayedIndex;
    int _selectedIndex;
    FBSegmentedContainerView *_containerView;
    FBKVOController *_observation;
    FBScenePathContext *_scenePathContext;
    NSMutableDictionary *_segmentTitles;
    FBSegmentedView *_segmentedView;
    NSArray *_viewControllers;
    int _previousSelectedIndex;
}

@property(readonly, nonatomic) int previousSelectedIndex; // @synthesize previousSelectedIndex=_previousSelectedIndex;
@property(nonatomic) int selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(copy, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
@property(readonly, nonatomic) FBSegmentedView *segmentedView; // @synthesize segmentedView=_segmentedView;
- (void).cxx_destruct;
- (id)analyticsUUID;
- (BOOL)analyticsRequiresNetworkContent;
- (id)analyticsPresentedViewController;
- (BOOL)analyticsHasCachedNetworkContent;
- (id)analyticsModule;
@property(readonly, nonatomic) UIViewController *displayedViewController;
- (unsigned int)supportedInterfaceOrientations;
- (void)_setupSegmentedView;
- (id)_segmentedViewItems;
- (void)_switchToViewController:(id)arg1 fromViewController:(id)arg2;
- (BOOL)shouldUpdateRightBarButtonItem;
- (BOOL)shouldUpdateTitle;
- (void)_setSegmentedViewTitle:(id)arg1 atIndex:(unsigned int)arg2;
- (void)_setSegmentedViewSelectedIndex:(int)arg1;
@property(readonly, nonatomic) UIViewController *selectedViewController;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)segmentedView:(id)arg1 didSelectItemAtIndex:(int)arg2;
- (void)viewWillLayoutSubviews;
- (void)willAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2 scenePathContext:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

