//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBPopoverControllerDelegate-Protocol.h"

@class FBPopoverActionSheet, FBUserSession, NSArray, NSString;
@protocol FBNavigationCoordinator, FBSearchDiscreetFilterPopoverControllerDelegate;

@interface FBSearchDiscreetFilterPopoverController : NSObject <FBPopoverControllerDelegate>
{
    FBUserSession *_session;
    unsigned int _selectedResultType;
    FBPopoverActionSheet *_popoverActionSheet;
    NSArray *_filters;
    id <FBNavigationCoordinator> _navigationCoordinator;
    id <FBSearchDiscreetFilterPopoverControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <FBSearchDiscreetFilterPopoverControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGPoint)_popoverPointSenderView:(id)arg1 hostView:(id)arg2;
- (id)_actionButtonItems;
- (void)updatePopoverAttachmentPointWithView:(id)arg1;
- (void)dismiss;
- (void)presentFromSenderView:(id)arg1 hostView:(id)arg2;
- (id)initWithSession:(id)arg1 selectedResultType:(unsigned int)arg2 navigationCoordinator:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

