//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBNetworkerRequest.h"

@class NSString;

@interface FBSearchActivityLogRequest : FBNetworkerRequest
{
    NSString *_module;
    NSString *_userInput;
    NSString *_selectedType;
    NSString *_selectedText;
    NSString *_selectedSemantic;
    double _timestamp;
}

@property(readonly, nonatomic) double timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, copy, nonatomic) NSString *selectedSemantic; // @synthesize selectedSemantic=_selectedSemantic;
@property(readonly, copy, nonatomic) NSString *selectedText; // @synthesize selectedText=_selectedText;
@property(readonly, copy, nonatomic) NSString *selectedType; // @synthesize selectedType=_selectedType;
@property(readonly, copy, nonatomic) NSString *userInput; // @synthesize userInput=_userInput;
- (void).cxx_destruct;
- (id)networkRequest;
- (id)initWithUserInput:(id)arg1 selectedType:(id)arg2 selectedText:(id)arg3 selectedSemantic:(id)arg4 module:(id)arg5 timestamp:(double)arg6 callbackPerformer:(id)arg7;

@end

