//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBPhotoCollectionDataSource.h"

@class FBPhotoUpdater, NSArray, NSMutableArray;
@protocol FBSearchResultsPhotoCollectionDataSourceFetchingDelegate;

@interface FBSearchResultsPhotoCollectionDataSourceSubclass : FBPhotoCollectionDataSource
{
    FBPhotoUpdater *_photoUpdater;
    NSMutableArray *_photos;
    BOOL _selectedPhotoIsInvalid;
    unsigned int _photoIndex;
    id <FBSearchResultsPhotoCollectionDataSourceFetchingDelegate> _fetchingDelegate;
}

@property(copy, nonatomic) NSArray *photos; // @synthesize photos=_photos;
@property(nonatomic) __weak id <FBSearchResultsPhotoCollectionDataSourceFetchingDelegate> fetchingDelegate; // @synthesize fetchingDelegate=_fetchingDelegate;
- (void)setPhotoIndex:(unsigned int)arg1;
- (unsigned int)photoIndex;
- (void)setSelectedPhotoIsInvalid:(BOOL)arg1;
- (BOOL)selectedPhotoIsInvalid;
- (void).cxx_destruct;
- (void)syncMore:(CDUnknownBlockType)arg1;
- (BOOL)hasMoreToSync;
- (id)photoAtIndex:(unsigned int)arg1;
- (id)photo;
- (unsigned int)photosCount;
- (void)insertPhotos:(id)arg1 fromIndex:(unsigned int)arg2;
- (void)appendPhotos:(id)arg1;
- (id)initWithPhotos:(id)arg1 selectedPhotoIndex:(unsigned int)arg2;

@end

