//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBExperimentManagerPolicy-Protocol.h"

@class FBExperimentDebugHelper, FBUserSession, NSString;
@protocol OS_dispatch_queue;

@interface FBSessionExperimentManagerPolicy : NSObject <FBExperimentManagerPolicy>
{
    FBExperimentDebugHelper *_debugHelper;
    BOOL _includeAllGroupsAndParameters;
    FBUserSession *_session;
    NSObject<OS_dispatch_queue> *_persistenceQueue;
}

- (void).cxx_destruct;
- (id)gatekeepers;
- (BOOL)isEmployee;
- (id)shortDebugInfo;
- (id)debugInfo;
- (void)setupDebugHelperWithExperimentCatalog:(id)arg1;
- (void)fetchWithExperimentCatalog:(id)arg1 withCompletionBlock:(CDUnknownBlockType)arg2 withAllGroupsAndParameters:(BOOL)arg3 scenePath:(id)arg4;
- (id)plistKey;
- (void)persistOverrides:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)loadOverrides:(CDUnknownBlockType)arg1;
- (void)persistExperiments:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)loadExperiments:(CDUnknownBlockType)arg1;
- (id)preferenceStore;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

