//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBSearchSuggestionProtocol-Protocol.h"

@class FBGraphSearchStructuredText, NSAttributedString, NSString;

@interface FBSimpleSearchSingleStateSuggestion : NSObject <FBSearchSuggestionProtocol>
{
    BOOL _isNonCacheable;
    unsigned int _cacheType;
    NSString *_text;
    NSString *_semantic;
    unsigned int _resultType;
    FBGraphSearchStructuredText *_structuredText;
    NSAttributedString *_summaryAttributedText;
}

+ (id)createSuggestionForStructuredText:(id)arg1;
@property(readonly, copy, nonatomic) NSAttributedString *summaryAttributedText; // @synthesize summaryAttributedText=_summaryAttributedText;
@property(readonly, nonatomic) FBGraphSearchStructuredText *structuredText; // @synthesize structuredText=_structuredText;
@property(readonly, nonatomic) unsigned int resultType; // @synthesize resultType=_resultType;
@property(readonly, copy, nonatomic) NSString *semantic; // @synthesize semantic=_semantic;
@property(readonly, copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(nonatomic) BOOL isNonCacheable; // @synthesize isNonCacheable=_isNonCacheable;
@property(nonatomic) unsigned int cacheType; // @synthesize cacheType=_cacheType;
- (void).cxx_destruct;
- (id)suggestionTypeForLogging;
- (id)initWithStructuredText:(id)arg1 summaryAttributedText:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

