//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBSimpleSearchNullStateServiceProtocol-Protocol.h"

@class FBConsistentLookasideCacheObservationHandle, FBUserSession, NSArray, NSAttributedString, NSMutableDictionary, NSSet, NSString, NSTimer;
@protocol FBServiceTransactionMutating;

@interface FBSimpleSearchHeadPublisherNullStateService : NSObject <FBSimpleSearchNullStateServiceProtocol>
{
    FBUserSession *_session;
    BOOL _loading;
    NSTimer *_periodicTimer;
    NSTimer *_afterFollowTimer;
    NSMutableDictionary *_clcHandles;
    FBConsistentLookasideCacheObservationHandle *_observer;
    NSArray *_recentSearchesSuggestions;
    NSAttributedString *_recentSearchesSectionTitle;
    NSArray *_pymlSuggestions;
    NSAttributedString *_pymlSuggestionSectionTitle;
    id <FBServiceTransactionMutating> _token;
    BOOL _isNullStateReady;
    NSArray *_nullStateTitlesAndSuggestions;
}

@property(nonatomic) BOOL isNullStateReady; // @synthesize isNullStateReady=_isNullStateReady;
@property(retain) NSArray *nullStateTitlesAndSuggestions; // @synthesize nullStateTitlesAndSuggestions=_nullStateTitlesAndSuggestions;
- (void).cxx_destruct;
- (void)_recommendedPageChanged:(id)arg1;
- (void)_pymlConnectionChanged:(id)arg1;
- (id)_getSubtextForPage:(id)arg1;
- (void)_updateNullstateTitlesAndSuggestions;
- (BOOL)_isDuplicate:(id)arg1 and:(id)arg2;
- (void)_insertToRecentSearchesInternal:(id)arg1;
- (id)_createPYMLSuggestions:(id)arg1;
- (void)_loadPYML;
- (BOOL)_isNullStateReady;
- (void)_forceLoadNullState;
- (BOOL)isSectionTitleRecentSearches:(id)arg1;
- (void)insertToRecentSearches:(id)arg1;
- (void)loadNullState;
- (void)stopAppServiceWithDependencies:(id)arg1;
- (void)startAppServiceWithDependencies:(id)arg1;
@property(readonly, copy, nonatomic) NSSet *appServiceDependencyIDs;
@property(readonly, copy, nonatomic) NSString *appServiceID;
@property(readonly, nonatomic) unsigned int serviceStartupLevel;
- (void)dealloc;
- (id)init;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly, nonatomic) unsigned int numberOfRecentSearches;
@property(readonly) Class superclass;

@end

