//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCopying-Protocol.h"

@class NSString;

@interface FBStickerResourceTypeConfig : FBValueObject <NSCopying>
{
    BOOL _preloadable;
    NSString *_namePrefix;
    NSString *_fileExtension;
    struct CGSize _maxSize;
}

@property(readonly, nonatomic) BOOL preloadable; // @synthesize preloadable=_preloadable;
@property(readonly, copy, nonatomic) NSString *fileExtension; // @synthesize fileExtension=_fileExtension;
@property(readonly, copy, nonatomic) NSString *namePrefix; // @synthesize namePrefix=_namePrefix;
@property(readonly, nonatomic) struct CGSize maxSize; // @synthesize maxSize=_maxSize;
- (void).cxx_destruct;
- (id)initWithMaxSize:(struct CGSize)arg1 namePrefix:(id)arg2 fileExtension:(id)arg3 preloadable:(BOOL)arg4;

@end

