//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSError, NSString;

@interface FBStoryStreamLoadResultBuilder : NSObject
{
    BOOL _cancelled;
    unsigned int _edgeCount;
    NSString *_endCursor;
    NSError *_error;
    BOOL _hasNextPage;
    NSString *_startCursor;
}

+ (id)aStreamLoadResult;
- (void).cxx_destruct;
- (id)withStartCursor:(id)arg1;
- (id)withHasNextPage:(BOOL)arg1;
- (id)withError:(id)arg1;
- (id)withEndCursor:(id)arg1;
- (id)withEdgeCount:(unsigned int)arg1;
- (id)withCancelled:(BOOL)arg1;
- (id)build;

@end

