//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBExperimentContext.h"

@interface FBStateRestorationExperimentContext : FBExperimentContext
{
    BOOL _shouldLogRevivalTime;
    BOOL _shouldRestoreAppSection;
    BOOL _shouldRestorePermalinkFromFeed;
    BOOL _shouldRestorePermalinkEverywhere;
    double _lastActiveTimeRestorationThreshold;
}

+ (BOOL)allowUserInterfaceIdiom:(int)arg1;
+ (id)parameterConfigurations;
+ (id)experimentName;
@property(readonly, nonatomic) BOOL shouldRestorePermalinkEverywhere; // @synthesize shouldRestorePermalinkEverywhere=_shouldRestorePermalinkEverywhere;
@property(readonly, nonatomic) BOOL shouldRestorePermalinkFromFeed; // @synthesize shouldRestorePermalinkFromFeed=_shouldRestorePermalinkFromFeed;
@property(readonly, nonatomic) BOOL shouldRestoreAppSection; // @synthesize shouldRestoreAppSection=_shouldRestoreAppSection;
@property(readonly, nonatomic) double lastActiveTimeRestorationThreshold; // @synthesize lastActiveTimeRestorationThreshold=_lastActiveTimeRestorationThreshold;
@property(readonly, nonatomic) BOOL shouldLogRevivalTime; // @synthesize shouldLogRevivalTime=_shouldLogRevivalTime;

@end

