//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBStickerPackDetailsQuery : NSObject
{
}

+ (id)graphQLQueryWithAnimatedImageType:(id)arg1 buttonSize:(id)arg2 imageSize:(id)arg3 imageType:(id)arg4 limit:(id)arg5 scale:(id)arg6 stickerPackId:(id)arg7 thumbnailScale:(id)arg8 thumbnailSize:(id)arg9 thumbnailType:(id)arg10;

@end

