//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBStream.h"

#import "FBGraphQLConnectionControllerListener-Protocol.h"
#import "FBGraphQLConnectionStoreListener-Protocol.h"
#import "FBGraphQLPagedDownloading-Protocol.h"

@class FBFeedGraphQLConnectionInfo, NSString;
@protocol FBGraphQLConnectionInterface;

@interface FBStoryStream : FBStream <FBGraphQLPagedDownloading, FBGraphQLConnectionStoreListener, FBGraphQLConnectionControllerListener>
{
    BOOL _enableUDPPriming;
    id <FBGraphQLConnectionInterface> _connection;
    FBFeedGraphQLConnectionInfo *_connectionInfo;
}

+ (id)_chunkingAfterCursorJSONPathForFeedType:(int)arg1 request:(id)arg2;
+ (unsigned int)_secondChunkSizeForFeedType:(int)arg1 loadType:(unsigned int)arg2 refreshMode:(unsigned int)arg3 session:(id)arg4;
+ (unsigned int)_firstChunkSizeForFeedType:(int)arg1 loadType:(unsigned int)arg2 refreshMode:(unsigned int)arg3 session:(id)arg4;
+ (BOOL)_chunkSizeExperimentationAllowedForFeedType:(int)arg1;
+ (void)_configuredChunkedRequest:(id)arg1 withCursor:(id)arg2 limit:(unsigned int)arg3 loadType:(unsigned int)arg4 feedType:(int)arg5 refreshMode:(unsigned int)arg6 session:(id)arg7;
+ (id)graphQLRequestWithParameters:(id)arg1 feedType:(int)arg2 enableUDPPriming:(BOOL)arg3 callbackPerformer:(id)arg4 subsequentRequest:(BOOL)arg5 queryOptions:(id)arg6;
@property(readonly, nonatomic) BOOL enableUDPPriming; // @synthesize enableUDPPriming=_enableUDPPriming;
@property(readonly, copy, nonatomic) FBFeedGraphQLConnectionInfo *connectionInfo; // @synthesize connectionInfo=_connectionInfo;
@property(readonly, nonatomic) id <FBGraphQLConnectionInterface> connection; // @synthesize connection=_connection;
- (void).cxx_destruct;
- (void)_graphQLConnectionDidFinishAttemptingToRestoreFirstPersistedPage;
- (void)graphQLConnectionControllerDidFinishAttemptingToRestoreFirstPersistedPage:(id)arg1;
- (void)graphQLConnectionStoreDidFinishAttemptingToRestoreFirstPersistedPage:(id)arg1;
- (void)_load:(unsigned int)arg1 refreshMode:(unsigned int)arg2 backgroundFetch:(BOOL)arg3;
- (void)streamLoadDidFinishLoading:(id)arg1;
@property(readonly, copy) NSString *description;
- (id)initWithSession:(id)arg1 targetID:(id)arg2 scenePath:(id)arg3 analyticsUUID:(id)arg4 pollingSource:(id)arg5;
- (id)initWithSession:(id)arg1 connection:(id)arg2 connectionInfo:(id)arg3 enableUDPPriming:(BOOL)arg4 scenePathProvider:(id)arg5 analyticsUUID:(id)arg6 queryOptions:(id)arg7;
- (BOOL)lastHeadLoadWasRetried;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) BOOL enabled;
@property(readonly) unsigned int hash;
@property(nonatomic) double refreshInterval;
@property(readonly) Class superclass;

@end

