//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBStorySetHscrollContentComponentState : NSObject
{
    BOOL _appFeedRequestSent;
    id _currentChildScopeFrameID;
}

+ (id)newWithCurrentChildScopeFrameID:(id)arg1 appFeedRequestSent:(BOOL)arg2;
@property(readonly, nonatomic) BOOL appFeedRequestSent; // @synthesize appFeedRequestSent=_appFeedRequestSent;
@property(readonly, nonatomic) id currentChildScopeFrameID; // @synthesize currentChildScopeFrameID=_currentChildScopeFrameID;
- (id)initWithCurrentChildScopeFrameID:(id)arg1 appFeedRequestSent:(BOOL)arg2;

@end

