//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBSimpleNetworkerRequest.h"

@interface FBSubscribeRequest : FBSimpleNetworkerRequest
{
}

- (id)initWithSubscriberFBID:(id)arg1 subscribeeFBID:(id)arg2 followLocation:(unsigned int)arg3 subscribe:(BOOL)arg4 callbackPerformer:(id)arg5;
- (id)initWithRequest:(id)arg1 session:(id)arg2;

@end

