//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBPhotoTagGuideTaglet, FBTagContainerView, FBUserSession, NSArray, NSMutableArray;
@protocol FBPhotoTagGuideTagletDelegate;

@interface FBTagAggregator : NSObject
{
    NSMutableArray *_photoTaglets;
    FBUserSession *_session;
    id <FBPhotoTagGuideTagletDelegate> _delegate;
    float _scale;
    float _minimumScale;
    float _maximumScale;
    FBPhotoTagGuideTaglet *_tagGuideTaglet;
    FBTagContainerView *_view;
    NSArray *_tagletsCommitted;
    NSArray *_tagletsGenerated;
}

@property(retain, nonatomic) NSArray *tagletsGenerated; // @synthesize tagletsGenerated=_tagletsGenerated;
@property(retain, nonatomic) NSArray *tagletsCommitted; // @synthesize tagletsCommitted=_tagletsCommitted;
@property(retain, nonatomic) FBTagContainerView *view; // @synthesize view=_view;
@property(readonly, nonatomic) FBPhotoTagGuideTaglet *tagGuideTaglet; // @synthesize tagGuideTaglet=_tagGuideTaglet;
@property(nonatomic) float maximumScale; // @synthesize maximumScale=_maximumScale;
@property(nonatomic) float minimumScale; // @synthesize minimumScale=_minimumScale;
@property(nonatomic) float scale; // @synthesize scale=_scale;
@property(nonatomic) __weak id <FBPhotoTagGuideTagletDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)commitWithAnimation:(unsigned int)arg1;
- (void)adjustScaleWithMultiplier:(float)arg1;
- (void)generateAggregatedTagletsWithMinimumScale:(float)arg1 maximumScale:(float)arg2;
@property(readonly, nonatomic) BOOL generated;
- (void)removeTagGuide;
- (void)addTagGuideForFacebox:(id)arg1;
- (id)findTagletByTaggbleEdge:(id)arg1;
- (void)removeAllTaglets;
- (void)removeAllTaggableEdges;
- (void)removeTaggable:(id)arg1;
- (void)addPhotoTaglet:(id)arg1;
- (void)addTaggableEdge:(id)arg1;
- (void)refresh;
@property(nonatomic) BOOL dirty;
- (void)setScale:(float)arg1 animated:(BOOL)arg2;
- (void)_setScaleState;
- (id)initWithSession:(id)arg1;

@end

