//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "ASControlNode.h"

@class ASImageNode, ASTextNode, CALayer, NSAttributedString;
@protocol ASTextNodeDelegate;

@interface FBTextAnnotationNode : ASControlNode
{
    ASImageNode *_imageNode;
    ASTextNode *_textNode;
    struct UIEdgeInsets _textContentInsets;
    float _textCenter;
}

+ (id)_textNodeWithString:(id)arg1;
+ (id)annotationNodeWithText:(id)arg1 icon:(id)arg2 needsInteraction:(BOOL)arg3 needsTransition:(BOOL)arg4;
@property(readonly, nonatomic) float textCenter; // @synthesize textCenter=_textCenter;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)layout;
@property(readonly, nonatomic) CALayer *textLayer;
@property(nonatomic) __weak id <ASTextNodeDelegate> delegate;
@property(copy, nonatomic) NSAttributedString *attributedString;
- (struct CGSize)calculateSizeThatFits:(struct CGSize)arg1;
- (void)removeIconAnimations;
- (void)addIconAnimation:(id)arg1;
- (id)initWithText:(id)arg1 icon:(id)arg2;

@end

