//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "CKComponent.h"

@interface FBThrowbackUnifiedFeedPromotionFullWidthHeaderImageComponent : CKComponent
{
    CKComponent *_image;
    struct CGSize _imageSize;
    struct UIEdgeInsets _insets;
}

+ (id)newWithImage:(id)arg1 insets:(struct UIEdgeInsets)arg2 toolbox:(id)arg3;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct CKComponentLayout)computeLayoutThatFits:(struct CKSizeRange)arg1;

@end

