//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBValueObject.h"

#import "NSCopying-Protocol.h"

@class NSArray, NSString;

@interface FBThrowbackEmptyStateModel : FBValueObject <NSCopying>
{
    BOOL _isMegaphone;
    NSString *_title;
    NSString *_subtitle;
    NSString *_buttonText;
    NSArray *_images;
}

@property(readonly, nonatomic) BOOL isMegaphone; // @synthesize isMegaphone=_isMegaphone;
@property(readonly, copy, nonatomic) NSArray *images; // @synthesize images=_images;
@property(readonly, copy, nonatomic) NSString *buttonText; // @synthesize buttonText=_buttonText;
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 buttonText:(id)arg3 images:(id)arg4 isMegaphone:(BOOL)arg5;

@end

