//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBNetworkerRequest.h"

@class NSArray, NSString;

@interface FBTimelineAppCollectionPlusRequest : FBNetworkerRequest
{
    NSString *_collectionID;
    NSString *_itemID;
    NSString *_action;
    NSString *_privacyScopeJson;
    NSString *_curationSurface;
    NSString *_curationMechanism;
    NSString *_storyGraphQLID;
    NSArray *_trackingCodes;
    NSString *_saveContext;
    NSString *_actionType;
}

@property(copy, nonatomic) NSString *actionType; // @synthesize actionType=_actionType;
@property(copy, nonatomic) NSString *saveContext; // @synthesize saveContext=_saveContext;
@property(copy, nonatomic) NSArray *trackingCodes; // @synthesize trackingCodes=_trackingCodes;
@property(copy, nonatomic) NSString *storyGraphQLID; // @synthesize storyGraphQLID=_storyGraphQLID;
@property(copy, nonatomic) NSString *curationMechanism; // @synthesize curationMechanism=_curationMechanism;
@property(copy, nonatomic) NSString *curationSurface; // @synthesize curationSurface=_curationSurface;
@property(copy, nonatomic) NSString *privacyScopeJson; // @synthesize privacyScopeJson=_privacyScopeJson;
@property(readonly, copy, nonatomic) NSString *action; // @synthesize action=_action;
@property(copy, nonatomic) NSString *itemID; // @synthesize itemID=_itemID;
@property(copy, nonatomic) NSString *collectionID; // @synthesize collectionID=_collectionID;
- (void).cxx_destruct;
- (BOOL)isEqual:(id)arg1;
- (unsigned int)hash;
- (id)networkRequest;
- (BOOL)isPlus;
- (id)initWithItemID:(id)arg1 collectionID:(id)arg2 actionType:(id)arg3 privacyScope:(id)arg4 curationSurface:(id)arg5 curationMechanism:(id)arg6 storyGraphQLID:(id)arg7 trackingCodes:(id)arg8 saveContext:(id)arg9 callbackPerformer:(id)arg10;

@end

