//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSDateFormatter;
@protocol OS_dispatch_queue;

@interface FBTimeSyncer : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSDateFormatter *_dateStringFormatter;
    double _lastServerTimeSyncUnixTime;
    BOOL _hasTimeEstimate;
    double _serverTimeDelta;
}

+ (id)sharedTimeSyncer;
@property double serverTimeDelta; // @synthesize serverTimeDelta=_serverTimeDelta;
- (void).cxx_destruct;
- (void)didReceiveFacebookDateString:(id)arg1;
- (void)_processDateString:(id)arg1 receiptTime:(id)arg2;
@property(readonly) NSDate *estimatedCurrentServerTime;
- (id)init;

@end

