//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class FBGraphQLDownloadRequest, FBScenePath, FBUserSession;
@protocol FBTrendingEntitiesRequestParserDelegate;

@interface FBTrendingEntitiesRequestParser : NSObject
{
    FBUserSession *_session;
    id <FBTrendingEntitiesRequestParserDelegate> _delegate;
    FBGraphQLDownloadRequest *_entitiesRequest;
    FBScenePath *_scenePath;
}

@property(retain, nonatomic) FBScenePath *scenePath; // @synthesize scenePath=_scenePath;
@property(retain, nonatomic) FBGraphQLDownloadRequest *entitiesRequest; // @synthesize entitiesRequest=_entitiesRequest;
@property(nonatomic) __weak id <FBTrendingEntitiesRequestParserDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)cancel;
- (void)_handleResponse:(id)arg1 blockSelf:(id)arg2;
- (void)requestTrendingEntities;
- (void)dealloc;
- (id)initWithSession:(id)arg1 scenePath:(id)arg2;

@end

