//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSString, NSURL;

@interface FBUpdate : NSObject
{
    NSString *_name;
    NSString *_buildNumber;
    NSString *_bundleIdentifier;
    NSString *_releaseNotes;
    NSString *_version;
    NSURL *_itmsURL;
    NSURL *_downloadURL;
    NSString *_releaseTag;
    NSString *_releaseChannel;
    NSDate *_publicationDate;
    unsigned int _archiveSize;
    unsigned int _uncompressedArchiveSize;
    unsigned int _type;
    unsigned int _networkRequirements;
    unsigned int _retryInterval;
}

+ (id)updateFromFQLQueryResult:(id)arg1;
+ (id)updateFromEndpointResponse:(id)arg1;
@property(nonatomic) unsigned int retryInterval; // @synthesize retryInterval=_retryInterval;
@property(nonatomic) unsigned int networkRequirements; // @synthesize networkRequirements=_networkRequirements;
@property(nonatomic) unsigned int type; // @synthesize type=_type;
@property(nonatomic) unsigned int uncompressedArchiveSize; // @synthesize uncompressedArchiveSize=_uncompressedArchiveSize;
@property(nonatomic) unsigned int archiveSize; // @synthesize archiveSize=_archiveSize;
@property(copy, nonatomic) NSDate *publicationDate; // @synthesize publicationDate=_publicationDate;
@property(copy, nonatomic) NSString *releaseChannel; // @synthesize releaseChannel=_releaseChannel;
@property(copy, nonatomic) NSString *releaseTag; // @synthesize releaseTag=_releaseTag;
@property(retain, nonatomic) NSURL *downloadURL; // @synthesize downloadURL=_downloadURL;
@property(retain, nonatomic) NSURL *itmsURL; // @synthesize itmsURL=_itmsURL;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *releaseNotes; // @synthesize releaseNotes=_releaseNotes;
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(copy, nonatomic) NSString *buildNumber; // @synthesize buildNumber=_buildNumber;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (BOOL)isSameBundleAsCurrentApp;
- (BOOL)isMoreRecentThanCurrentApp;
- (BOOL)isMoreRecentThan:(id)arg1;
- (BOOL)isMoreRecentThanBundle:(id)arg1;
- (BOOL)isSameBundleAs:(id)arg1;
- (BOOL)canDownloadOnNetwork:(unsigned int)arg1;
- (unsigned int)uniqueIdentifier;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (BOOL)isShellUpdate;
- (BOOL)_isVersionKind;
- (BOOL)_isAutoUpdaterKind;
- (BOOL)_isShellKind;
- (BOOL)_isCurrentAppUpdateKind;
- (unsigned int)kind;

@end

