//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBUpdateDataFetcher, NSArray, NSData, NSError;

@protocol FBUpdateDataFetcherDelegate <NSObject>
- (void)updateDataFetcher:(FBUpdateDataFetcher *)arg1 didFailWithError:(NSError *)arg2;
- (void)updateDataFetcher:(FBUpdateDataFetcher *)arg1 didReceiveUpdates:(NSArray *)arg2;

@optional
- (void)updateDataFetcher:(FBUpdateDataFetcher *)arg1 didReceiveData:(NSData *)arg2;
- (void)updateDataFetcher:(FBUpdateDataFetcher *)arg1 didUpdateDownloadProgress:(float)arg2 complete:(BOOL)arg3;
- (void)updateDataFetcherDidBeginFetchingData:(FBUpdateDataFetcher *)arg1;
@end

