//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "FBVerveViewState.h"

@class NSString;

@interface FBVerveButtonViewState : FBVerveViewState
{
    NSString *_buttonSize;
    NSString *_buttonStyle;
    id _buttonColor;
    NSString *_title;
    BOOL _enabled;
    _Bool _definesButtonSize;
    _Bool _definesButtonStyle;
    _Bool _definesButtonColor;
    _Bool _definesTitle;
    _Bool _definesEnabled;
}

+ (Class)FBVerve_getProperties:(CDStruct_183601bc **)arg1 count:(unsigned int *)arg2;
- (void).cxx_destruct;

@end

