//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface FBVideoCapturePermissionsManager : NSObject
{
}

+ (void)_requestMicrophonePermissionsWithCameraPermissionGrantedBlock:(CDUnknownBlockType)arg1;
+ (void)_requestSystemVideoAndAudioPermissionsWithPermissionGrantedBlock:(CDUnknownBlockType)arg1 permissionDeniedBlock:(CDUnknownBlockType)arg2;
+ (void)_showAudioAndVideoCapturePermissionsPrePromptWithPermissionGrantedBlock:(CDUnknownBlockType)arg1 permissionDeniedBlock:(CDUnknownBlockType)arg2;
+ (void)checkVideoCapturePermissionsWithPermissionGrantedBlock:(CDUnknownBlockType)arg1 permissionDeniedBlock:(CDUnknownBlockType)arg2 shouldRequestPermission:(BOOL)arg3;

@end

