//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface FBVideoPlayerManager : NSObject
{
    NSMutableDictionary *_videoPlayerStates;
    struct Mutex _videoPlayerStatesLock;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)findOrCreateVideoPlayerStateForVideoWithID:(id)arg1;
- (id)videoPlayerStateBuilderForVideoWithID:(id)arg1;
- (void)updateHasShownSoundPrompt:(BOOL)arg1 forVideoWithID:(id)arg2;
- (void)updateDidLogStartedPlaying:(BOOL)arg1 forVideoWithID:(id)arg2;
- (void)updateHasDisplayed:(BOOL)arg1 forVideoWithID:(id)arg2;
- (void)updateManuallyPaused:(BOOL)arg1 forVideoWithID:(id)arg2;
- (void)updateDidPlayToEnd:(BOOL)arg1 time:(double)arg2 isOnEndScreen:(BOOL)arg3 forVideoWithID:(id)arg4;
- (id)videoPlayerStateForVideoWithID:(id)arg1;
- (id)init;
- (id)initWithSession:(id)arg1;

@end

