//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UISlider.h>

@class UIView;

@interface FBVideoScrubber : UISlider
{
    UIView *_trackView;
    UIView *_trackMinView;
    UIView *_trackLoadingView;
    UIView *_trackMaxView;
    BOOL _newStyle;
    float _currentScrubberHeight;
    float _currentInset;
    float _playableDuration;
    float _trackInsetWhileScrubbing;
    float _hitAreaBelowScrubber;
}

@property(nonatomic) float hitAreaBelowScrubber; // @synthesize hitAreaBelowScrubber=_hitAreaBelowScrubber;
@property(nonatomic) float trackInsetWhileScrubbing; // @synthesize trackInsetWhileScrubbing=_trackInsetWhileScrubbing;
@property(nonatomic) float playableDuration; // @synthesize playableDuration=_playableDuration;
- (void).cxx_destruct;
- (BOOL)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)_scrubberIsNotBeingUsed:(id)arg1;
- (void)_scrubberIsBeingUsed:(id)arg1;
- (id)_imageWithColor:(id)arg1;
- (id)_imageWithColor:(id)arg1 andSize:(struct CGRect)arg2;
- (void)_updateTrackLoadingViewFrame;
- (void)setPlayableDuration:(float)arg1 animated:(BOOL)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1 usingNewStyle:(BOOL)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

