//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSProxy.h>

#import "FBIntentHandler-Protocol.h"

@class NSString, UIViewController;

@interface FBViewControllerProxyingIntentHandler : NSProxy <FBIntentHandler>
{
    UIViewController *_viewController;
}

+ (id)proxyingIntentHandlerForViewController:(id)arg1;
- (void).cxx_destruct;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (id)_resolvedIntentHandler;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

