//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBVideoChannelDimmingLayer, UICollectionView, UINavigationBar;

@interface FBVideoChannelView : UIView
{
    UIView *_statusBarOverlay;
    FBVideoChannelDimmingLayer *_headerDimmingOverlay;
    UICollectionView *_collectionView;
    UINavigationBar *_navigationBar;
    CDUnknownBlockType _didInteractWithBlock;
}

@property(copy, nonatomic) CDUnknownBlockType didInteractWithBlock; // @synthesize didInteractWithBlock=_didInteractWithBlock;
@property(readonly, nonatomic) UINavigationBar *navigationBar; // @synthesize navigationBar=_navigationBar;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)loseFocusOnVideo;
- (void)focusOnVideo;
- (id)initWithFrame:(struct CGRect)arg1 session:(id)arg2;

@end

