//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "MNCollectionViewLayoutAttributesTransforming-Protocol.h"

@class NSString;

@interface MNCollectionViewLayoutAttributesBlockTransformer : NSObject <MNCollectionViewLayoutAttributesTransforming>
{
    CDUnknownBlockType _block;
}

+ (id)transformerWithBlock:(CDUnknownBlockType)arg1;
- (void).cxx_destruct;
- (void)apply:(id)arg1 inContext:(struct MNCollectionViewLayoutAttributesTransformContext)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

