//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBMImageViewDownloader, FBMThreadParticipantFilter, NSArray, NSDictionary, NSMutableArray;
@protocol FBGenericThread, FBMAttachmentURLFormatting, FBMessengerRequestManager, MNAuthenticationManager;

@interface MNThreadImageView : UIView
{
    NSArray *_contacts;
    NSMutableArray *_imageViews;
    id <FBGenericThread> _thread;
    NSDictionary *_usersByUserId;
    int _splitMode;
    id <MNAuthenticationManager> _authManager;
    FBMImageViewDownloader *_fbmImageViewDownloader;
    FBMThreadParticipantFilter *_threadParticipantFilter;
    id <FBMessengerRequestManager> _requestManager;
    id <FBMAttachmentURLFormatting> _attachmentURLFormatter;
}

@property(retain, nonatomic) id <FBMAttachmentURLFormatting> attachmentURLFormatter; // @synthesize attachmentURLFormatter=_attachmentURLFormatter;
@property(retain, nonatomic) id <FBMessengerRequestManager> requestManager; // @synthesize requestManager=_requestManager;
@property(retain, nonatomic) FBMThreadParticipantFilter *threadParticipantFilter; // @synthesize threadParticipantFilter=_threadParticipantFilter;
@property(retain, nonatomic) FBMImageViewDownloader *fbmImageViewDownloader; // @synthesize fbmImageViewDownloader=_fbmImageViewDownloader;
@property(retain, nonatomic) id <MNAuthenticationManager> authManager; // @synthesize authManager=_authManager;
@property(nonatomic) int splitMode; // @synthesize splitMode=_splitMode;
@property(copy, nonatomic) NSDictionary *usersByUserId; // @synthesize usersByUserId=_usersByUserId;
@property(retain, nonatomic) id <FBGenericThread> thread; // @synthesize thread=_thread;
- (void).cxx_destruct;
- (void)cancelSetImages;
- (float)imageSplitXPosition;
- (void)layoutSubviews;
- (void)_layoutLowerRightImage:(id)arg1;
- (void)_layoutUpperRightImage:(id)arg1;
- (void)_layoutRightSplitImages:(unsigned int)arg1;
- (void)_layoutLeftSplitImageForContact:(id)arg1;
- (void)_layoutFullImageForContact:(id)arg1;
- (void)layoutFullImageForThread;
- (void)_setImageView:(id)arg1 forContact:(id)arg2 useLarge:(BOOL)arg3 usePlaceholder:(BOOL)arg4;
- (id)_picUrlForThread;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 fbmImageViewDownloader:(id)arg2 participantFilter:(id)arg3 requestManager:(id)arg4;

@end

