//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSString.h>

@interface NSString (JSONKitSerializing)
- (id)JSONStringWithOptions:(unsigned int)arg1 includeQuotes:(BOOL)arg2 error:(id *)arg3;
- (id)JSONString;
- (id)JSONDataWithOptions:(unsigned int)arg1 includeQuotes:(BOOL)arg2 error:(id *)arg3;
- (id)JSONData;
- (id)fb_JSONStringWithOptions:(unsigned int)arg1 includeQuotes:(BOOL)arg2 error:(id *)arg3;
- (id)fb_JSONString;
- (id)fb_JSONDataWithOptions:(unsigned int)arg1 includeQuotes:(BOOL)arg2 error:(id *)arg3;
- (id)fb_JSONData;
@end

