//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import "SBNuxFlowDescriptionAndPermissions.h"

#import "SBNuxDescriptionPrivacyUnderlinedViewDelegate-Protocol.h"

@class NSString;

@interface SBNuxFlowUnderlinedDescription : SBNuxFlowDescriptionAndPermissions <SBNuxDescriptionPrivacyUnderlinedViewDelegate>
{
}

- (void)didTapMoreInfoButton:(id)arg1;
- (void)didTapNotNowButton:(id)arg1;
- (void)didTapSyncPhotosButton:(id)arg1;
- (id)initWithSyncPreferences:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

