//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (FBColor)
+ (id)fb_colorWithHexString:(id)arg1;
+ (id)fb_hexStringForColor:(id)arg1;
+ (id)fb_colorWithHex:(unsigned int)arg1;
- (id)fb_darker_color;
- (id)fb_accessibilityEnabledColor;
- (BOOL)fb_isOpaque;
@end

