//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (FBPhotoColors)
+ (id)fb_albumCellSizeTextColor;
+ (id)fb_loadingCellOpaqueBackgroundColor;
+ (id)fb_loadingCellBackgroundColor;
+ (id)fb_lightShadowColor;
+ (id)fb_photoModuleBackgroundColor;
@end

