//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug 12 2015 14:15:46).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2014 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "FBSessionClassProvidable-Protocol.h"
#import "ZRHeaderDataFetcherDelegate-Protocol.h"
#import "ZRHeaderRequestDataFetcherDelegate-Protocol.h"

@class FBUserSession, NSDictionary, NSString, ZRApplicationState, ZRHeaderDataFetcher, ZRHeaderDataSender, ZRHeaderRequestDataFetcher, ZRTokenCurrentNetwork, ZRTokenUpdater;
@protocol FBProvider, ZRProjectGatingDelegate;

@interface ZRHeaderRequestCoordinator : NSObject <FBSessionClassProvidable, ZRHeaderDataFetcherDelegate, ZRHeaderRequestDataFetcherDelegate>
{
    id <FBProvider> _headerRequestFetcherProvider;
    ZRApplicationState *_zeroRatingState;
    ZRTokenUpdater *_zeroTokenUpdater;
    id <ZRProjectGatingDelegate> _projectGater;
    ZRTokenCurrentNetwork *_network;
    FBUserSession *_session;
    ZRHeaderRequestDataFetcher *_headerRequestFetcher;
    ZRHeaderDataFetcher *_headerDataFetcher;
    ZRHeaderDataSender *_headerDataSender;
    NSDictionary *_headerRequestParams;
}

@property(copy, nonatomic) NSDictionary *headerRequestParams; // @synthesize headerRequestParams=_headerRequestParams;
@property(retain, nonatomic) ZRHeaderDataSender *headerDataSender; // @synthesize headerDataSender=_headerDataSender;
@property(retain, nonatomic) ZRHeaderDataFetcher *headerDataFetcher; // @synthesize headerDataFetcher=_headerDataFetcher;
@property(retain, nonatomic) ZRHeaderRequestDataFetcher *headerRequestFetcher; // @synthesize headerRequestFetcher=_headerRequestFetcher;
- (void)_refreshZeroHeaderRequest;
- (void)couldNotFetchHeaderData:(id)arg1;
- (void)didFetchHeaderData:(id)arg1;
- (void)couldNotFetchZeroHeaderRequest:(id)arg1;
- (void)didFetchZeroHeaderRequest:(id)arg1;
- (id)initWithProviderMapData:(id)arg1;
- (void)stop;
- (void)start;
- (void)dealloc;
- (id)init;
- (id)initWithHeaderRequestFetcherProvider:(id)arg1 zeroRatingState:(id)arg2 zeroTokenUpdater:(id)arg3 projectGater:(id)arg4 network:(id)arg5 session:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

